### ISSUE TITLE
v3.1.4 appointment repeat doesn't seem to work 

### ISSUE THREAD

**Issue by daniilsunyaev** [lfos/calcurse#10]
Hello!
Just installed v3.1.4 (v4 is not yet available at debian stable repos), and it looks like I can't use "repeat" option for appointments.
When I hit `r` (while focused at the appointment), I'm asked about repetition rate (daily, weekly, monthly, or yearly) but pressing `d`, `w`, `m`, `y` yields nothing.
Any Ideas?

**Comment by coachshea** [comment]
I'd recommend downloading and building it from source. I'm on Debian and it compiles just fine. it's very easy to do and it is greatly improved from the Debian version.

**Comment by daniilsunyaev** [comment]
Hmm, interesting, it works okay if I'm disabling native language support when building from sources.
I think I'm fine with eng interface. Thus, building from sources solves my issue, thanks!

**Comment by coachshea** [comment]
Glad it helped. You should check out some of the scripts in the contrib section. Some cool features that you might find helpful.

**Comment by lfos** [comment]
Seems like there is an issue with the translation then... Which locale are you using?

**Comment by daniilsunyaev** [comment]
It was russian.
