### ISSUE TITLE
I can't sync my Nextcloud calendar using the CALCURSE_CALDAV_PASSWORD variable

### ISSUE THREAD

**Issue by maxigaz** [lfos/calcurse#101]
When I set my password for HTTP Basic Authentication in ~/.calcurse/caldav/config, I can sync my Nextcloud calendar at disroot.org without any problems. However, when I try to do the same with the `CALCURSE_CALDAV_PASSWORD` variable, I get the following error:

```
$ CALCURSE_CALDAV_PASSWORD=somepassword calcurse-caldav
Connecting to cloud.disroot.org...
Loading synchronization database from /home/xxx/.calcurse/caldav/sync.db...
error: The server at cloud.disroot.org replied with HTTP status code 401
error: (Unauthorized) while trying to access https://cloud.disroot.org/remote.ph
error: p/dav/calendars/xxx/<calendar-id>/.
```

I also tried wrapping the password with quotation marks, but they didn't work either:

```
CALCURSE_CALDAV_PASSWORD='somepassword' calcurse-caldav
CALCURSE_CALDAV_PASSWORD="somepassword" calcurse-caldav
```

Consequently, decrypting a file containing the password with GPG (which would be my goal) doesn't work either as I receive the same error as above.

```
CALCURSE_CALDAV_PASSWORD=$(gpg -d ~/.calcurse/caldav/password.gpg) calcurse-caldav
```

**Comment by lfos** [comment]
Are you using a development snapshot? The `CALCURSE_CALDAV_PASSWORD` environment variable is a fairly recent addition and not part of any released version.

**Comment by maxigaz** [comment]
I'm sorry, I forgot to mention that. I'm using v4.3.0, installed from the official repositories of Manjaro Linux.

**Comment by lfos** [comment]
There will probably be a release pretty soon but you'll have to switch to the development version until then.

**Comment by maxigaz** [comment]
I've just tried the latest dev version, and it works, indeed. Thank you!
