### ISSUE TITLE
No Configure Script. Autoconf and Autogen.sh Fail with errors

### ISSUE THREAD

**Issue by peterski007** [lfos/calcurse#11]
Hi there. 

First, thanks for writing this. I've been looking for a 'distraction/clutter-free' calendar app for my mutt. I'd like to use the new functions of CalDev as I am an iMac/iPhone/iPad user and want to sync my calendar with the cloud.

Here's what I've tried. I'm not a C developer but an avid Open Source protagonist.

===============================================================
$./autogen.sh
Copying file ABOUT-NLS
Copying file config.rpath
Creating directory m4
Copying file m4/codeset.m4
Copying file m4/gettext.m4
Copying file m4/glibc21.m4
Copying file m4/iconv.m4
Copying file m4/intdiv0.m4
Copying file m4/intmax.m4
Copying file m4/inttypes-pri.m4
Copying file m4/inttypes.m4
Copying file m4/inttypes_h.m4
Copying file m4/isc-posix.m4
Copying file m4/lcmessage.m4
Copying file m4/lib-ld.m4
Copying file m4/lib-link.m4
Copying file m4/lib-prefix.m4
Copying file m4/longdouble.m4
Copying file m4/longlong.m4
Copying file m4/nls.m4
Copying file m4/po.m4
Copying file m4/printf-posix.m4
Copying file m4/progtest.m4
Copying file m4/signed.m4
Copying file m4/size_max.m4
Copying file m4/stdint_h.m4
Copying file m4/uintmax_t.m4
Copying file m4/ulonglong.m4
Copying file m4/wchar_t.m4
Copying file m4/wint_t.m4
Copying file m4/xsize.m4
Copying file mkinstalldirs
Copying file po/Makefile.in.in
Copying file po/Makevars.template
Copying file po/Rules-quot
Copying file po/boldquot.sed
Copying file po/en@boldquot.header
Copying file po/en@quot.header
Copying file po/insert-header.sin
Copying file po/quot.sed
Copying file po/remove-potcdate.sin
git-version-gen: unknown version number.
configure.ac:8: error: AC_INIT should be called with package and version arguments
/opt/local/share/aclocal-1.15/init.m4:171: AM_INIT_AUTOMAKE is expanded from...
configure.ac:8: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
git-version-gen: unknown version number.
git-version-gen: unknown version number.
configure.ac: error: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
configure.ac: that aclocal.m4 is present in the top-level directory,
configure.ac: and that aclocal.m4 was recently regenerated (using aclocal)
configure.ac:17: installing './config.guess'
configure.ac:17: installing './config.sub'
Makefile.am:7: error: ENABLE_DOCS does not appear in AM_CONDITIONAL
doc/Makefile.am:3: error: HAVE_ASCIIDOC does not appear in AM_CONDITIONAL
doc/Makefile.am:10: error: HAVE_A2X does not appear in AM_CONDITIONAL
doc/Makefile.am:63: error: HAVE_ASCIIDOC does not appear in AM_CONDITIONAL
doc/Makefile.am:68: error: HAVE_A2X does not appear in AM_CONDITIONAL
src/Makefile.am: installing './depcomp'
/opt/local/share/automake-1.15/am/depend2.am: error: am__fastdepCC does not appear in AM_CONDITIONAL
/opt/local/share/automake-1.15/am/depend2.am:   The usual way to define 'am__fastdepCC' is to add 'AC_PROG_CC'
/opt/local/share/automake-1.15/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
/opt/local/share/automake-1.15/am/depend2.am: error: AMDEP does not appear in AM_CONDITIONAL
/opt/local/share/automake-1.15/am/depend2.am:   The usual way to define 'AMDEP' is to add one of the compiler tests
/opt/local/share/automake-1.15/am/depend2.am:     AC_PROG_CC, AC_PROG_CXX, AC_PROG_OBJC, AC_PROG_OBJCXX,
/opt/local/share/automake-1.15/am/depend2.am:     AM_PROG_AS, AM_PROG_GCJ, AM_PROG_UPC
/opt/local/share/automake-1.15/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
parallel-tests: installing './test-driver'
/opt/local/share/automake-1.15/am/check2.am: error: am__EXEEXT does not appear in AM_CONDITIONAL
configure.ac:8: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:10: error: possibly undefined macro: AM_GNU_GETTEXT
configure.ac:11: error: possibly undefined macro: AM_GNU_GETTEXT_VERSION
configure.ac:83: error: possibly undefined macro: AM_CONDITIONAL
peterbarganski macbook calcurse-master 11:03 am

$ls
ABOUT-NLS      Makefile.am    autom4te.cache config.rpath   contrib        mkinstalldirs  test
AUTHORS        NEWS           build-aux      config.sub     depcomp        po             test-driver
COPYING        README         config.guess   configure      doc            scripts
INSTALL        autogen.sh     config.h.in    configure.ac   m4             src
calcurse-master 11:03 am

$./configure
./configure: line 2107: AM_INIT_AUTOMAKE: command not found
./configure: line 2109: syntax error near unexpected token `external'
./configure: line 2109: `AM_GNU_GETTEXT(external)'

===========================================================================
Regards,

Peter

**Comment by lfos** [comment]
It seems like you are neither using Git nor a release tarball which is why git-version-gen fails. You can either download the latest release tarball from [1] or use Git to clone the repository.

[1] http://calcurse.org/downloads/

**Comment by ScrumpyJack** [comment]
can we have a tarball somewhere else? calcurse.org is no more

**Comment by lfos** [comment]
The web server at calcurse.org was down. It should work again now.
