### ISSUE TITLE
Configuration files in another folder

### ISSUE THREAD

**Issue by hiqua** [lfos/calcurse#111]
Issue to find a conclusion to the discussion started on #105. Read the discussion to have the full context.

In short, it would be nice to have an option `-C` to specify where the configuration files are located, especially to avoid incompatibilities when various versions of calcurse are used with the same configuration files (e.g. if they are synchronized between computers).

The question now, is what should be the defaults, and how `-C` should interact with `-D`.

@lhca @lfos let me know once you've agreed on something.

**Comment by hiqua** [comment]
The conclusion would be:
* `-C $cdir` says where the configuration files should be located
* `-D $ddir`: if -C is provided, then $ddir will only contain the data files, and configuration files will be in $cdir. If -C is not provided, $ddir will contain all the files (current behaviour).
The default file layout is not changed (all files in same default directory).

Good for you @lhca  @lfos ?

**Comment by lfos** [comment]
Sounds good to me! Thanks!

**Comment by lhca** [comment]
Agreed.

Give it a thought whether `$cdir` should be optional with default `$ddir/config`.
