### ISSUE TITLE
ToDo caldav synchronization not importing priority

### ISSUE THREAD

**Issue by dottdottdott** [lfos/calcurse#112]
When i sync calcurse with nextcloud using caldav, exporting todo objects works just fine, but importing causes problems.
The objects exportet to nextcloud keep there priority but when i import them they lose the priority. This happens with all toto entries (ones that have been made in calcurse and ones made in nextcloud). 
Everything looks fine, running calcurse-caldav --debug
`<cal:calendar-data>BEGIN:VCALENDAR 
< VERSION:2.0 
< PRODID:-//Nextcloud Tasks v0.9.5 
< BEGIN:VTODO 
< CREATED:20180607T223131 
< DTSTAMP:20180607T223150 
< LAST-MODIFIED:20180607T223150 
< UID:otwzs890od 
< SUMMARY:testeintrag 
< PRIORITY:4 
< PERCENT-COMPLETE:0 
< X-OC-HIDESUBTASKS:0 
< END:VTODO 
< END:VCALENDAR</cal:calendar-data></d:prop><d:status>HTTP/1.1 200 OK</d:status> </d:propstat></d:response></d:multistatus>
`
This also creates duplicate todo entries in calcurse .

**Comment by vxid** [comment]
I have the same issue using radicale.

**Comment by lfos** [comment]
Should be fixed on `pu`. Will merge that into master soon.
