### ISSUE TITLE
Fullscreen Calcurse in terminal

### ISSUE THREAD

**Issue by necronoise** [lfos/calcurse#115]
How do show only the calendar in terminal? I want to make it fullscreen: http://i.imgur.com/wOHq04s.png

**Comment by lfos** [comment]
This is currently not possible.

**Comment by necronoise** [comment]
@lfos I found a way, I use urxvt terminal and resize-font script, so here is: http://i.imgur.com/WOIaM6j.png

**Comment by hiqua** [comment]
Out of curiosity, how do you use this? Is this some sort of widget on your desktop?

**Comment by hiqua** [comment]
Sorry I meant "why" rather than "how" really: why is it useful for you to be able to do that? Because you want to have calcurse as a widget on your desktop?
