### ISSUE TITLE
calcurse not reading EDITOR and VISUAL env vairables

### ISSUE THREAD

**Issue by lukeoftheaura** [lfos/calcurse#117]
I have both the EDITOR and VISUAL environemnt variables set to vim in my zshrc, yet calcurse is still editing notes in `vi`.

OS: arch linux 64 bit
Version: latest in arch repos

**Comment by lfos** [comment]
Works for me. Are you sure your environment variables are set properly? What happens if you launch calcurse from the command line via `VISUAL=vim calcurse`?

**Comment by lukeoftheaura** [comment]
Then it works. No idea why it won't read my usual environment variables though.

**Comment by lfos** [comment]
My guess is that there is something wrong with your setup and the variables aren't actually set properly. Can you check the output of `env`?

**Comment by lukeoftheaura** [comment]
hmm. Env doesn't output it being set but somehow basically every other program knows to use vim. I have no idea what is happening here.

**Comment by lukeoftheaura** [comment]
*facepalms*

forgot to `export`.

**Comment by Kaspyr** [comment]
A Year later and I am also _facepalming_.

Thanks for maintaining this lfos!

**Comment by francescoinblack** [comment]
I would to use both the variables:
VISUAL=nano calcurse
and
EDITOR=nano calcurse
How can i to do ?
