### ISSUE TITLE
Feature request: Directly move appointment to a different date

### ISSUE THREAD

**Issue by Jereviendrai** [lfos/calcurse#12]
Hello,

First of all, thanks for creating this app! It's the only cli calendar I could find with caldav support that actually works.

There's one feature I'm missing, though: When I edit an existing appointment, I can change the start and end times but not the date on which it takes place. I often need to move appointments to different days, and currently this can only be done by copying it, deleting it, and then pasting it to a different day.

It wouldn't matter to me if the appointment was internally deleted and then recreated as long as I can conveniently change the date from the 'edit appointment' menu. Could this be done?

Thanks a lot!

Cheers,
jereviendrai

**Comment by lfos** [comment]
Deleting an item automatically inserts it to the paste buffer. No need to copy the item first.

**Comment by Jereviendrai** [comment]
Oh, all right, that already makes it a lot easier. Thanks for clarifying. 

I still find it a bit odd that it's not possible to specify date and time (as opposed to only time) in the start and end fields. That would not only make it possible to move appointments across dates without deleting them, but would also make it easier to add appointments that span several days without having to first calculate the duration. 

So I'd still like to request this feature :)

**Comment by lfos** [comment]
Fixed by 1f39b5c and adf29c8.

**Comment by bughunter2** [comment]
Suggest to open this bug report again until the following case is also fixed:

An "all day" appointment cannot be moved to a different date, because in this case you aren't asked to choose between editing the item or moving it.

**Comment by lfos** [comment]
> Suggest to open this bug report again until the following case is also fixed:
> 
> An "all day" appointment cannot be moved to a different date, because in this case you aren't asked to choose between editing the item or moving it.

Does delete-paste not work? Is it too unintuitive?

**Comment by bughunter2** [comment]
That works. I consider it a workaround however, and I had to look up this issue to find it. I had expected either a key binding to move an item with, or a prompt (as is the case for non-all-day appointments). Please interpret my comment as a request to make life easier for those who haven't yet found this workaround. :slightly_smiling_face:
