### ISSUE TITLE
calcurse-caldav configparser.MissingSectionHeaderError

### ISSUE THREAD

**Issue by dnjp** [lfos/calcurse#128]
Hello! I will try to be as concise as possible with the issue I am having.

I had Calcurse properly setup with calcurse-caldav to sync with Google. I found it irritating that I had to run calcurse-caldav before calcurse to sync my calendar. As a result, I followed the instructions to write a simple bash script hook to run calcurse-caldav as a pre-sync task. When I went to run calcurse, none of my calendar information synced and I lost all of the previously present information. 

I removed the hook and ran calcurse-caldav again and now I am getting the following error:
```
daniel@daniel-pc:~|⇒  calcurse-caldav
Traceback (most recent call last):
  File "/usr/bin/calcurse-caldav", line 501, in <module>
    config.readfp(open(configfn))
  File "/usr/lib/python3.6/configparser.py", line 763, in readfp
    self.read_file(fp, source=filename)
  File "/usr/lib/python3.6/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib/python3.6/configparser.py", line 1080, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/home/daniel/.calcurse/caldav/config', line: 2
'Binary = calcurse\n'
```

My config file looks like this:

```
[General]
Binary = calcurse
Hostname = apidata.googleusercontent.com
Path = /caldav/v2/[removed email address]/events/
Scope = https://www.googleapis.com/auth/calendar
SyncFilter = cal
AuthMethod = oauth2

InsecureSSL = No

DryRun = No

Verbose = No


[OAuth2]
ClientID = [removed]
ClientSecret = [removed]
Scope = [removed]
RedirectURI = [removed]
```
The config file is encoded as UTF-8 without BOM. 

Any help would be much appreciated!

**Comment by lfos** [comment]
Are you really sure that there's no BOM? What is the output of `head -c3 .calcurse/caldav/config | hexdump -C`?

**Comment by danieljamespost** [comment]
I'm quite sure. I specified `:setlocal nobomb` in Vim when editing the config file.

Here's the output I got:
```
daniel@daniel-pc:~|⇒  head -c3 .calcurse/caldav/config | hexdump -C
00000000  23 20 50                                          |# P|
00000003
```

**Comment by loweryaustin** [comment]
Hey @danieljamespost I noticed that it seems that your `[General]` header is legitimately missing from your config. I say this because in your output I see `# P`

When I tested this on my machine I get the following:
```
host:~ $ head -c3 .calcurse/caldav/config | hexdump -C 
00000000  23 20 49                                          |# I|
00000003
```

I am seeing `# I` becausee that what is at the very start of my config file.

At the very start of your file is `# P` which is the line directly below the `[General]` header. You can see this in the following:
```
host:~ $ head .calcurse/caldav/config 
# If you want to synchronize calcurse with a CalDAV server using
# calcurse-caldav, create a new directory ~/.calcurse/caldav/, copy this file
# to ~/.calcurse/caldav/config and adjust the configuration below.

[General]
# Path to the calcurse binary that is used for importing/exporting items.
Binary = calcurse

# Host name of the server that hosts CalDAV.
```
Are you sure that your file is uncorrupted and complete?

Whenever I chop off the top portion of the config file so that it starts with `# Path` I am able to reproduce your issue exactly:
```
host:~ $ calcurse-caldav 
Traceback (most recent call last):
  File "/usr/bin/calcurse-caldav", line 501, in <module>
    config.readfp(open(configfn))
  File "/usr/lib/python3.6/configparser.py", line 763, in readfp
    self.read_file(fp, source=filename)
  File "/usr/lib/python3.6/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib/python3.6/configparser.py", line 1080, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/home/username/.calcurse/caldav/config', line: 2
'Binary = calcurse\n'
```

**Comment by loweryaustin** [comment]
No problem! I'm glad you got it sorted out!
Have you thought about setting up a cronjob to run caldav-calcurse? I haven't really gotten to the point where I'm able to use it heavily yet, but I have a feeling that it is lightweight enough that you could set it to run once a minute, or every 5 minutes or so.

**Comment by lfos** [comment]
You can run calcurse-caldav from the pre-load hook. See [1] for an example hook.

[1] https://github.com/lfos/calcurse/blob/master/contrib/hooks/pre-load

**Comment by danieljamespost** [comment]
Both are great recommendations. This has been incredibly helpful. Thank you both again.
