### ISSUE TITLE
calcurse-caldav: Unicode error

### ISSUE THREAD

**Issue by misterunknown** [lfos/calcurse#13]
Hi,

I want to use calcurse-caldav for syncing my calendar with my companies exchange server. Therefore I set up [DavMail](http://davmail.sourceforge.net/). It seems to work basically, but unfortunately I get an unicode error while the script parses the response:

```
Traceback (most recent call last):
  File "/usr/local/bin/calcurse-caldav", line 519, in <module>
    local_new, local_del = pull_objects(conn, syncdb, etagdict)
  File "/usr/local/bin/calcurse-caldav", line 301, in pull_objects
    headers, body = remote_query(conn, "REPORT", path, {}, body)
  File "/usr/local/bin/calcurse-caldav", line 124, in remote_query
    print("< " + line)
  File "/usr/lib/python3.4/encodings/iso8859_15.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2022' in position 25: character maps to <undefined>
```

I looked around a bit in the script and noticed that it is basically unicode-aware (afaics^^), so do you have any hint for me?

Thanks in advance!

**Comment by misterunknown** [comment]
Well, I solved this particular issue, by disabling the debug mode^^ Apparently the script couldn't print the lines, neither to the screen, nor to the file. (I guess this issue is related to my locale, which is de_DE@euro [due to a company policy] while the server speaks UTF-8).

I disabled the debug mode and added explicit encoding in the save_syncdb function:
```
def save_syncdb(fn, syncdb):
  ...
    with open(fn, 'w', encoding='utf-8') as f:
      ...
```

So this works for me at the moment.

Cheers,
Marco

**Comment by lfos** [comment]
Yes, that error message is caused by your terminal which does not seem to support UTF-8. As a workaround, you can use something like `PYTHONIOENCODING=:replace calcurse-caldav` if you still want to see the debug output. Specifying UTF-8 explicitly when opening the file might be something that is interesting in general, though.
