### ISSUE TITLE
oauth2client.py throwing "The value of scope must not be None"

### ISSUE THREAD

**Issue by freed00m** [lfos/calcurse#132]
Hi,

I am attempting using calcurse-caldav, but I can't login via oauth2

liek this
```
~$ calcurse-caldav --init keep-remote --authcode '4/AAAFAKEiK7msdfEB4fKW9FKG3SAO2oasdln4OtARKH7NsLMdMIaPfdmlmIPI4usDKtqrDDZsw6k7nZ50-3eXqc#'
```

I am using config file at `~/.calcurse/caldav/config` 
```
[General]
Binary = calcurse
Hostname = apidata.googleusercontent.com
Path = /caldav/v2/Freed00mcz@gmail.com/events/
AuthMethod = oauth2
InsecureSSL = No
SyncFilter = cal,todo
DryRun = No
Verbose = Yes

#[OAuth2]
ClientID = 5FAKE7184363-c4a49v7p66d5e39g6sdfs7sv1g1a4sr.apps.googleusercontent.com
ClientSecret = uFAKEsfdtOht-lr072bGfFfU
Scope = https://www.googleapis.com/auth/calendar

RedirectURI = http://127.0.0.1
```

I've tried both oauth2client from pip and arch repository, both versions are having this issue. 

I managed to authorized the web API in their dashboard.

**Comment by freed00m** [comment]
@lionhead94 despite me disliking python2 I've started to use the AUR version of gcacli and they are building in for python2-oauth2client1412.

That works for me.. Hope the AUR maintainer build a working python 3 variant.

**Comment by lfos** [comment]
Are you sure it's not the fact that `#[OAuth2]` is commented out that causes the issue?

**Comment by lionhead94** [comment]
solved, thank you ;)

**Comment by freed00m** [comment]
Yeah, embarrassing :O 

Still can't the ncurse style configs. :D
