### ISSUE TITLE
`calcurse-caldav` config sample missing

### ISSUE THREAD

**Issue by jakobcornell** [lfos/calcurse#144]
The [`calcurse-caldav` documentation](https://www.calcurse.org/files/calcurse-caldav.html) claims that there's a sample configuration file at `/contrib/caldav/config.sample` in the source tree, but this file is missing in the current source, version 4.3.0. The file doesn't seemed to have been moved elsewhere in the tree either.

**Comment by lfos** [comment]
Pushed a fix to `pu`. Thanks for reporting!
