### ISSUE TITLE
End time of an item is skipped when adding an item and making an error when typing in the start date.

### ISSUE THREAD

**Issue by 991jo** [lfos/calcurse#154]
Hello

When I add an item and I send an invalid start time, e.g. 100 instead of 1000 calcurse says

`You entered an invalid start time, should be [hh:mm] or [hhmm]
Press [Enter] to continue`

When I press enter and fix the start time the next input field will be the description.

**Comment by lhca** [comment]
The bug is fixed in the master branch (https://github.com/lfos/calcurse/commit/40eb6f809eb22770543fe5ec6c0fc1fc1c9297df).
