### ISSUE TITLE
Bug while colour changing

### ISSUE THREAD

**Issue by KaRo2018** [lfos/calcurse#155]
Hi,
at first I really like your program.

While playing around in the config menu I ran into a problem:
If I try to select an other colour in the config menu I have an malfunction.
The error code I receive is "Speicherzugriffsfehler" which means segmentation fault.

P.S.: This is my first bug report and my first attempt on github, if I did something wrong please be tolerant.

Cheers 
Karsten

System information
![malfunction colour changing front ground calcurse](https://user-images.githubusercontent.com/44438740/47436715-53308880-d7a7-11e8-9499-0a0a3ced6ca3.png)
:
SysInfos 24.10.2018

OS:
Linux karo-HP-250-G6-Notebook-PC 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

HW:
karo-hp-250-g6-notebook-pc  
    Beschreibung: Computer
    Breite: 64 bits
    Fähigkeiten: smp vsyscall32
  *-core
       Beschreibung: Motherboard
       Physische ID: 0
     *-memory
          Beschreibung: Systemspeicher
          Physische ID: 0
          Größe: 7883MiB
     *-cpu
          Produkt: Intel(R) Pentium(R) CPU  N3710  @ 1.60GHz
          Hersteller: Intel Corp.
          Physische ID: 1
          Bus-Informationen: cpu@0
          Größe: 653MHz
          Kapazität: 2560MHz
          Breite: 64 bits
          Fähigkeiten: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp x86-64 constant_tsc arch_perfmon pebs bts rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 movbe popcnt tsc_deadline_timer aes rdrand lahf_lm 3dnowprefetch epb pti tpr_shadow vnmi flexpriority ept vpid tsc_adjust smep erms dtherm ida arat cpufreq
     *-pci
          Beschreibung: Host bridge
          Produkt: Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series SoC Transaction Register
          Hersteller: Intel Corporation
          Physische ID: 100
          Bus-Informationen: pci@0000:00:00.0
          Version: 35
          Breite: 32 bits
          Takt: 33MHz
          Konfiguration: driver=iosf_mbi_pci
          Ressourcen: irq:0
        *-display
             Beschreibung: VGA compatible controller
             Produkt: Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Integrated Graphics Controller
             Hersteller: Intel Corporation
             Physische ID: 2
             Bus-Informationen: pci@0000:00:02.0
             Version: 35
             Breite: 64 bits
             Takt: 33MHz
             Fähigkeiten: vga_controller bus_master cap_list rom
             Konfiguration: driver=i915 latency=0
             Ressourcen: irq:118 memory:90000000-90ffffff memory:80000000-8fffffff ioport:2000(Größe=64) memory:c0000-dffff
        *-generic:0
             Beschreibung: Signal processing controller
             Produkt: Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series Power Management Controller
             Hersteller: Intel Corporation
             Physische ID: b
             Bus-Informationen: pci@0000:00:0b.0
             Version: 35
             Breite: 64 bits
             Takt: 33MHz
             Fähigkeiten: bus_master cap_list
             Konfiguration: driver=proc_thermal latency=0
             Ressourcen: irq:120 memory:91414000-91414fff
        *-storage
             Beschreibung: SATA controller
             Produkt: Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series SATA Controller
             Hersteller: Intel Corporation
             Physische ID: 13
             Bus-Informationen: pci@0000:00:13.0
             Version: 35
             Breite: 32 bits
             Takt: 66MHz
             Fähigkeiten: storage ahci_1.0 bus_master cap_list
             Konfiguration: driver=ahci latency=0
             Ressourcen: irq:116 ioport:2060(Größe=32) memory:91415000-914157ff
        *-usb
             Beschreibung: USB controller
             Produkt: Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series USB xHCI Controller
             Hersteller: Intel Corporation
             Physische ID: 14
             Bus-Informationen: pci@0000:00:14.0
             Version: 35
             Breite: 64 bits
             Takt: 33MHz
             Fähigkeiten: xhci bus_master cap_list
             Konfiguration: driver=xhci_hcd latency=0
             Ressourcen: irq:115 memory:91400000-9140ffff
        *-generic:1
             Beschreibung: Encryption controller
             Produkt: Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series Trusted Execution Engine
             Hersteller: Intel Corporation
             Physische ID: 1a
             Bus-Informationen: pci@0000:00:1a.0
             Version: 35
             Breite: 32 bits
             Takt: 33MHz
             Fähigkeiten: bus_master cap_list
             Konfiguration: driver=mei_txe latency=0
             Ressourcen: irq:121 memory:91300000-913fffff memory:91200000-912fffff
        *-multimedia
             Beschreibung: Audio device
             Produkt: Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series High Definition Audio Controller
             Hersteller: Intel Corporation
             Physische ID: 1b
             Bus-Informationen: pci@0000:00:1b.0
             Version: 35
             Breite: 64 bits
             Takt: 33MHz
             Fähigkeiten: bus_master cap_list
             Konfiguration: driver=snd_hda_intel latency=0
             Ressourcen: irq:123 memory:91410000-91413fff
        *-pci:0
             Beschreibung: PCI bridge
             Produkt: Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCI Express Port #1
             Hersteller: Intel Corporation
             Physische ID: 1c
             Bus-Informationen: pci@0000:00:1c.0
             Version: 35
             Breite: 32 bits
             Takt: 33MHz
             Fähigkeiten: pci normal_decode bus_master cap_list
             Konfiguration: driver=pcieport
             Ressourcen: irq:0 ioport:3000(Größe=4096) memory:91500000-916fffff ioport:91700000(Größe=2097152)
        *-pci:1
             Beschreibung: PCI bridge
             Produkt: Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCI Express Port #3
             Hersteller: Intel Corporation
             Physische ID: 1c.2
             Bus-Informationen: pci@0000:00:1c.2
             Version: 35
             Breite: 32 bits
             Takt: 33MHz
             Fähigkeiten: pci normal_decode bus_master cap_list
             Konfiguration: driver=pcieport
             Ressourcen: irq:18 memory:91100000-911fffff
           *-network
                Beschreibung: Kabellose Verbindung
                Produkt: Intel Corporation
                Hersteller: Intel Corporation
                Physische ID: 0
                Bus-Informationen: pci@0000:02:00.0
                Logischer Name: wlo1
                Version: 10
                Seriennummer: 90:61:ae:fe:b1:c2
                Breite: 64 bits
                Takt: 33MHz
                Fähigkeiten: bus_master cap_list ethernet physical wireless
                Konfiguration: broadcast=yes driver=iwlwifi driverversion=4.15.0-38-generic firmware=29.1044073957.0 ip=192.168.178.44 latency=0 link=yes multicast=yes wireless=IEEE 802.11
                Ressourcen: irq:122 memory:91100000-91101fff
        *-pci:2
             Beschreibung: PCI bridge
             Produkt: Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCI Express Port #4
             Hersteller: Intel Corporation
             Physische ID: 1c.3
             Bus-Informationen: pci@0000:00:1c.3
             Version: 35
             Breite: 32 bits
             Takt: 33MHz
             Fähigkeiten: pci normal_decode bus_master cap_list
             Konfiguration: driver=pcieport
             Ressourcen: irq:19 ioport:1000(Größe=4096) memory:91000000-910fffff
           *-network
                Beschreibung: Ethernet interface
                Produkt: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
                Hersteller: Realtek Semiconductor Co., Ltd.
                Physische ID: 0
                Bus-Informationen: pci@0000:03:00.0
                Logischer Name: eno1
                Version: 15
                Seriennummer: 48:ba:4e:26:b0:36
                Größe: 10Mbit/s
                Kapazität: 1Gbit/s
                Breite: 64 bits
                Takt: 33MHz
                Fähigkeiten: bus_master cap_list ethernet physical tp mii 10bt 10bt-fd 100bt 100bt-fd 1000bt 1000bt-fd autonegotiation
                Konfiguration: autonegotiation=on broadcast=yes driver=r8169 driverversion=2.3LK-NAPI duplex=half firmware=rtl8168h-2_0.0.2 02/26/15 latency=0 link=no multicast=yes port=MII speed=10Mbit/s
                Ressourcen: irq:19 ioport:1000(Größe=256) memory:91004000-91004fff memory:91000000-91003fff
        *-isa
             Beschreibung: ISA bridge
             Produkt: Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCU
             Hersteller: Intel Corporation
             Physische ID: 1f
             Bus-Informationen: pci@0000:00:1f.0
             Version: 35
             Breite: 32 bits
             Takt: 33MHz
             Fähigkeiten: isa bus_master cap_list
             Konfiguration: driver=lpc_ich latency=0
             Ressourcen: irq:0
        *-serial UNGEFORDERT
             Beschreibung: SMBus
             Produkt: Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx SMBus Controller
             Hersteller: Intel Corporation
             Physische ID: 1f.3
             Bus-Informationen: pci@0000:00:1f.3
             Version: 35
             Breite: 32 bits
             Takt: 33MHz
             Fähigkeiten: cap_list
             Konfiguration: latency=0
             Ressourcen: memory:91416000-9141601f ioport:2040(Größe=32)
     *-scsi
          Physische ID: 2
          Logischer Name: scsi1
          Fähigkeiten: emulated
        *-cdrom
             Beschreibung: DVD writer
             Produkt: DVDRW  DA8AESH
             Hersteller: hp
             Physische ID: 0.0.0
             Bus-Informationen: scsi@1:0.0.0
             Logischer Name: /dev/cdrom
             Logischer Name: /dev/cdrw
             Logischer Name: /dev/dvd
             Logischer Name: /dev/dvdrw
             Logischer Name: /dev/sr0
             Version: XH6M
             Fähigkeiten: removable audio cd-r cd-rw dvd dvd-r
             Konfiguration: ansiversion=5 status=nodisc
WARNUNG: Ausgabe kann unvollständig oder fehlerhaft werden, Sie sollten dieses Programm mit Systemverwalterrechten (root) ausführen.
karo@karo-HP-250-G6-Notebook-PC ~ $ sudo lshw
[sudo] Passwort für karo: 
karo-hp-250-g6-notebook-pc  
    Beschreibung: Notebook
    Produkt: HP 250 G6 Notebook PC (2RR63EA#ABD)
    Hersteller: HP
    Version: Type1ProductConfigId
    Seriennummer: CND7346LZP
    Breite: 64 bits
    Fähigkeiten: smbios-3.0 dmi-3.0 smp vsyscall32
    Konfiguration: boot=normal chassis=notebook family=103C_5336AN HP 200 sku=2RR63EA#ABD uuid=F2E5287F-87AC-11E7-BE82-48BA4E26B036
  *-core
       Beschreibung: Hauptplatine
       Produkt: 832C
       Hersteller: HP
       Physische ID: 0
       Version: 25.30
       Seriennummer: PGNUTJ4NM92L61
       Steckplatz: Type2 - Board Chassis Location
     *-firmware
          Beschreibung: BIOS
          Hersteller: Insyde
          Physische ID: 0
          Version: F.21
          date: 07/07/2017
          Größe: 64KiB
          Kapazität: 3008KiB
          Fähigkeiten: pci upgrade shadowing cdboot bootselect edd int9keyboard int14serial int17printer int10video acpi usb zipboot biosbootspecification netboot uefi
     *-cpu
          Beschreibung: CPU
          Produkt: Intel(R) Pentium(R) CPU  N3710  @ 1.60GHz
          Hersteller: Intel Corp.
          Physische ID: 4
          Bus-Informationen: cpu@0
          Version: Intel(R) Pentium(R) CPU  N3710  @ 1.60GHz
          Seriennummer: To Be Filled By O.E.M.
          Steckplatz: CHV
          Größe: 1173MHz
          Kapazität: 2560MHz
          Breite: 64 bits
          Takt: 83MHz
          Fähigkeiten: x86-64 fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp constant_tsc arch_perfmon pebs bts rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 movbe popcnt tsc_deadline_timer aes rdrand lahf_lm 3dnowprefetch epb pti tpr_shadow vnmi flexpriority ept vpid tsc_adjust smep erms dtherm ida arat cpufreq
          Konfiguration: cores=4 enabledcores=4 threads=4
        *-cache:0
             Beschreibung: L1 Cache
             Physische ID: 6
             Steckplatz: L1 Cache
             Größe: 32KiB
             Kapazität: 32KiB
             Fähigkeiten: synchronous internal write-back instruction
             Konfiguration: level=1
        *-cache:1
             Beschreibung: L2 Cache
             Physische ID: 7
             Steckplatz: L2 Cache
             Größe: 1MiB
             Kapazität: 1MiB
             Fähigkeiten: synchronous internal write-back unified
             Konfiguration: level=2
     *-cache
          Beschreibung: L1 Cache
          Physische ID: 5
          Steckplatz: L1 Cache
          Größe: 24KiB
          Kapazität: 24KiB
          Fähigkeiten: synchronous internal write-back data
          Konfiguration: level=1
     *-memory
          Beschreibung: Systemspeicher
          Physische ID: 25
          Steckplatz: Systemplatine oder Hauptplatine
          Größe: 8GiB
        *-bank:0
             Beschreibung: SODIMM DDR3 Synchron 1600 MHz (0,6 ns)
             Produkt: HMT41GS6DFR8A-PB
             Hersteller: Hynix
             Physische ID: 0
             Seriennummer: 02121214
             Steckplatz: Bottom-slot 1(left)
             Größe: 8GiB
             Breite: 8 bits
             Takt: 1600MHz (0.6ns)
        *-bank:1
             Beschreibung: SODIMM DDR Synchron [leer]
             Physische ID: 1
             Steckplatz: Bottom-slot 2(right)
     *-pci
          Beschreibung: Host bridge
          Produkt: Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series SoC Transaction Register
          Hersteller: Intel Corporation
          Physische ID: 100
          Bus-Informationen: pci@0000:00:00.0
          Version: 35
          Breite: 32 bits
          Takt: 33MHz
          Konfiguration: driver=iosf_mbi_pci
          Ressourcen: irq:0
        *-display
             Beschreibung: VGA compatible controller
             Produkt: Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Integrated Graphics Controller
             Hersteller: Intel Corporation
             Physische ID: 2
             Bus-Informationen: pci@0000:00:02.0
             Version: 35
             Breite: 64 bits
             Takt: 33MHz
             Fähigkeiten: pm msi vga_controller bus_master cap_list rom
             Konfiguration: driver=i915 latency=0
             Ressourcen: irq:118 memory:90000000-90ffffff memory:80000000-8fffffff ioport:2000(Größe=64) memory:c0000-dffff
        *-generic:0
             Beschreibung: Signal processing controller
             Produkt: Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series Power Management Controller
             Hersteller: Intel Corporation
             Physische ID: b
             Bus-Informationen: pci@0000:00:0b.0
             Version: 35
             Breite: 64 bits
             Takt: 33MHz
             Fähigkeiten: msi pm bus_master cap_list
             Konfiguration: driver=proc_thermal latency=0
             Ressourcen: irq:120 memory:91414000-91414fff
        *-storage
             Beschreibung: SATA controller
             Produkt: Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series SATA Controller
             Hersteller: Intel Corporation
             Physische ID: 13
             Bus-Informationen: pci@0000:00:13.0
             Version: 35
             Breite: 32 bits
             Takt: 66MHz
             Fähigkeiten: storage msi pm ahci_1.0 bus_master cap_list
             Konfiguration: driver=ahci latency=0
             Ressourcen: irq:116 ioport:2060(Größe=32) memory:91415000-914157ff
        *-usb
             Beschreibung: USB controller
             Produkt: Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series USB xHCI Controller
             Hersteller: Intel Corporation
             Physische ID: 14
             Bus-Informationen: pci@0000:00:14.0
             Version: 35
             Breite: 64 bits
             Takt: 33MHz
             Fähigkeiten: pm msi xhci bus_master cap_list
             Konfiguration: driver=xhci_hcd latency=0
             Ressourcen: irq:115 memory:91400000-9140ffff
           *-usbhost:0
                Produkt: xHCI Host Controller
                Hersteller: Linux 4.15.0-38-generic xhci-hcd
                Physische ID: 0
                Bus-Informationen: usb@1
                Logischer Name: usb1
                Version: 4.15
                Fähigkeiten: usb-2.00
                Konfiguration: driver=hub slots=7 speed=480Mbit/s
              *-usb
                   Beschreibung: USB-Hub
                   Produkt: USB2.0 Hub
                   Hersteller: Genesys Logic, Inc.
                   Physische ID: 5
                   Bus-Informationen: usb@1:5
                   Version: 88.32
                   Fähigkeiten: usb-2.00
                   Konfiguration: driver=hub maxpower=100mA slots=4 speed=480Mbit/s
                 *-usb:0
                      Beschreibung: Video
                      Produkt: HP TrueVision HD Camera
                      Hersteller: DGENB019I88LMF
                      Physische ID: 2
                      Bus-Informationen: usb@1:5.2
                      Version: 0.05
                      Fähigkeiten: usb-2.00
                      Konfiguration: driver=uvcvideo maxpower=500mA speed=480Mbit/s
                 *-usb:1
                      Beschreibung: Bluetooth-Schnittstelle
                      Hersteller: Intel Corp.
                      Physische ID: 3
                      Bus-Informationen: usb@1:5.3
                      Version: 0.01
                      Fähigkeiten: bluetooth usb-2.00
                      Konfiguration: driver=btusb maxpower=100mA speed=12Mbit/s
           *-usbhost:1
                Produkt: xHCI Host Controller
                Hersteller: Linux 4.15.0-38-generic xhci-hcd
                Physische ID: 1
                Bus-Informationen: usb@2
                Logischer Name: usb2
                Version: 4.15
                Fähigkeiten: usb-3.00
                Konfiguration: driver=hub slots=6 speed=5000Mbit/s
        *-generic:1
             Beschreibung: Encryption controller
             Produkt: Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series Trusted Execution Engine
             Hersteller: Intel Corporation
             Physische ID: 1a
             Bus-Informationen: pci@0000:00:1a.0
             Version: 35
             Breite: 32 bits
             Takt: 33MHz
             Fähigkeiten: pm msi bus_master cap_list
             Konfiguration: driver=mei_txe latency=0
             Ressourcen: irq:121 memory:91300000-913fffff memory:91200000-912fffff
        *-multimedia
             Beschreibung: Audio device
             Produkt: Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series High Definition Audio Controller
             Hersteller: Intel Corporation
             Physische ID: 1b
             Bus-Informationen: pci@0000:00:1b.0
             Version: 35
             Breite: 64 bits
             Takt: 33MHz
             Fähigkeiten: pm msi bus_master cap_list
             Konfiguration: driver=snd_hda_intel latency=0
             Ressourcen: irq:123 memory:91410000-91413fff
        *-pci:0
             Beschreibung: PCI bridge
             Produkt: Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCI Express Port #1
             Hersteller: Intel Corporation
             Physische ID: 1c
             Bus-Informationen: pci@0000:00:1c.0
             Version: 35
             Breite: 32 bits
             Takt: 33MHz
             Fähigkeiten: pci pciexpress msi pm normal_decode bus_master cap_list
             Konfiguration: driver=pcieport
             Ressourcen: irq:0 ioport:3000(Größe=4096) memory:91500000-916fffff ioport:91700000(Größe=2097152)
        *-pci:1
             Beschreibung: PCI bridge
             Produkt: Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCI Express Port #3
             Hersteller: Intel Corporation
             Physische ID: 1c.2
             Bus-Informationen: pci@0000:00:1c.2
             Version: 35
             Breite: 32 bits
             Takt: 33MHz
             Fähigkeiten: pci pciexpress msi pm normal_decode bus_master cap_list
             Konfiguration: driver=pcieport
             Ressourcen: irq:18 memory:91100000-911fffff
           *-network
                Beschreibung: Kabellose Verbindung
                Produkt: Intel Corporation
                Hersteller: Intel Corporation
                Physische ID: 0
                Bus-Informationen: pci@0000:02:00.0
                Logischer Name: wlo1
                Version: 10
                Seriennummer: 90:61:ae:fe:b1:c2
                Breite: 64 bits
                Takt: 33MHz
                Fähigkeiten: pm msi pciexpress bus_master cap_list ethernet physical wireless
                Konfiguration: broadcast=yes driver=iwlwifi driverversion=4.15.0-38-generic firmware=29.1044073957.0 ip=192.168.178.44 latency=0 link=yes multicast=yes wireless=IEEE 802.11
                Ressourcen: irq:122 memory:91100000-91101fff
        *-pci:2
             Beschreibung: PCI bridge
             Produkt: Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCI Express Port #4
             Hersteller: Intel Corporation
             Physische ID: 1c.3
             Bus-Informationen: pci@0000:00:1c.3
             Version: 35
             Breite: 32 bits
             Takt: 33MHz
             Fähigkeiten: pci pciexpress msi pm normal_decode bus_master cap_list
             Konfiguration: driver=pcieport
             Ressourcen: irq:19 ioport:1000(Größe=4096) memory:91000000-910fffff
           *-network
                Beschreibung: Ethernet interface
                Produkt: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
                Hersteller: Realtek Semiconductor Co., Ltd.
                Physische ID: 0
                Bus-Informationen: pci@0000:03:00.0
                Logischer Name: eno1
                Version: 15
                Seriennummer: 48:ba:4e:26:b0:36
                Größe: 10Mbit/s
                Kapazität: 1Gbit/s
                Breite: 64 bits
                Takt: 33MHz
                Fähigkeiten: pm msi pciexpress msix bus_master cap_list ethernet physical tp mii 10bt 10bt-fd 100bt 100bt-fd 1000bt 1000bt-fd autonegotiation
                Konfiguration: autonegotiation=on broadcast=yes driver=r8169 driverversion=2.3LK-NAPI duplex=half firmware=rtl8168h-2_0.0.2 02/26/15 latency=0 link=no multicast=yes port=MII speed=10Mbit/s
                Ressourcen: irq:19 ioport:1000(Größe=256) memory:91004000-91004fff memory:91000000-91003fff
        *-isa
             Beschreibung: ISA bridge
             Produkt: Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCU
             Hersteller: Intel Corporation
             Physische ID: 1f
             Bus-Informationen: pci@0000:00:1f.0
             Version: 35
             Breite: 32 bits
             Takt: 33MHz
             Fähigkeiten: isa bus_master cap_list
             Konfiguration: driver=lpc_ich latency=0
             Ressourcen: irq:0
        *-serial UNGEFORDERT
             Beschreibung: SMBus
             Produkt: Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx SMBus Controller
             Hersteller: Intel Corporation
             Physische ID: 1f.3
             Bus-Informationen: pci@0000:00:1f.3
             Version: 35
             Breite: 32 bits
             Takt: 33MHz
             Fähigkeiten: pm cap_list
             Konfiguration: latency=0
             Ressourcen: memory:91416000-9141601f ioport:2040(Größe=32)
     *-scsi:0
          Physische ID: 1
          Logischer Name: scsi0
          Fähigkeiten: emulated
        *-disk
             Beschreibung: ATA Disk
             Produkt: SAMSUNG MZNLN256
             Physische ID: 0.0.0
             Bus-Informationen: scsi@0:0.0.0
             Logischer Name: /dev/sda
             Version: 1H3Q
             Seriennummer: S2Y2NX0J413306
             Größe: 238GiB (256GB)
             Fähigkeiten: partitioned partitioned:dos
             Konfiguration: ansiversion=5 logicalsectorsize=512 sectorsize=4096 signature=7ebf80cd
           *-volume:0
                Beschreibung: Windows FAT Laufwerk
                Hersteller: FRDOS4.1
                Physische ID: 1
                Bus-Informationen: scsi@0:0.0.0,1
                Logischer Name: /dev/sda1
                Version: FAT32
                Seriennummer: 4ee5-543a
                Größe: 8186MiB
                Kapazität: 8GiB
                Fähigkeiten: primary fat initialized
                Konfiguration: FATs=2 filesystem=fat label=HPDOCS
           *-volume:1
                Beschreibung: Windows FAT Laufwerk
                Hersteller: SYSLINUX
                Physische ID: 2
                Bus-Informationen: scsi@0:0.0.0,2
                Logischer Name: /dev/sda2
                Version: FAT32
                Seriennummer: f0e5-b624
                Größe: 8186MiB
                Kapazität: 8GiB
                Fähigkeiten: primary bootable fat initialized
                Konfiguration: FATs=2 filesystem=fat label=BUILDPART
           *-volume:2
                Beschreibung: Extended partition
                Physische ID: 3
                Bus-Informationen: scsi@0:0.0.0,3
                Logischer Name: /dev/sda3
                Größe: 222GiB
                Kapazität: 222GiB
                Fähigkeiten: primary extended partitioned partitioned:extended
              *-logicalvolume:0
                   Beschreibung: EXT4-Laufwerk
                   Hersteller: Linux
                   Physische ID: 5
                   Logischer Name: /dev/sda5
                   Logischer Name: /
                   Version: 1.0
                   Seriennummer: e26936bc-9140-43f6-aff8-6f991ecc4ac1
                   Größe: 214GiB
                   Kapazität: 214GiB
                   Fähigkeiten: journaled extended_attributes large_files huge_files dir_nlink recover extents ext4 ext2 initialized
                   Konfiguration: created=2018-04-10 17:54:24 filesystem=ext4 lastmountpoint=/ modified=2018-10-24 15:49:16 mount.fstype=ext4 mount.options=rw,noatime,errors=remount-ro,data=ordered mounted=2018-10-24 15:49:16 state=mounted
              *-logicalvolume:1
                   Beschreibung: Linux swap Laufwerk
                   Physische ID: 6
                   Logischer Name: /dev/sda6
                   Version: 1
                   Seriennummer: 3f9918ed-689b-41b7-a80e-9b5b4056b2d6
                   Größe: 8097MiB
                   Kapazität: 8097MiB
                   Fähigkeiten: nofs swap initialized
                   Konfiguration: filesystem=swap pagesize=4096
     *-scsi:1
          Physische ID: 2
          Logischer Name: scsi1
          Fähigkeiten: emulated
        *-cdrom
             Beschreibung: DVD writer
             Produkt: DVDRW  DA8AESH
             Hersteller: hp
             Physische ID: 0.0.0
             Bus-Informationen: scsi@1:0.0.0
             Logischer Name: /dev/cdrom
             Logischer Name: /dev/cdrw
             Logischer Name: /dev/dvd
             Logischer Name: /dev/dvdrw
             Logischer Name: /dev/sr0
             Version: XH6M
             Fähigkeiten: removable audio cd-r cd-rw dvd dvd-r
             Konfiguration: ansiversion=5 status=nodisc
  *-battery
       Produkt: JC04041
       Hersteller: 133-42-6E
       Physische ID: 1
       Version: 0
       Seriennummer: 0
       Steckplatz: Primary
       Kapazität: 41610mWh
       Konfiguration: voltage=14,6V
  *-power UNGEFORDERT
       Beschreibung: OEM Define 1
       Produkt: OEM Define 5
       Hersteller: OEM Define 2
       Physische ID: 2
       Version: OEM Define 6
       Seriennummer: OEM Define 3
       Kapazität: 75mWh

**Comment by lfos** [comment]
Which version are you using? This should be fixed in both master and the latest release.

**Comment by KaRo2018** [comment]
Hi,
you are right, I have an old version (4.2.1) which was downloaded by apt install in Linux Mint 19.
I will remove it and take the actual version from your website.
Thank you.
Cheers Karsten
