### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by lhca** [lfos/calcurse#156]
I am looking into the calcurse documentation, specifically the man-page.

Any complaints, issues, wishes - even praises - are much appreciated.

**Comment by lhca** [comment]
Command line mode has an option `-F` or `--filter` and also a lot of "filter-options" like `--filter-type`. The "filter-options" are used to restrict the output from other options, among them `-F`.

The "filter" name is confusing and not well chosen in my opinion. The option must be used with care and should not be confused with the "filter-options".

I suggest that it be renamed to `-P` or `--purge`.

**Comment by lhca** [comment]
Many options take a date as argument. The date may be entered as

- year/month/day
- month/day/year
- year-month-day

but not as day/month/year (my own preference). The formats are tried in sequence as listed, which has the unfortunate consequence that if you enter 4 November 2018 as 4/11/2018, it is interpreted as 11 April 2018. This, of course, is a bug that should be fixed, but how?

The simplest solution is to add day/month/year to the list and change the sequence to

- year-month-day (ISO format)
- year/month/day
- day/month/year
- month/day/year (North American format)

That will leave the ambiguity day/month <-> month/day and in effect make the last format unusable (that would serve them right :-).

Another possibility is to accept the ISO format only:

- year-month-day

which is not very flexible and may break existing scripts.

A third possibility, which is the best way, but requires a greater implementation effort, is to handle the input format as the output format: take it from the user configuration. This will make it less easy to switch between input formats, but my guess is that everybody uses just one.

What do you think?

**Comment by lhca** [comment]
In queries you may specify a range of days (`-Q` in combination with `--from`, `--to` or `--days`).

 The _from_ day, but not the _to_ day, is included in the range. Bug or feature?

**Comment by lfos** [comment]
> I suggest that it be renamed to `-P` or `--purge`.

Well, it's not that easy. The `-F` option has been part of an official release and might be used in scripts already. We can rename it but we'll have to keep the old options as well (and mark them as deprecated).

> A third possibility, which is the best way, but requires a greater implementation effort, is to handle the input format as the output format: take it from the user configuration. This will make it less easy to switch between input formats, but my guess is that everybody uses just one.

This is not a good idea. The scriptable part of the CLI should not depend on user configuration. You want to be able to write a script and make sure it behaves the same, even on another system. Accepting only ISO sounds fine but again, we'd have to ensure backwards compatibility in some way.

> The _from_ day, but not the _to_ day, is included in the range. Bug or feature?

I think it is a feature but it should definitely be documented.

**Comment by lhca** [comment]
I understand your concerns about backward compatibility, but I don't think it should take precedence in all cases. If it can be achieved at no great cost, by all means. But this is not commercial software. The effort in maintaining the software should be taken into account.  If inconvenient or confusing behaviour keep new users from adopting calcurse, it may be worth the risk of offending old ones when improvements break existing behaviour. As long as it is documented, of course. It should not stand in the way of improvement and clarity at all costs.

 > > I suggest that it be renamed to `-P` or `--purge`.
> 
> Well, it's not that easy. The `-F` option has been part of an official release and might be used in scripts already. We can rename it but we'll have to keep the old options as well (and mark them as deprecated).

This one is easy. Keep both.
 
> > A third possibility, which is the best way, but requires a greater implementation effort, is to handle the input format as the output format: take it from the user configuration. This will make it less easy to switch between input formats, but my guess is that everybody uses just one.
 
> This is not a good idea. The scriptable part of the CLI should not depend on user configuration.
> You want to be able to write a script and make sure it behaves the same, even on another system.

It does already. The date format in the lines separating query output results is taken from the user configuration. It is confusing that this part of the output cannot be changed from the command line. (That, of course, is an argument for making that independent of the configuration as well.) 

But it is also annoying that I cannot use my preferred format (`dd/mm/yyyy`) on the command line. As I already said, I consider it a bug.

> > The _from_ day, but not the _to_ day, is included in the range. Bug or feature?
 
> I think it is a feature but it should definitely be documented.

I think it as a bug for several reasons.
- It is confusing.
- It disagrees with the semantics of _to_ in filter options like `--filter-start-to`, where _to_ (and _from_) are used in the inclusive sense (as opposed to _before_ and _after_).
- It has the effect that `--from today --to tomorrow` has a range of 1 day, `--to today` a range of 0 days (otherwise not allowed), and `--to today --days -1` is allowed and displays yesterday, although `--to today --days 1` is rejected with the message _cannot specify a range and an end date_!
- Documenting this behaviour is (hmm) tedious.

The negative range is in b82a3b9 on master and needs fixing before release or else there will be further backward compatibility problems.

In my opinion, the `--to` semantics should be changed to agree with the filter options, `--to` with `--days` should be disallowed in all cases, and `--from` with a negative range should mean _from today and so-many-days in the past_.

**Comment by lfos** [comment]
> I understand your concerns about backward compatibility, but I don't think it should take precedence in all cases. If it can be achieved at no great cost, by all means. But this is not commercial software. The effort in maintaining the software should be taken into account. If inconvenient or confusing behaviour keep new users from adopting calcurse, it may be worth the risk of offending old ones when improvements break existing behaviour. As long as it is documented, of course. It should not stand in the way of improvement and clarity at all costs.

I generally agree. If there's a change that is impossible (or extremely hard) to make backwards compatbile, I am all for breaking backwards compatibility and making a major release to indicate the change. But it's usually rather easy to achieve backwards compatibility, even though it often requires some extra tought.

> > This is not a good idea. The scriptable part of the CLI should not depend on user configuration.
> > You want to be able to write a script and make sure it behaves the same, even on another system.
> 
> It does already. The date format in the lines separating query output results is taken from the user configuration. It is confusing that this part of the output cannot be changed from the command line. (That, of course, is an argument for making that independent of the configuration as well.)
> 
> But it is also annoying that I cannot use my preferred format (`dd/mm/yyyy`) on the command line. As I already said, I consider it a bug.

I usually think of the CLI as being the scriptable part of calcurse and the ncurses part being the user interface but I also realize other users might be thinking differently. We should definitely keep independence of the personal settings in some way, though. What we could do is add an option to set the input format, and another option to load the input format from the config file. But even then, it might be too inconvenient to specify that option whenever running calcurse. You could create a shell alias, of course. Or maybe, we should split the CLI into a user-facing part and a scriptable part?

> 
> > > The _from_ day, but not the _to_ day, is included in the range. Bug or feature?
> 
> > I think it is a feature but it should definitely be documented.
> 
> I think it as a bug for several reasons.
> 
> * It is confusing.
> * It disagrees with the semantics of _to_ in filter options like `--filter-start-to`, where _to_ (and _from_) are used in the inclusive sense (as opposed to _before_ and _after_).
> * It has the effect that `--from today --to tomorrow` has a range of 1 day, `--to today` a range of 0 days (otherwise not allowed), and `--to today --days -1` is allowed and displays yesterday, although `--to today --days 1` is rejected with the message _cannot specify a range and an end date_!
> * Documenting this behaviour is (hmm) tedious.

Agreed.

> 
> The negative range is in [b82a3b9](https://github.com/lfos/calcurse/commit/b82a3b9276bd32c5a4f13fcf9661a7a65b3505aa) on master and needs fixing before release or else there will be further backward compatibility problems.
> 
> In my opinion, the `--to` semantics should be changed to agree with the filter options, `--to` with `--days` should be disallowed in all cases, and `--from` with a negative range should mean _from today and so-many-days in the past_.

Sounds sensible. Thanks!

**Comment by lhca** [comment]
> I usually think of the CLI as being the scriptable part of calcurse and the ncurses part being the user interface but I also realize other users might be thinking differently. We should definitely keep independence of the personal settings in some way, though. What we could do is add an option to set the input format, and another option to load the input format from the config file. But even then, it might be too inconvenient to specify that option whenever running calcurse.

I think the CLI is used in both ways: as a script interface and as a UI. Searches in the data files, for instance, are only possible from the CLI.

You have a point in that scripts should be independent of the user configuration. But it should also be possible to use a prefered input date format when calcurse is used interactively, whether in ncurses or command line mode .

Both could be accomplished if calcurse takes the input format from the user configuration by default and has a long option `--input-datefmt` which overrides `conf.input_datefmt`. For the output date format a long option `--output-datefmt` could similarly override `conf.output_datefmt`.

**Comment by lhca** [comment]
Pull request opened, issue closed.
