### ISSUE TITLE
random selection of appointment

### ISSUE THREAD

**Issue by mvhulten** [lfos/calcurse#16]
After changing and saving an appointment, a different appointment is highlighted, seemingly randomly.

Version: calcurse 4.1.0

To reproduce:
- select some empty day in your appointments
- add two or three appointments
- edit an appointment (e.g. description)

The result is that it jumps to another item.  Which one I cannot predict.

I remember that with some previous version this did not happen: the same appointment was still highlighted/selected after changing it.

**Comment by lfos** [comment]
Fixed by ab9256a.
