### ISSUE TITLE
calcurse-caldav --init does not complete

### ISSUE THREAD

**Issue by crashwny** [lfos/calcurse#165]
` File "calcurse-caldav", line 289
    print("{} {} {}".format(href, etag, objhash), file=f)
                                                      ^
SyntaxError: invalid syntax
`
I attempted to fix with several minor syntax changes without success

**Comment by lfos** [comment]
You are not trying to run the script with Python 2 by any chance?

**Comment by crashwny** [comment]
yeah, I guess I was!, boy do I feel dumb
