### ISSUE TITLE
[Feature Request] Repeated Events

### ISSUE THREAD

**Issue by lukerb52** [lfos/calcurse#166]
Repeated events for things like weekly classes. Events should be able to repeat weekly, daily, every weekday, etc. Here's a proposed format for the description:

Original Title (🔁) Additional Notes

- the Original Title and the (🔁) must remain the same for the event to be classified as a clone, and anything after will be specific notes for that clone
- Clones should be able to be modified through the original after the matter.

**Comment by lfos** [comment]
You can create repeated events by selecting an existing event/appointment and using the "Repeat" (`r`) key binding.

This is described in our FAQ [1] and in the key bindings bar within calcurse.

If you have any suggestions on how to improve the visibility of this feature (Where did you look for it? Which resources did you consult? Where would you have expected to find this documented?), please let us know!

[1] https://calcurse.org/support/
