### ISSUE TITLE
Calendar going to the next week while being in the todo tab

### ISSUE THREAD

**Issue by pearupung** [lfos/calcurse#168]

**Comment by lfos** [comment]
This happens when pressing the enter key. Also happens from the appointments panel because enter is bound to "generic next week" by default. Not sure whether we should consider that a bug or expected behavior.

**Comment by pearupung** [comment]
I hadn't had much experience with the app when I wrote this, as time has passed, having the `W`, `w`, `T`, `t` etc. keys tied to the calendar view at all times is a menacingly good idea when some insight into appointments is needed when making a todo. I did not expect the return key to move a week forward the first time I used it. Since this is the default behaviour, I am not considering this a bug no more.

It is up to debate if this is the most wanted default behaviour though. :D 
My personal preference is viewing a note attached to an event with a return character than the "lesser-than" sign which isn't as handy on an Estonian keyboard to type, nor as intuitive. :) Even though the return key's default function duplicates the `w` key's action, the decision of what-should-it-do is not purely mine to make. I hope this thread has others giving in to the discussion of UX as well.

**Comment by lhca** [comment]
I have `RETURN` (= `^J`) mapped to view-item (which is a noop in the calendar). A second `RETURN` then closes the view.

The default generic-next-week is more confusing than helpful.

**Comment by lfos** [comment]
Should we just change the default mapping then?

**Comment by lhca** [comment]
That would help newcomers and harm no one.
