### ISSUE TITLE
Google calendar caldav support

### ISSUE THREAD

**Issue by iliavolyova** [lfos/calcurse#17]
Hello. 

I'm trying to get calcurse to two-way sync with google's caldav server. I found a [thread](http://lists.calcurse.org/misc/msg00786.html) on your misc mailing list where a user made it work by using a [deprecated endpoint](https://www.google.com/calendar/dav). The link looks live, but I get 

```
Connecting to www.google.com...
error: The server at www.google.com replied with HTTP status code 405 (Method
error: Not Allowed) while trying to access /calendar/dav/.
```

My `~/.calcurse/caldav/config` is as follows:
```
  1 #If you want to synchronize calcurse with a CalDAV server using                                                                 
  2 # calcurse-caldav, create a new directory ~/.calcurse/caldav/, copy this file
  3 # to ~/.calcurse/caldav/config and adjust the configuration below.
  4 
  5 [General]
  6 # Path to the calcurse binary that is used for importing/exporting items.
  7 Binary = calcurse
  8 
  9 # Host name of the server that hosts CalDAV.
 10 Hostname = www.google.com
 11 
 12 # Path to the CalDAV calendar on the host specified above.
 13 Path = /calendar/dav
 14 
 15 # Enable this if you want to skip SSL certificate checks.
 16 InsecureSSL = No
 17 
 18 # Disable this option to actually enable synchronization. If it is enabled,
 19 # nothing is actually written to the server or to the local data files. If you
 20 # combine DryRun = Yes with Verbose = Yes, you get a log of what would have
 21 # happened with this option disabled.
 22 DryRun = Yes
 23 
 24 # Enable this if you want detailed logs written to stdout.
 25 Verbose = Yes
 26 
 27 # Credentials for HTTP Basic Authentication. Leave this commented out if you do
 28 # not want to use authentication.
 29 [Auth]
 30 Username = [redacted]@gmail.com
 31 Password = [redacted]
```

I've generated a fresh Google app-password for calcurse and am using it in the above config.

Thanks in advance, and keep up the good work!

**Comment by Neo-Oli** [comment]
According to [this](https://blog.mozilla.org/calendar/2013/09/google-is-changing-the-location-url-of-their-caldav-calendars/) that api endpoint was moved. So it should be
```
Hostname = apidata.googleusercontent.com
Path = /caldav/v2/[redacted]@gmail.com/events/
```

Unfortunately seems to use a different kind of authentication and not HTTP Basic Auth. 

```
error: The server at apidata.googleusercontent.com replied with HTTP status code
error: 401 (Unauthorized) while trying to access
error: /caldav/v2/[redacted]/events/.
```

**Comment by hughwilliams94** [comment]
I second an OAuth implementation

**Comment by Erulisse** [comment]
+1

**Comment by emk2203** [comment]
+1 for OAuth. Ran into the same roadblock just now.

**Comment by watersalesman** [comment]
I submitted a PR (#28) for this, for those who are interested. I added a script for OAuth2 servers and appended the appropriate options in the sample config file. Feedback is very much welcome.

**Comment by lfos** [comment]
Patches for OAuth2 support are currently sitting in the `pu` branch and will be merged soon. Closing this for now, feel free to reopen if there are any issues.

@watersalesman: Thanks a lot for working on this!
