### ISSUE TITLE
[Request] Add custom directory support to calcurse-caldav

### ISSUE THREAD

**Issue by vxid** [lfos/calcurse#187]
This is probably not really high priority but it would be nice to add a data directory flag to calcurse-caldav to complement the -D flag in calcurse to indicate which directory events should be saved in.
If i'm not mistaken, calcurse-caldav currently hardcode `~/.calcurse` as the storage path which causes synchronization to fail if events are in a different directory.

**Comment by lfos** [comment]
Huh? Using `-D`, you should be able to change the directory that events are saved in...

**Comment by vxid** [comment]
I do not think I exposed my problem clearly.

I currently use a different directory, `$HOME/usr/cal`, to store calendar objects.

Using `calcurse -D $HOME/usr/cal -C $HOME/usr/cal` allows me to use data files from this directory as expected (the config files also are in the same directory, hence the `-C` flag).

However, syncing using ```calcurse-caldav --config $HOME/usr/cal/caldav/config --lockfile $HOME/usr/cal/caldav/lock --syncdb $HOME/usr/cal/caldav/sync.db``` still saves remote events to `$HOME/.calcurse` and assumes local events are also present in this directory.

I'm started working on a PR to add the -D flag as a config option to the `calcurse-caldav` script, it seems like it wouldn't take much effort to pass this new -D option to subprocess calls from within the script.

**Comment by lfos** [comment]
Do you still plan on working on this for `calcurse-caldav` as well? Sounds like a good idea to me.

**Comment by vxid** [comment]
Yes, I will open a PR once calcurse-vdirsyncer is merged.
