### ISSUE TITLE
No rule to make target 'calcurse.1', needed by 'all-am

### ISSUE THREAD

**Issue by strk** [lfos/calcurse#194]
v4.4.0-3-g5283689

Making all in doc
make[2]: Entering directory '/usr/src/calcurse/doc'
make[2]: *** No rule to make target 'calcurse.1', needed by 'all-am'.  Stop.
make[2]: Leaving directory '/usr/src/calcurse/doc'
Makefile:388: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/src/calcurse'
Makefile:329: recipe for target 'all' failed

**Comment by vxid** [comment]
You need asciidoc installed.
There is no warning if you do not have it though, I wonder if the Makefile could make this more obvious.

**Comment by strk** [comment]
I'm sure Makefile could be crafted to give you such warning, yes.
It could even be done by ./configure (maybe better)

**Comment by vxid** [comment]
Apparently `./configure` already issues a warning. 

https://github.com/lfos/calcurse/blob/528368932ceb05fec10638062ca56d6772f21040/configure.ac#L90-L97

**Comment by strk** [comment]
> Apparently `./configure` already issues a warning. 

That's good, but then it shouldn't break build (ie: should disable
building or installing the manual). If it breaks the build,
./configure should error out, not just warn.
