### ISSUE TITLE
I can't get notifications to work!

### ISSUE THREAD

**Issue by fmv1992** [lfos/calcurse#204]
I can't get notifications to work.

With the following configuration:

```
appearance.calendarview=monthly
appearance.compactpanels=no
appearance.defaultpanel=calendar
appearance.layout=5
appearance.notifybar=yes
appearance.sidebarwidth=3
appearance.theme=red on default
daemon.enable=yes
daemon.log=yes
format.inputdate=4
format.notifydate=%a %F
format.notifytime=%T
format.outputdate=%F
general.autogc=yes
general.autosave=yes
general.confirmdelete=yes
general.confirmquit=no
general.firstdayofweek=sunday
general.periodicsave=3
general.systemdialogs=yes
notification.command=calcurse --next | xargs -0 notify-send "Appointment"
notification.notifyall=all
notification.warning=1
appearance.todoview=show-completed
appearance.headingpos=right-justified
format.dayheading=%B %-d, %Y
general.systemevents=yes
```

I have also tried:

```
notification.command=touch /tmp/this_calcurse_command
```

Etc.

None of them worked. I have the calcurse daemon running:

```
started at Fri Mar 29 14:40:02 2019
sleeping at Fri Mar 29 14:40:02 2019 for 60 seconds
terminated at Fri Mar 29 14:40:04 2019 with signal 2
started at Fri Mar 29 14:40:18 2019
sleeping at Fri Mar 29 14:40:18 2019 for 60 seconds
terminated at Fri Mar 29 14:40:19 2019 with signal 2
started at Fri Mar 29 14:40:53 2019
sleeping at Fri Mar 29 14:40:53 2019 for 60 seconds
terminated at Fri Mar 29 14:40:55 2019 with signal 2
started at Fri Mar 29 14:47:16 2019
sleeping at Fri Mar 29 14:47:16 2019 for 60 seconds
terminated at Fri Mar 29 14:47:24 2019 with signal 2
started at Fri Mar 29 14:48:10 2019
sleeping at Fri Mar 29 14:48:10 2019 for 60 seconds
terminated at Fri Mar 29 14:48:12 2019 with signal 2
started at Fri Mar 29 14:51:45 2019
sleeping at Fri Mar 29 14:51:45 2019 for 60 seconds
```

Etc.

* * *

Event in question:

```
03/29/2019 @ 14:50 -> 03/29/2019 @ 14:55|test
```

I tried various different times (starting from 5 minutes ahead of time to give time for the daemon to update

Version:

```
# calcurse --version
calcurse 4.4.0-9-gd261 -- text-based organizer

Copyright (c) 2004-2017 calcurse Development Team.
This is free software; see the source for copying conditions.
```

Thanks :)

**Comment by lhca** [comment]
There are two issues. Let's leave out the notification daemon for a moment.

> I can't get notifications to work.
> 
> With the following configuration:
> 
> notification.command=calcurse --next | xargs -0 notify-send "Appointment"
> notification.notifyall=all
> notification.warning=1

Your setup means that the notification should be triggered one second before the appointment. Unfortunately this extreme case does not work (bug), and the notification command is never launched (even if it were, system load could delay the execution of `calcurse --next` till after the appointment start time). Try `notification.warning=2` (with calcurse running interactively).

Now for the daemon. As you can see from the daemon log, it wakes up once every minute. It then checks whether the time left to the next appointment is less than the `notication.warning` interval. If so, the `notification.command` is launched. This is a somewhat crude mechanism, and the notification may be up to 60 seconds late or _not forthcoming at all_, if the warning period is less than 60 seconds and the daemon is at sleep during the entire period. In your case that is bound to happen.

**Comment by fmv1992** [comment]
Thank you for your anser; I have moved over to cron. I think it may be more suitable for my needs for now. I'm going to close this issue.
