### ISSUE TITLE
Characters Next To Date Under Appointments

### ISSUE THREAD

**Issue by sla0101** [lfos/calcurse#21]
I compiled 4.2.2 from source on Slackware 14.2 x86_64

I noticed characters appearing next to the date on the left side under the 'Appointments' section. They don't appear for everday, but random days throughout the month.

Is this suppose to mean something, or some bug?

Looks odd to me, if this is suppose to serve a purpose, I'd personally like to get rid of it.

All I can tell looking at a calendar at my home is some representation of the moon?

If this is for the moon, is there an option to disable this?

Hmm

|)   January 04, 2017
(|)  January 11, 2017
|   January 27, 2017

**Comment by sla0101** [comment]
I see the same thing in 3.2.1

**Comment by lfos** [comment]
Those icons indeed represent moon phases. I might implement an option to disable this feature but it's pretty low priority.

**Comment by lfos** [comment]
Fixed in 172efd7 (Remove phase of moon feature, 2017-09-05).
