### ISSUE TITLE
Appointment Time With Two Digits

### ISSUE THREAD

**Issue by Ad-An** [lfos/calcurse#219]
If I want to write an appointment time lets say 21:00 then by simply writing 21 it takes it as a date not a time although it specifically ask for a time. 

I can understand that this might have been an idea for easily creating events but if two digits are seen as a date then shouldn't immediately after accepting it as a date ask me for a new time? 

Also given that most of the appointment times are in the form XX:00 then wouldn't it be a good idea to also accept time given with two digits?

Is a specific idea behind this? Is this actually a mechanism to easily create events? it seems weird to ask for a time and then accept a date.

**Comment by lfos** [comment]
You can use `21:`. Is that good enough?

**Comment by Ad-An** [comment]
Sure! I was just wondering mainly due to the user experience because when the program asks for a time and you give a time, you don't actually expect it to act as a date. It is not intuitive. Is this a design choice to have the two digits act as a date?

**Comment by lhca** [comment]
> If I want to write an appointment time lets say 21:00 then by simply writing 21 it takes it as a date not a time although it specifically ask for a time.

Which calcurse version are you using?

**Comment by Ad-An** [comment]
I am using 4.2.1. I installed it through the repository.

**Comment by lfos** [comment]
I cannot reproduce with current master. It seems like this was "fixed" in one of the input overhaul patches between 4.3.0 and 4.4.0. Please try again with a more recent release.

**Comment by lhca** [comment]
> I am using 4.2.1. from the repository.

That's a fairly old one (October 2016). You should move to 4.4.0.

When you discuss a problem, please provide enough details to allow your actions to be _exactly_ repeated and your experience hopefully reproduced.

**Comment by Ad-An** [comment]
I am trying to build from source to get the new version as you said but it doesn't seem to work.

I downloaded the source code, I cd to the directory, I run `./autogen.sh` and then `./configure` but when I run make it says 

```
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by lfos** [comment]
Either install AsciiDoc or use `./configure --disable-docs`.

**Comment by Ad-An** [comment]
`./configure --disable-docs` doesn't change anything. Still the same behavior.

**Comment by lfos** [comment]
You need to stop ignoring all build instructions and error messages. Install autotools and gettext. Then start the whole process again.

**Comment by Ad-An** [comment]
I do have both of this installed. I just checked.

**Comment by lfos** [comment]
You also need autopoint which is a separate package if you are using a Debian-based distribution.

**Comment by Ad-An** [comment]
I have installed every single thing and it still doesn't work. I will stick to the packaged version from the repositories for the time being. Thank you for your time I know you must have better things to do. :P

**Comment by lfos** [comment]
Instead of "installing every single thing", you should have read the error messages. They are very clear about what is missing...

**Comment by Ad-An** [comment]
That is what I meant obviously, everything from the error list. At the end there was nothing missing. all the errors were gone! Anyway I am back to the previous version. Thanks for your time. I really appreciated it. :)

**Comment by lfos** [comment]
You are welcome! Since you mentioned "it still doesn't work", I assumed there still was an error. If there are no more errors, then everything compiles and you are done.
