### ISSUE TITLE
Versions Listed For Download On Github Don't Work...

### ISSUE THREAD

**Issue by sla0101** [lfos/calcurse#22]
I didn't download every version you have listed on GitHub, but many of them I tried failed, so I'm assuming they all do.

Because if I download 3.2.1 from GitHub it fails, but if I download it from the URL below it works.

http://calcurse.org/files/calcurse-3.2.1.tar.gz

I think you need to remove all the versions you have listed here for download and redo them over.

Here's the output from the terminal for the GitHub versions;

git-version-gen: unknown version number.
configure.ac:8: error: AC_INIT should be called with package and version arguments
/usr/share/aclocal-1.15/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:8: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
git-version-gen: unknown version number.
git-version-gen: unknown version number.
configure.ac: error: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
configure.ac: that aclocal.m4 is present in the top-level directory,
configure.ac: and that aclocal.m4 was recently regenerated (using aclocal)
configure.ac:17: installing './config.guess'
configure.ac:17: installing './config.sub'
Makefile.am:7: error: ENABLE_DOCS does not appear in AM_CONDITIONAL
doc/Makefile.am:3: error: HAVE_ASCIIDOC does not appear in AM_CONDITIONAL
doc/Makefile.am:10: error: HAVE_A2X does not appear in AM_CONDITIONAL
doc/Makefile.am:62: error: HAVE_ASCIIDOC does not appear in AM_CONDITIONAL
doc/Makefile.am:67: error: HAVE_A2X does not appear in AM_CONDITIONAL
src/Makefile.am: installing './depcomp'
/usr/share/automake-1.15/am/depend2.am: error: am__fastdepCC does not appear in AM_CONDITIONAL
/usr/share/automake-1.15/am/depend2.am:   The usual way to define 'am__fastdepCC' is to add 'AC_PROG_CC'
/usr/share/automake-1.15/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
/usr/share/automake-1.15/am/depend2.am: error: AMDEP does not appear in AM_CONDITIONAL
/usr/share/automake-1.15/am/depend2.am:   The usual way to define 'AMDEP' is to add one of the compiler tests
/usr/share/automake-1.15/am/depend2.am:     AC_PROG_CC, AC_PROG_CXX, AC_PROG_OBJC, AC_PROG_OBJCXX,
/usr/share/automake-1.15/am/depend2.am:     AM_PROG_AS, AM_PROG_GCJ, AM_PROG_UPC
/usr/share/automake-1.15/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
parallel-tests: installing './test-driver'
/usr/share/automake-1.15/am/check2.am: error: am__EXEEXT does not appear in AM_CONDITIONAL
configure.ac:8: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:10: error: possibly undefined macro: AM_GNU_GETTEXT
configure.ac:11: error: possibly undefined macro: AM_GNU_GETTEXT_VERSION
configure.ac:83: error: possibly undefined macro: AM_CONDITIONAL

**Comment by lfos** [comment]
Fixed in 8ab3106 (git-version-gen: Add default version, 2017-09-08).
