### ISSUE TITLE
Update of recurrent item parameters

### ISSUE THREAD

**Issue by lhca** [lfos/calcurse#220]
The recurrent item parameters are type, frequency, until date and (list of) exception dates.

In the master branch version (5283689) the list of exception dates can be edited (like the first three). It is treated separately, which may not be immediately apparent in the UI, but becomes clear when you cancel an edit session (of a recurrent item with exceptions) by pressing ESC while editing type, frequency or until date. The edit session then continues with the exception dates.

This is particularly unfortunate if you cancel while editing the exception dates, because it may lead you to believe that you also cancelled the first part of the edit session.

Instead, the recurrent item parameters should be treated as a unit, and a cancelled edit session should leave all parameters unchanged.

I have a PR coming up.

**Comment by lfos** [comment]
I agree with your analysis and your proposed solution. Looking forward to the PR!

**Comment by lhca** [comment]
> Looking forward to the PR!

The first shot was a bit off the mark. I have uploaded a second attempt.
