### ISSUE TITLE
Error 1044

### ISSUE THREAD

**Issue by rcrx** [lfos/calcurse#224]
After installing 4.5.0 I received the following message on Ubuntu 18.04

> Please report the following bug:                                           
>> io.c: 1044: Too many errors while reading keys file, aborting...

**Comment by lfos** [comment]
Intersting. Which version did you use before upgrading to 4.5.0? Do you think you can share your keys file (`$HOME/.calcurse/keys`)?

**Comment by lhca** [comment]
How do you invoke calcurse? Do you use the `-C` or the `-D` option?

**Comment by rcrx** [comment]
Simple fix. Merely removed the keys file and it seems to work.
