### ISSUE TITLE
Authentication Problem

### ISSUE THREAD

**Issue by gphandrich** [lfos/calcurse#24]
Hello,
I tried to setup an caldav connection - and failed. This is the output with --verbose and --debug:

peter@ideapad:/dokumente/downloads/calcurse-4.2.2$ calcurse-caldav --init=two-way --verbose --debug
Loading configuration from /home/peter/.calcurse/caldav/config...
warning: Dry run; nothing is imported/exported. Add "DryRun = No" to the
warning: [General] section in the configuration file to enable synchronization.
Connecting to 213.168.202.219...
> REPORT /owncloud/remote.php/caldav/calendars/peter/wolke/
> Headers: {'Content-Type': 'application/xml; charset=utf-8'}
> <?xml version="1.0" encoding="utf-8" ?><C:calendar-query xmlns:D="DAV:"                   xmlns:C="urn:ietf:params:xml:ns:caldav"><D:prop><D:getetag /></D:prop><C:filter><C:comp-filter name="VCALENDAR" /></C:filter></C:calendar-query>

< Headers: [('Date', 'Tue, 07 Feb 2017 19:08:56 GMT'), ('Server', 'Apache/2.4.10 (Debian)'), ('Set-Cookie', 'oc8b227bfb18=u4l1f44sr28i56jnvcmujib4h2; path=/owncloud; HttpOnly'), ('Expires', 'Thu, 19 Nov 1981 08:52:00 GMT'), ('Cache-Control', 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0'), ('Pragma', 'no-cache'), ('Strict-Transport-Security', 'max-age=31536000'), ('X-XSS-Protection', '1; mode=block'), ('X-Content-Type-Options', 'nosniff'), ('X-Frame-Options', 'Sameorigin'), ('Content-Security-Policy', "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *"), ('X-Robots-Tag', 'none'), ('WWW-Authenticate', 'Basic realm="ownCloud"'), ('Content-Length', '292'), ('Content-Type', 'application/xml; charset=utf-8')]
< <?xml version="1.0" encoding="utf-8"?>
< <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<   <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
<   <s:message>No basic authentication headers were found</s:message>
<   <s:sabredav-version>1.8.10</s:sabredav-version>
< </d:error>

error: The server at 213.168.202.219 replied with HTTP status code 401
error: (Unauthorized) while trying to access
error: /owncloud/remote.php/caldav/calendars/peter/wolke/.

And here is my .calcurse/caldav/cofig file:
# Host name of the server that hosts CalDAV.
Hostname = 213.168.202.219

# Path to the CalDAV calendar on the host specified above.
Path = /owncloud/remote.php/caldav/calendars/peter/wolke

# Enable this if you want to skip SSL certificate checks.
InsecureSSL = Yes

# Disable this option to actually enable synchronization. If it is enabled,
# nothing is actually written to the server or to the local data files. If you
# combine DryRun = Yes with Verbose = Yes, you get a log of what would have
# happened with this option disabled.
DryRun = Yes

# Enable this if you want detailed logs written to stdout.
Verbose = Yes

# Credentials for HTTP Basic Authentication. Leave this commented out if you do
# not want to use authentication.
#[Auth]
Username = nnnnnn
Password = nnnnnn

# Optionally specify additional HTTP headers here.
#[CustomHeaders]
#User-Agent = Mac_OS_X/10.9.2 (13C64) CalendarAgent/176

Any ideas why this does not work? I would be glad if I could use calcurse with my caldav-server ...

Thanks for thinking about it.
Peter

**Comment by lfos** [comment]
You need to uncomment the `[Auth]` section header.

**Comment by gphandrich** [comment]
Yes - sometimes being stupid. Thanks for the help - everything is fine now.
