### ISSUE TITLE
Duplicate day in calendar view

### ISSUE THREAD

**Issue by mbellitti** [lfos/calcurse#244]
**Version**: 4.5.0

**Bug description.** In calendar view for the month of Nov 2019 the date 2019-11-03 appears twice in a row, once as a Sunday and once as a Monday. This is inconsistent with the appointment wiew, which shows the correct dates:

![2019-10-10-134913_870x254_scrot](https://user-images.githubusercontent.com/5868852/66593324-c5d77700-eb64-11e9-9e92-4b753db08c8b.png)

Notice how in the calendar view the cursor is on 2019-11-03 (and it is duplicated) making all the following days for the month of November the wrong day of the week.

**Reproduce.** Go to date 2019-11-03 in calendar view. I am currently using calcurse-caldav to sync to a NextCloud instance, but I have tried deleting all the relative files and the bug is still presents.

**Expected Behavior.** 2019-11-02 should show up in calendar view as a Sunday, and 2019-11-04 as a Monday.

**Comment by lhca** [comment]
Please see #233.

**Comment by mbellitti** [comment]
That solves the problem, thank you. I'm sorry I could not find that issue earlier.
