### ISSUE TITLE
[Feature request] Support to hide the status bar at bottom.

### ISSUE THREAD

**Issue by kevinhwang91** [lfos/calcurse#246]
It wastes space, especially running inside tmux.
Could provide a key to trigger the bar?

**Comment by kevinhwang91** [comment]
> Good idea! It's a non-trivial task to implement this, though, since the bar also needs to pop up automatically whenever a prompt appears.

Yes, It's a hard task relative to the interactive command.
Maybe pop up a window in the center or render the bottom until the command is completed or canceled.

**Comment by sz47** [comment]
Hey are you planning to implement this?

**Comment by darkralts** [comment]
im interested aswel, @kevinhwang91. even if its temporarily. i would much rather a toggle as the buttons are actually useful, but when calcurse is just sitting there open not doing anything its useful to me to hide them, it looks better, and more space.

**Comment by 0pLuS0** [comment]
Hello @lfos 

Was this ever implemented?

I'm using 4.8.1 and looking around the settings/config trying to figure this out?

THANKS

**Comment by sohzm** [comment]
im working on it [sohzm/calcurse](https://github.com/sohzm/calcurse), will post as i have progress
