### ISSUE TITLE
calcurse-caldav - Attempting to use Nextcloud CalDAV

### ISSUE THREAD

**Issue by kickore** [lfos/calcurse#248]
Hello,

I'm attempting to use calcurse-caldav to sync with my Nextcloud calendar using oauth2

The issue I'm having seems to be in calcurse-caldav's use of the `oauth2client` python library:

```
└─ calcurse-caldav --init=two-way
warning: Dry run; nothing is imported/exported. Add "DryRun = No" to the
warning: [General] section in the configuration file to enable synchronization.
Connecting to [my-domain]...

If a browser window did not open, go to the URL below and log in to authorize syncing. Once authorized, pass the string after "code=" from the URL in your browser's address bar to calcurse-caldav.py using the "--authcode" flag. Example: calcurse-caldav --authcode 'your_auth_code_here'

https://accounts.google.com/o/oauth2/v2/auth?client_id=8[my-client-id]&redirect_uri=https%3A%2F%2F[my-domain]%2Fremote.php%2Fdav%2F&scope=https%3A%2F%2F[my-domain]%2Fremote.php%2Fdav%2F&access_type=offline&response_type=code

error: Access token is missing or refresh token is expired.

```
In the `oauth2client` python library, it appears to be based around the Google Calendar API, so it generating this URL makes sense.

Is there a way to work around this aside from modifying the library to reference my Nextcloud instance? I'd very much rather not do that for... reasons:
```

└─ grep -ir google /usr/lib/python3.7/site-packages/oauth2client/ | wc -l
265
```

**Comment by lfos** [comment]
It turns out that `oauth2client` has been deprecated, so we might want to look for alternatives anyway...

**Comment by matt-horwood-mayden** [comment]
If it helps, I have it working with auth.

Used Auth and a PW for calcaurse
```
# If you want to synchronize calcurse with a CalDAV server using
# calcurse-caldav, create a new directory ~/.calcurse/caldav/, copy this file
# to ~/.calcurse/caldav/config and adjust the configuration below.

[General]
# Path to the calcurse binary that is used for importing/exporting items.
Binary = calcurse

# Host name of the server that hosts CalDAV.
Hostname = nextcloud.domain.com

# Path to the CalDAV calendar on the host specified above.
Path = remote.php/dav/calendars/username/calendar/

# Type of authentication to use. Must be "basic" or "oauth2"
AuthMethod = basic

# Enable this if you want to skip SSL certificate checks.
InsecureSSL = No

# Disable this if you want to use HTTP instead of HTTPS.
# Using plain HTTP is highly discouraged.
HTTPS = Yes

# This option allows you to filter the types of tasks synced. To this end, the
# value of this option should be a comma-separated list of item types, where
# each item type is either "event", "apt", "recur-event", "recur-apt", "todo",
# "recur" or "cal". Note that the comma-separated list must not contain any
# spaces. Refer to the documentation of the --filter-type command line argument
# of calcurse for more details. Set this option to "cal" if the configured
# CalDAV server doesn't support tasks, such as is the case with Google
# Calendar.
SyncFilter = cal

# Disable this option to actually enable synchronization. If it is enabled,
# nothing is actually written to the server or to the local data files. If you
# combine DryRun = Yes with Verbose = Yes, you get a log of what would have
# happened with this option disabled.
DryRun = No

# Enable this if you want detailed logs written to stdout.
Verbose = Yes

# Credentials for HTTP Basic Authentication. Leave this commented out if you do
# not want to use authentication.
[Auth]
Username = username
Password = password

# Optionally specify additional HTTP headers here.
#[CustomHeaders]
#User-Agent = Mac_OS_X/10.9.2 (13C64) CalendarAgent/176

# Use the following to synchronize with an OAuth2-based service
# such as Google Calendar.
#[OAuth2]
#ClientID = 
#ClientSecret = 

# Scope of access for API calls. Synchronization requires read/write.
#Scope = https://www.googleapis.com/auth/calendar

# Change the redirect URI if you receive errors, but ensure that it is identical
# to the redirect URI you specified in the API settings.
#RedirectURI = http://127.0.0.1
```

**Comment by zoof** [comment]
@matt-horwood-mayden Thank you for sharing your config!  I have a NextCloud instance that comes with mail-in-a-box and it's not working for me.  Any suggestions?

    $ calcurse-caldav --init=two-way
    Connecting to box.example.com...
    error: The server at box.example.com replied with HTTP status code 401
    error: Allowed) while trying to access https://box.example.com/remote.php/d
    error: av/calendars/user@example.com/calendar/.

**Comment by matt-horwood-mayden** [comment]
for your password, try an app password in nextcloud

**Comment by zoof** [comment]
Interesting -- seems to have gotten a little further (405 instead of 401)...

    $ calcurse-caldav --init=two-way
    Connecting to box.example.com...
    error: The server at box.example.com replied with HTTP status code 405 (Not
    error: Allowed) while trying to access https://box.example.com/remote.php/d
    error: av/calendars/user@example.com/calendar/.

**Comment by matt-horwood-mayden** [comment]
have you set the `Path` to your full calender?

**Comment by zoof** [comment]
I modified yours with my own username and password (and tried the app password).  To reach the web interface, one uses https://box.example.com/cloud so I also tried prefixing your `Path` with `cloud` which gives me a 401 error, making me think that yours is more correct.  I had no problem configuring my iPhone to access the NextCloud instance.

**Comment by matt-horwood-mayden** [comment]
is `user@example.com` your username?
if you click the `...` button on a calender from the web UI and use the `copy private link` option you should have a full link that you can use to fill in the path.

**Comment by zoof** [comment]
Ah, I see.  The full link is `https://box.example.com/cloud/remote.php/dav/calendars/user@example.com/personal/`.  I substituted `personal` for `calendar` in your config and still get a 405.  If I prepend that with `cloud`, I get a 401.

**Comment by matt-horwood-mayden** [comment]
I see, your path should be `cloud/remote.php/dav/calendars/user@example.com/calendar/`
If that still fails, it could be am issue with calcurse and your username with an `@`

**Comment by zoof** [comment]
Ok, that produces a 401:

    $ calcurse-caldav --init=two-way
    Connecting to box.example.com...
    error: The server at box.example.com replied with HTTP status code 401
    error: (Unauthorized) while trying to access https://box.example.com/cloud/
    error: remote.php/dav/calendars/user@example.com/calendar/.

Do you know if I should I open a new issue with `calcurse-caldav` or will this issue serve?

**Comment by lfos** [comment]
Could you please share your full config (with your password and other personal data redacted)?

**Comment by zoof** [comment]
Sure, here it is.

```
# If you want to synchronize calcurse with a CalDAV server using
# calcurse-caldav, create a new directory at $XDG_CONFIG_HOME/calcurse/caldav/
# (~/.config/calcurse/caldav/) and $XDG_DATA_HOME/calcurse/caldav/
# (~/.local/share/calcurse/caldav/) and copy this file to
# $XDG_CONFIG_HOME/calcurse/caldav/config and adjust the configuration below.
# Alternatively, if using ~/.calcurse, create a new directory at
# ~/.calcurse/caldav/ and copy this file to ~/.calcurse/caldav/config and adjust
# the configuration file below.

[General]
# Path to the calcurse binary that is used for importing/exporting items.
Binary = calcurse

# Host name of the server that hosts CalDAV.
Hostname = box.example.com

# Path to the CalDAV calendar on the host specified above.
Path = cloud/remote.php/dav/calendars/user@example.com/calendar/

# Type of authentication to use. Must be "basic" or "oauth2"
AuthMethod = basic

# Enable this if you want to skip SSL certificate checks.
InsecureSSL = No

# Disable this if you want to use HTTP instead of HTTPS.
# Using plain HTTP is highly discouraged.
HTTPS = Yes

# This option allows you to filter the types of tasks synced. To this end, the
# value of this option should be a comma-separated list of item types, where
# each item type is either "event", "apt", "recur-event", "recur-apt", "todo",
# "recur" or "cal". Note that the comma-separated list must not contain any
# spaces. Refer to the documentation of the --filter-type command line argument
# of calcurse for more details. Set this option to "cal" if the configured
# CalDAV server doesn't support tasks, such as is the case with Google
# Calendar.
SyncFilter = cal,todo

# Disable this option to actually enable synchronization. If it is enabled,
# nothing is actually written to the server or to the local data files. If you
# combine DryRun = Yes with Verbose = Yes, you get a log of what would have
# happened with this option disabled.
DryRun = No

# Enable this if you want detailed logs written to stdout.
Verbose = Yes

# Credentials for HTTP Basic Authentication. Leave this commented out if you do
# not want to use authentication.
#[Auth]
Username = user@example.com
Password = password

# Optionally specify additional HTTP headers here.
#[CustomHeaders]
#User-Agent = Mac_OS_X/10.9.2 (13C64) CalendarAgent/176

# Use the following to synchronize with an OAuth2-based service
# such as Google Calendar.
#[OAuth2]
#ClientID = your_client_id
#ClientSecret = your_client_secret

# Scope of access for API calls. Synchronization requires read/write.
#Scope = https://example.com/resource/scope

# Change the redirect URI if you receive errors, but ensure that it is identical
# to the redirect URI you specified in the API settings.
#RedirectURI = http://127.0.0.1
```

**Comment by lfos** [comment]
You need to remove the pound sign (`#`) in front of `[Auth]`.

**Comment by zoof** [comment]
Oh duh -- clearly not paying enough attention...

Unfortunately, I'm now getting a 404 error.

```
$ calcurse-caldav --init=two-way
Connecting to box.example.com...
error: The server at box.example.com replied with HTTP status code 404 (Not
error: Found) while trying to access https://box.example.com/cloud/remote.p
error: hp/dav/calendars/user@example.com/calendar/.
```

**Comment by lfos** [comment]
Were you able to resolve this? Unfortunately, I do not use Nextcloud myself and cannot help you much with anything more specific to your setup.

**Comment by zoof** [comment]
Thank you responding!  I gave up on it.  `calcurse` is not exactly the calendar app I was looking for (I ideally want notifications and reminders).  Contact and calendar syncing were my big issues with Thunderbird and a new addon (tbsync) has solved that problem.

**Comment by lfos** [comment]
Thank you for your feedback! We're working on improving notification/reminder support in calcurse. Glad you found a setup that works well for you.

**Comment by jaboto** [comment]
> You need to remove the pound sign (`#`) in front of `[Auth]`.

Some years later but this made it for me. I was not paying attention to realized that the Auth itself is commented. Thanks a lot.

**Comment by igorzhilin** [comment]
Just for anyone who bumps into this several years later, again. An important addition for `calcurse-caldav` and Nextcloud URL.

## Nextcloud has calendar names, and they must be included in the URL

While other CalDAV apps, e.g. DAVx5 for Android, first run DAV discovery and then allow you to select the calendars to sync, the `calcurse-caldav` script expects the exact URL of a **single calendar** WebDAV API endpoint.

```
Path = /remote.php/dav/calendars/$USERNAME/$CALENDARNAME/
```

Some posters mention `$USERNAME/personal`, but this is specific URL to the default "Personal" calendar. However, if your calendar has a different name, you must take care of this.
