### ISSUE TITLE
doesn't save imported apppointments on Arch by default

### ISSUE THREAD

**Issue by ec1oud** [lfos/calcurse#249]
Arch Linux currently offers a 4.5.1 package.  I installed it, and used the menu function to import an .ics file (that I had exported from my phone).  (Other, Import)  Appointments show up on the calendar.  If I invoke the Save function from the menu, it says data has already been saved.  But when I quit calcurse and restart it, there are no appointments.  I can see that .calcurse/apts is empty (zero length).

This is repeatable: import always works, but saving the new appointments after import always fails.  But if I add an appointment manually using control-A, that one will be saved.  Having saved that does not fix the import feature though: if I import again, I see appointments; if I quit, .calcurse/apts remains the same size as it was before the import.

I'm able to use the config menu to change configuration, and in that case  .calcurse/conf is written correctly too.

**Comment by lhca** [comment]
I can confirm the described behaviour. As a workaround you can import the file from the command line (option `-i`).

I have mailed a patch to the calcurse bugs mailing list.

**Comment by lfos** [comment]
I merged the patch into `pu`. Thanks Shawn for reporting the bug and thanks Lars for creating a patch. I think we will have another maintenance release soon.
