### ISSUE TITLE
Notify-bar, no recurrent appointment

### ISSUE THREAD

**Issue by rgc69** [lfos/calcurse#25]
I noticed that no appointments appear in the notify-bar (next appointment within the upcoming 24 hours),  if they are marked as recurrent. It's this correct? Thank you

EDIT: Nor notifications sends

**Comment by lfos** [comment]
Probably not. I get notifications for recurrent items. Which calcurse version are you using? What does the item (line in the data file) look like?

**Comment by rgc69** [comment]
Hi, calcurse version 4.2.2. The line for a recurrent appointments looks like:
02/08/2017 @ 18:30 -> 02/08/2017 @ 19:15 {1D -> 03/01/2017} |Blacklist
Notify-bar (& notifications) works great with "normal" apointments:
02/14/2017 @ 09:00 -> 02/14/2017 @ 07:30|San Valentino

**Comment by lfos** [comment]
Works fine for me. Can you try to reproduce the issue on a stock configuration? And maybe a data file which contains nothing but the recurrent item in question?

**Comment by rgc69** [comment]
I think I got it. It's a problem with notification.notifyall, and the '!' flag. Even if notification.notifyall=all (as far as I understand, in this way all the events are notified), only  If I put a '!' on the recursive event, the remaining time to the recursive event is visible inside the notify-bar. And no matter what is the value of notification.notify ('all', 'flagged' or 'unflagged'), only the "normal" items (i.e. not the recurrent one's) are notified according to the value, and visible in the notify-bar. Just to be clear, with the recursive one, no matter the value of notification.notify, I have to put (or remove) the '!' flag (it's like a trick), and then I can see the remaining time in the notify-bar (but no notification in the end).

**Comment by lfos** [comment]
I think I was able to debug and fix this, seems like it is not related to flagging at all. Could you please check the commit on current master and see whether it fixes the issue?

**Comment by lfos** [comment]
Also, could you please open another ticket for the (unrelated) notify-send issue? Thanks!

**Comment by rgc69** [comment]
Now everything's fine, notify-bar and notify-send issues! Thank you very much!

**Comment by lhca** [comment]
Can you confirm that at the time of your query the event were to happen after midnight (belonging to tomorrow)? If so, it will appear after midnight!

**Comment by chaosmonk1** [comment]
Thanks, you're right. After midnight the event appeared. Is there a way to override this behavior so that recurring events appear 24 hours in advance like non-recurring events do?

**Comment by lhca** [comment]
No. It's a bug, unfortunately. If you are not building calcurse yourself, you will have to wait for the next release.

If you do build calcurse yourself, you can have a look at my cloned repository. The first commit of the branch notify-review contains a fix (https://github.com/lhca/calcurse/commit/4cc6a558107310b9c8be1c39a1ce80fdf49d3d2c).

**Comment by chaosmonk1** [comment]
> If you do build calcurse yourself, you can have a look at my cloned repository. The first commit of the branch notify-review contains a fix (https://github.com/lhca/calcurse/commit/4cc6a558107310b9c8be1c39a1ce80fdf49d3d2c).

That fixed it. Thanks!
