### ISSUE TITLE
Todo List Task Priority Not Carried Over After Importing .ical Version Of Calcurse Calendar

### ISSUE THREAD

**Issue by SBanya** [lfos/calcurse#253]
**Todo List Task Priority Not Carried Over After Importing .ical Version Of Calcurse Calendar** 

**Version information.** Specify the calcurse version you are using. 
Using latest version.

**Bug description.** Provide a clear and concise description of what the bug is.

**Reproduce.** Please try to reproduce the bug before reporting. Describe steps to reproduce the behavior.

Hello Calcurse Dev Team,

I am reporting this bug because my task prioritization setting values are not being imported while using the -i parameter that imports the .ical export of my Calcurse calendar.

The main issue is that although it properly imports my appointments and tasks correctly, the priorization of tasks is completely stripped of any priority, so they all are just tasks on a list, which is not what I want since I painstakingly thought of which tasks have higher priority than others.

**Steps To Reproduce:**
1. I have a related cron job on my local Lubuntu computer running Lubuntu 19.04 Disco that does the following items:

- It deletes existing todo list, and downloads the latest .ical file, and imports it with the -i parameter.

- Here's the exact crontab -e command minus my personal site specific stuff which I've indicated in parentheses for personal reasons:

- `*/5 * * * * cd /home/(username)/.calcurse && rm -f apts todo && cd /home/(username)/calendar && rm -f calcurse.ical && wget (website directory's calendar section).ical && calcurse -i calcurse.ical`

**Expected Behavior.** A clear and concise description of what you expected to happen.

I expected the tasks to be imported correctly with their appropriate task prioritization intact.

**Screenshots.** If applicable, you can add screenshots to help explain your problem.

**Comment by lfos** [comment]
How are the iCal files generated? Are they exported from another calcurse instance? Could you please provide a snippet that contains a full `VTODO` block for one of the items? Which calcurse version are you using?

**Comment by lfos** [comment]
Status?

**Comment by SBanya** [comment]
Hi there, sorry about the delay.

The iCal files are generated by a cron tab script.

I have changed a few of the directory names as they're a bit personal, but I wanted to be descriptive to help you understand my issue, so here is the Cron tab job over SSH:

**OVER SSH (Calcurse)** 
*  * * * * calcurse -xical > /var/www/musimatic.net/public_html/calendar/calcurse.ical

Here is the Cron tab job on the local machine which deletes the existing appointments, and then reads them (I also abbreviated the wget portion for personal reasons):

**LOCAL MACHINE:**
*/5 * * * * cd /home/sam/.calcurse && rm -f apts todo && cd /home/sam/calendar && rm -f calcurse.ical && wget <ssh location: calcurse.ical> && calcurse -i calcurse.ical

**Output of Calcurse's Version (SSH):**
calcurse 4.2.1 -- text-based organizer

Copyright (c) 2004-2016 calcurse Development Team.
This is free software; see the source for copying conditions.

**Output of Calcurse's Version (Local Machine):**
calcurse 4.3.0 -- text-based organizer

Copyright (c) 2004-2017 calcurse Development Team.
This is free software; see the source for copying conditions.

**Here are related screenshots:**
SSH version which contains the priority of my tasks:
https://ibb.co/6yH79xJ

Local machine version which lost all of the priority of tasks:
https://ibb.co/p0ByQ9G

**Comment by lfos** [comment]
You claimed to be using the "latest version" of calcurse but what you're using is more than 3 years olg. Please upgrade to 4.5.1. I think the bug you describe should be fixed in that release.
