### ISSUE TITLE
Recurrent appointment issue

### ISSUE THREAD

**Issue by rgc69** [lfos/calcurse#26]
Hi, sorry to bother you again, but there are issues with the recurrent appointments.... 
Version: calcurse 4.2.2-3-g2084
Let me try to explain. Yesterday all my (new, first time insert) appointments were notified as they have to: notify-bar countdown, notify-send bubble, all ok. Today, my first 7 recurrent appointments are missed (in the sense that there is no countdown for the first of them), and the notify-bar notify me only of the last one, this evening at 8:10pm. My notification.notifyall = unflagged-only , and all the appointments are unflagged, BUT, if I flag and then unflag the first one of this morning(the trick I show you last time), it appears in the notify-bar! I show you my data:
02/10/2017 @ 11:30 -> 02/10/2017 @ 12:30 {1D -> 06/15/2017} |Haskell
02/10/2017 @ 13:10 -> 02/10/2017 @ 14:00 {1D} |Lunch
02/10/2017 @ 15:30 -> 02/10/2017 @ 16:30 {1D -> 06/15/2017} |Test
02/10/2017 @ 16:35 -> 02/10/2017 @ 16:55 {1D} |Gymn
02/10/2017 @ 17:30 -> 02/10/2017 @ 18:30 {1D -> 06/15/2017} |Mathematica
02/10/2017 @ 18:35 -> 02/10/2017 @ 19:20 {1D -> 02/14/2017} |Blacklist
02/10/2017 @ 20:10 -> 02/10/2017 @ 20:55 {1D} |Dinner
02/11/2017 @ 09:30 -> 02/11/2017 @ 10:30 {1D -> 06/15/2017} |Test
I get notification countdown for Dinner, and not for the other ones. Lunch, for example, has the same structure, but it's not in the notify-bar. Even if I change it in Aunch (alphabetical order :) ), there is always Dinner. Thank you for your work, and let me know :)

**Comment by lfos** [comment]
There was another bug in the notification code for recurrent items. Should be fixed now!
