### ISSUE TITLE
syntax error in the item date (of format "20190102T080000")

### ISSUE THREAD

**Issue by hoijui** [lfos/calcurse#262]
trying to load an iCal file (that works in `gnome-contacts`) fails.

`calcurse` version, input file and error follow:

version:

```bash
$ calcurse -v
calcurse 4.5.0 -- text-based organizer

Copyright (c) 2004-2017 calcurse Development Team.
This is free software; see the source for copying conditions.
```

iCal input file (_tsts.ical_):
```ical
BEGIN:VCALENDAR
BEGIN:VEVENT
DTSTAMP:20200215T075325Z
DTSTART:20190102T080000
DTEND:20190102T120000
END:VEVENT
END:VCALENDAR
```

`calcurse` call and error:

```bash
$ calcurse -c tsts.ical
 ┌────────────────────────────────────────────────────────────────────────────┐
 │                           /!\ INTERNAL ERROR /!\                           │
 ├────────────────────────────────────────────────────────────────────────────┤
 │Please report the following bug:                                            │
 │                                                                            │
 │           io.c: 515: tsts.ical:1: syntax error in the item date            │
 │                                                                            │
 │                                                                            │
 │                                                                            │
 └────────────────────────────────────────────────────────────────────────────┘
```

**Comment by lhca** [comment]
You should not _load_ the iCalendar file, but _import_ it. The option to use `-i`,  not `-c`, which expects a file in calcurse calendar format.

**Comment by hoijui** [comment]
ahaa!! :D
hmmm, but still:

```bash
calcurse -i tsts.ical
ical.c: 1132: Warning: ical header malformed or wrong version number. Aborting...
Import process report: 0009 lines read
0 apps / 0 events / 0 todos / 0 skipped
```

**Comment by hoijui** [comment]
according to [Wikipedia](https://en.wikipedia.org/wiki/ICalendar#Core_object):

> `VERSION:2.0` indicates that the data is in iCalendar format. `VERSION:1.0` was used to specify that data is in the old vCalendar format

It seems to be common practice to assume `VERSION:2.0` if no version is present (at least with a file extension of `.ical`).

**Comment by hoijui** [comment]
https://github.com/lfos/calcurse/pull/263

**Comment by lhca** [comment]
> It seems to be common practice to assume `VERSION:2.0` if no version is present (at least with a file extension of `.ical`).

I don't know about that. However, the iCalendar specification (RFC 5545) says in section "3.7.4. Version":

> Property Name:  VERSION
...
> Conformance:  This property MUST be specified once in an iCalendar
      object.

**Comment by hoijui** [comment]
thank you for that! :-)
I made [a pull request with the iCal4j library](https://github.com/ical4j/ical4j/pull/394)
