### ISSUE TITLE
Exported iCalender events not properly escaped

### ISSUE THREAD

**Issue by kechpaja** [lfos/calcurse#265]
The iCalendar specifications (https://tools.ietf.org/html/rfc5545#page-11) require that commas, semicolons, colons, and a few other characters be escaped in the values of most fields of an iCalendar event. However, when I export an event from Calcurse that includes commas in the text, they are unescaped, e.g. in the 'SUMMARY' field of the following:

>BEGIN:VCALENDAR
>PRODID:-//calcurse//NONSGML v4.5.1-24-gada0//EN
>VERSION:2.0
>BEGIN:VEVENT
>DTSTART;VALUE=DATE:20200612
>SUMMARY:Absolute, final, no-way-around-asking-for-more-time *graded* thesis deadline
>UID:89455665661fc33f4ab85ab7b1df8ce07594301f
>END:VEVENT
>END:VCALENDAR

The unescaped commas are then misinterpreted by my CalDAV server, which truncates the summary of the above event to "SUMMARY:Absolute".

**Comment by kechpaja** [comment]
#266 provides a very simple patch that wraps the contents of the SUMMARY field in quotes when an event is exported, allowing events containing commas, semicolons, and colons to meet the specifications. However, it does nothing to prevent double quotes (forbidden by RFC 5545) from making it into the exported iCalendar item — I decided that adding code to remove or replace them would be overstepping my bounds as a random contributor sharing a fix that I personally had to make, since there are a couple of options for how to deal with them and the decision about which one is correct should be made by the project maintainers.

**Comment by lhca** [comment]
> The iCalendar specifications (https://tools.ietf.org/html/rfc5545#page-11) require that commas, semicolons, colons, and a few other characters be escaped in the values of most fields of an iCalendar event.

This is a very broad, inaccurate statement, and the reference is misleading. We must look at the property in question: SUMMARY. The value of a SUMMARY property is of type TEXT which is defined here: https://tools.ietf.org/html/rfc5545#section-3.3.11.

**Comment by lhca** [comment]
> #266 provides a very simple patch that wraps the contents of the SUMMARY field in quotes when an event is exported, allowing events containing commas, semicolons, and colons to meet the specifications.

I don't see how quoting should help. In a value of type TEXT, the double quote (DQUOTE) is an allowed character.

> However, it does nothing to prevent double quotes (forbidden by RFC 5545) 

? Please  provide a reference.

**Comment by kechpaja** [comment]
Hmm, you're right on all counts, and I spoke too soon and didn't spent enough time trying to make sense of that RFC. 

Will post an update to the pull request in a couple of minutes.
