### ISSUE TITLE
Log file is deletd before exiting calcurse

### ISSUE THREAD

**Issue by hoijui** [lfos/calcurse#269]
Using latest git version (`lfos/pu` 96c0790804f9c80803debc2e7b61d216ab66b3af),

When trying ot import an invalid iCal file with `calcurse -i invalid.ical`, I get:

> Some items could not be imported. See /tmp/calcurse_log.X1ofgB for details.

But this file is deleted in [`io_log_free`](https://github.com/lfos/calcurse/blob/96c0790804f9c80803debc2e7b61d216ab66b3af/src/io.c#L1448) before exiting calcurse, which kind of defeats the purpose of a log-file.

**Expected Behavior.** Do not delete/unlink the log-file on exit.

**Comment by lhca** [comment]
Yes, that is unfortunate. I am working on a patch.

**Comment by hoijui** [comment]
ahh nice, thank you! :-)
.. and yes, at least in those cases, for sure, it should be left.

**Comment by lfos** [comment]
I guess this can be closed now?
