### ISSUE TITLE
-d prints to terminal 

### ISSUE THREAD

**Issue by twofivetwo** [lfos/calcurse#275]
Hey, I'd like to be able to view multiple apt days at the same time. Am I correct in thinking that 'calcurse -d 7' should return 7 days of appointments. For me it prints 7 days to the terminal without launching calcurse.

**Comment by lhca** [comment]
Yes, and that is what it does. Calcurse is terminal-based. Which version are you using (calcurse -v)? Since version 4.5.0, just invoke calcurse interactively (no options). It figures out automatically how many days will fit into your terminal window.

**Comment by twofivetwo** [comment]
It must be a version issue. I appear to be on 4.3.0  I guess what I'm seeing when using -d is the non interactive mode. Will update now. Thank you.

**Comment by twofivetwo** [comment]
all sorted now.
