### ISSUE TITLE
How can I temporarily open an ics file?

### ISSUE THREAD

**Issue by GideonWolfe** [lfos/calcurse#278]
I am writing a program to interface with an API which will return URLs to `.ics` files. 

I want to allow users to use calcurse as a frontend to view those `.ics` files. 

As far as I can tell, I need to combine two command line options into one command, which I haven't been able to get working.

`calcurse -i cal.ics` imports the calendar fine
`calcurse --read-only` opens calcurse without saving to a database.

How can I combine the two to import the `.ics` file in `--read-only` mode so no changes are saved?

Maybe I could create a temp directory and tell calcurse to use it as a config dir, and then delete it after?

**Comment by lfos** [comment]
You can certainly do that. Create a temporary directory and pass it as an argument to `--datadir`.

**Comment by GideonWolfe** [comment]
This works great, thanks.
