### ISSUE TITLE
ical fields containing commas are rejected

### ISSUE THREAD

**Issue by luukvbaal** [lfos/calcurse#280]
**Version information.** 
Noticed on release v4.6.0, some testing on `pu` git branch.
**Bug description.**
ical events are rejected by `--import` due to "malformed description".
This seems to be happening with `DESCRIPTION` (or any other ical field for that matter) containing commas.

**Reproduce.** 
- compile latest git version
- edit `test/data/ical-012` to contain a ','(comma) on a `DESCRIPTION` line(same happens for all the other fields unformatted by `ical_unformat_line`)
- run `test/ical-012.sh` and get error:
```
Some items could not be imported.
See /tmp/calcurse_log.la5hNt for details.
```
running 
`gdb --args calcurse --import dev/calcurse/test/data/ical-012.ical`
reveals:
```
Breakpoint 1, ical_unformat_line (line=<optimized out>, eol=1, indentation=0)
    at ical.c:497
497                                     mem_free(s.buf);
(gdb) print *p
$1 = 44 ','
```
it indeed breaks and returns `NULL` when it encounters a comma, entering the `'\\'` case at `ical.c:497` somehow. I would expect it to skip the `'\\'` case entirely when `*p == ','` as is the case here so not sure whats happening there. Although my c is quite rusty so nvm if I'm talking nonsense.

**Expected Behavior.**
ical event is imported successfully.

Don't have time to debug further currently so I thought I'd open an issue here, as I would like to be able to import my calendar again(worked in v4.5.1 btw).

**Comment by lhca** [comment]
This is as it should be according to the iCalendar standard (RFC 5545). Read the comment above `ical_unformat_line()` in `ical.c`. Much of the recent work on ical import took outset in #271 which has more details.

The ical files you are trying to import do not conform to the iCalendar standard. Where do they come from?

That it "worked" in calcurse 4.5.1 was due to non-standard behaviour (bugs) in calcurse.

**Comment by luukvbaal** [comment]
Thanks for the quick response, not sure how I missed that sorry. The ical files I am trying to import come from my university through [davmail](https://github.com/mguessan/davmail). It seems the issue is with `davmail` since my calendar exported through outlook does seem to escape the commas.

**Comment by isaksamsten** [comment]
Sorry for bumping this issue, but I have submitted a [patch to davmail](https://github.com/mguessan/davmail/pull/206) to fix the issue.
