### ISSUE TITLE
Notification 24 hours before appointment

### ISSUE THREAD

**Issue by mb720** [lfos/calcurse#285]
Hi!

Is there an upper limit to the value of `notification.warning`?

I get notifications for flagged appointments when I use a low value for `notification.warning` like 300 or 10.

But I'd like to get a notification 24 hours before an appointment.

Here's my notification configuration:

    notification.command=echo notified >> /home/me/notifications_from_calcurse
    notification.notifyall=flagged-only
    notification.warning=86400

This doesn't seem to work: I expected to see another line of text in the test file `/home/me/notifications_from_calcurse` but there is none.

I'm using calcurse 4.6.0

Thanks and kind regards!

**Comment by lfos** [comment]
Thanks for the report. There shouldn't be such a limit, so what you describe is most likely a bug. Will investigate!

**Comment by lhca** [comment]
There seems to be a mismatch between the abilities of calcurse and your expectations.

> But I'd like to get a notification 24 hours before an appointment.

Calcurse cannot do that. The notify bar and the configuration options are only concerned with upcoming appointments inside 24 hours. If there are several, the first one is shown in the bar with a count down in front. When the counter reaches zero, the next appointment is shown (if there is one). These are the "notifications" in calcurse.

In addition calcurse can remind you of the next upcoming appointment `notification.warning` seconds before it is reached by blinking with the notify bar text and by launching `notification.command`.

**Comment by mb720** [comment]
Thanks for your candid responses!

For my notifications/reminders, I use [systemd's transient timer units](https://wiki.archlinux.org/index.php/Systemd/Timers#Transient_.timer_units) and email via Mutt now. This schedules sending an email:

    systemd-run --user --on-calendar="2023-05-02 11:30" --timer-property=Persistent=true --property=Restart=on-failure --property=RestartSec=20 -u "Mail_Reminder_from_$(date "+%F_%H-%M-%S")" bash -c "printf \"Hi from $(whoami)!\nDon't forget about X.\" | mutt -s \"This is a ⌛ reminder sent with systemd\" matthias@bullbytes.com"

The timer property `Persistent` makes systemd send the email at the next occasion when the scheduled time has passed while the machine was powered off. `Restart=on-failure` means that systemd will keep trying to send the email if Mutt returned a non-zero exit value which is the case when there's no internet connection. `RestartSec=20` is very useful for this task since systemd should wait a bit before retry attempts so the machine has a chance to connect to the internet.

`--on-calendar` accepts also arguments like "thursday" which will send the email next Thursday. To check if an argument is valid, there's `systemd-analayze calendar thursday`.

I use the command as-is but it could be made more succinct with a Bash function that calls it, hiding the arguments that probably don't change, like `--timer-property=Persistent=true`.

Lists all reminders:

    systemctl --user list-timers *Reminder*

Removes a reminder:

    systemctl --user stop Remove_Me.{service,timer}
