### ISSUE TITLE
problem making calcurse

### ISSUE THREAD

**Issue by coachshea** [lfos/calcurse#29]
I am a longtime calcurse user and have always compiled it myself without problem. I am now trying to compile calcurse on a new computer (debian stretch). After checking out v4.2.2 ./autogen.sh and ./config appear to be working fine, but then when I try to run "make" I get the following error:

    make all-recursive
    make[1]: Entering directory '.../calcurse'
    Making all in po
    make[2]: Entering directory '../calcurse/po'
    test -z "fr.gmo en.gmo de.gmo es.gmo nl.gmo ru.gmo pt_BR.gmo" || make fr.gmo
    en.gmo de.gmo es.gmo nl.gmo ru.gmo pt_BR.gmo
    make[3]: Entering directory '../calcurse/po'
    rm -f fr.gmo && : -c -statistics -o fr.gmo fr.po
    mv: cannot stat 't-fr.gmo': No such file or directory
    Makefile:139: recipe for target 'fr.gmo' failed
    make[3]: ***[fr.gmo] Error 1
    make[3]: Leaving directory '../calcurse/po'
    Makefile:163: recipe for target 'stamp-po' failed
    make[2]: ***[stamp-po] Error 2
    make[2]: Leaving directory '../calcurse/po'
    Makefile:389:recipe for target 'all-recursive failed'
    make[1]:***[all-recurse] Error 1
    make[1]: Leaving directory '../calcurse'
    Makefile:330: recipe for target 'all' failed
    make: ***[all] Error 2

**Comment by lfos** [comment]
This has been open for a while. Are you still able to reproduce the issue? Can you provide a full build log?

**Comment by PaulSt** [comment]
[errorlog.txt](https://github.com/lfos/calcurse/files/2018847/errorlog.txt)
Hi! I am experiencing the same error when building under lubuntu 18.04 with make 4.1 
I am including a file with the full log. This only happens when i try to build the git version. Starting from the tar file of v4.3.0, not using the autogen.sh, works fine.

**Comment by lfos** [comment]
You need to install `msgfmt` to be able to build translations.

**Comment by PaulSt** [comment]
thanks, i missed that! :+1:
