### ISSUE TITLE
Permission denied on post-save hook caldav

### ISSUE THREAD

**Issue by devendr4** [lfos/calcurse#292]
I placed the hook post-save in .config/calcurse/hooks and everytime I exit calcurse I get this error message

`sh: /home/user/.config/calcurse/hooks//post-save: Permission denied
`
If I run calcurse-caldav manually it does synchronize properly

**Comment by lfos** [comment]
What's the output of `ls -l /home/user/.config/calcurse/hooks/post-save`?

**Comment by devendr4** [comment]
-rw-r--r-- 1 user user 1400 may  9 18:17 /home/user/.config/calcurse/hooks/post-save

**Comment by lfos** [comment]
Hooks must be executable, try `chmod +x ~/.config/calcurse/hooks/post-save`.

**Comment by devendr4** [comment]
It worked thanks!
