### ISSUE TITLE
Garbage collector deletes notes.

### ISSUE THREAD

**Issue by crocket** [lfos/calcurse#293]
**Version information.** 4.6.0

**Bug description.** `general.autogc = yes` deletes notes when quitting.

**Reproduce.** Create a note for an event. Quit. Execute calcurse. Try to view the note.

**Expected Behavior.** Note should not be deleted by garbage collector.

**Comment by lfos** [comment]
Thanks for the bug report! I cannot reproduce this locally, though. Is this exactly what you do? No manual editing of any files managed by calcurse; no hooks that modify any files? If yes, could you please be more specific, give a concrete item with all details and a specific note that we can use to reproduce this? Thanks!

**Comment by crocket** [comment]
Add `06/01/2020 [1] {1D -> 06/07/2020} >188bcaeee324c1a9819010463c4750fada9e0e09 5G summit
` as an event to your calendar.

Add `https://the5gsummit.com/event` as a note to the event.

The note is deleted after I quit.

**Comment by lfos** [comment]
Again, I cannot reproduce. Did you verify that the note file first exists and is deleted when exiting? I suspect this might be related to XDG Base Directory support and not to the note GC after all. Do you use `$XDG_DATA_HOME` or `~/.calcurse/` for your data files?

**Comment by crocket** [comment]
~/bin/calcurse

```
/usr/bin/calcurse -C ~/.config/calcurse -D ~/.local/share/calcurse -c /mnt/data/calendars/appointments $@
```

**Comment by lfos** [comment]
The note GC is only executed when exiting calcurse. If the notes are deleted by something at some later point, this is likely unrelated to the GC. Very hard to tell without additional information, though... Are you sure there is nothing else accessing the note files? No hooks, cron job, sync script, ...?

**Comment by crocket** [comment]
I don't have hooks. My cron jobs don't touch home directory. I haven't written any script that touches `~/.local/share/calcurse/notes`

**Comment by crocket** [comment]
While I brushed my teeth, I figured out that the following two commands were the culprit.

~/bin/calcurse

```
/usr/bin/calcurse -C ~/.config/calcurse -D ~/.local/share/calcurse -c /mnt/data/calendars/appointments $@
```

~/bin/calcurse-holidays

```
/usr/bin/calcurse -C ~/.config/calcurse -D ~/.local/share/calcurse -c /mnt/data/calendars/holidays $@
```

Each calendar requires its own note directory. If two calendars share the same note directory, the note directory gets wiped out.
