### ISSUE TITLE
Show weeks appointments in appointment pane

### ISSUE THREAD

**Issue by thepyguy** [lfos/calcurse#295]
I notice in the page there's a gif that shows appointments for multiple days in the appointments pane. Is there a setting I am missing or something? I would like to see at least 1 weeks of appointments in the appointment pane at a time. This is not really a bug more just a question how to obtain the functionality I've seen on the repository. I've searched and not found an answer to this.

Thank you

**Comment by lfos** [comment]
The setting is `general.multipledays`. It requires calcurse 4.5.0 or newer.

**Comment by thepyguy** [comment]
Thanks I am on an older version. Ubuntu LTS repos are behind. I tried to build from source but didnt work for some reason will keep trying.
