### ISSUE TITLE
Problems in popping events from Google Server to local calendar

### ISSUE THREAD

**Issue by lhpt** [lfos/calcurse#303]
Description:
I configured calcurse to synchronize my google calendar with my local calendar. Pushing new created events from the local calendar db to the google calendar works flawlessly but somehow getting already existing events from my google calendar somehow fails.

Reproduction:
Setting up google calendar synchronization according to https://www.calcurse.org/files/calcurse-caldav.html tutorial.

Expected Behavior:
Synchronization in both ways (Getting new events from server as well as pushing own events up)

Screenshots:
calcurse-caldav output and mentioned logfile
Command used: $calcurse-caldav --config ~/.config/calcurse/caldav/config --init two-way

![selected_20200624_1539_40](https://user-images.githubusercontent.com/37117877/85569690-0ca5c800-b633-11ea-8be9-1e4eb33f8630.png)
![selected_20200624_1544_57](https://user-images.githubusercontent.com/37117877/85569857-3101a480-b633-11ea-92c7-c3c6061c6811.png)

**Comment by lhca** [comment]
You have encountered a known problem. There is a patch available. See #274.

**Comment by lhpt** [comment]
Alright, must have overseen it sorry my bad

**Comment by lhpt** [comment]
jjj
