### ISSUE TITLE
Feature Request: A beeping reminder that recurs until user disables

### ISSUE THREAD

**Issue by clort81** [lfos/calcurse#305]
Need a beeping reminder that will repeat every few minutes until user disables it.

I have made a beep script using 'aplay' but i need calcurse to pop up a notification that user must respond to to stop the beep every 5 minutes.

Any ideas? Thanks!

**Comment by lfos** [comment]
What is the role of calcurse here? Can't the script show a message (e.g. using notify-send(1)) and stop alerting only when the user reacts to that notification?

**Comment by lfos** [comment]
Closing. Please feel free to reopen if there's anything we can implement in calcurse to support this.
