### ISSUE TITLE
Redesign the item deletion menu

### ISSUE THREAD

**Issue by lfos** [lfos/calcurse#308]
Currently, the following things happen when the `del-item` key binding is used on a calendar item:

- If `general.confirmdelete` is enabled, the deletion must be confirmed (`[y/n]`).
- If the item has a note, you choose whether you want to delete the item or just the note (`[i/n]`).
- If the item is recurring, you choose whether you want to delete all occurrences or just the selected occurrence (`[a/o]`).

This does not only mean that the sequence of key strokes to delete highly depends on the item properties but also requires up to four key strokes are required to delete an item (e.g. `dyia`). The range goes from 2-4 key strokes with `general.confirmdelete` enabled and from 1-3 key strokes with `general.confirmdelete` disabled.

Here is an alternative proposal. When deleting an appointment, the following message is displayed:
```
Delete (s)elected occurrence, (a)ll occurrences, or only the (n)ote?
```

This message is always the same (for all items) but options that are not available are omitted. For example, for a non-recurring item without a note, the message would become:
```
Delete (s)elected occurrence?
```

This new interface is consistent across all item types and always requires only two key strokes. The "Do you really want to delete this item?" message can be dropped since the second key stroke can be seen as a deletion confirmation. The only downside is that in one specific scenario (`general.confirmdelete` disabled, non-recurring item without a note), now two key strokes are required instead of one. However, the new menu has been chosen in a way such that the two keys to press in this situation (`ds`) are very close together by default.

Opinions?

**Comment by lfos** [comment]
@lhca The deletion menu inconsistency was brought up by a user. This is my first improvement proposal but I'd be interested to hear what you think and I'm open to discussing alternative solutions.

**Comment by lhca** [comment]
Looks like a definite improvement.
 
> Opinions?

The single key stroke deletion could easily be retained as follows. If the user must choose between several options, `general.confirmdelete` is ignored. If there is only one option (non-recurring item, no note), `general.confirmdelete` is taken into account.

**Comment by lfos** [comment]
> The single key stroke deletion could easily be retained as follows. If the user must choose between several options, `general.confirmdelete` is ignored. If there is only one option (non-recurring item, no note), `general.confirmdelete` is taken into account.

Great suggestion.

We should probably also at least add a warning to the compatibility section in the release notes that the menu has changed.
