### ISSUE TITLE
Hook execution and deadlocks

### ISSUE THREAD

**Issue by lhca** [lfos/calcurse#309]
Deadlocks in calcurse have occurred previously (#215) and have surfaced again (https://github.com/lfos/calcurse/issues/301#issuecomment-650541124).

#### Problem.

Load and save hooks are run much like external programs (editors, pagers). In interactive mode that means stopping the notify bar (the clock), clearing the terminal, and handing stdin, stdout and stderr over to the hook/external program.  Afterwards, the usual calcurse interface is restored.

This approach works well for external programs, the launch of which is always user-initiated, but not for hooks. Load and save operations (and with them, hooks) are not only run on demand (save/reload action), but also asynchronously by the periodic save thread and by the initial data load.

At the moment (calcurse v4.6.0) serious problems are caused by hooks when calcurse is configured for periodic save (`general.periodicsave > 0`), as proven by the following scenario.

1. Start calcurse interactively and set `general.periodicsave = 1`. This is not a requirement (as long as the value is positive), but serves to speed up proceedings. Exit calcurse.

2. Two (script) files must be present in the hooks directory: pre-load and post-save. The contents are not important and the files may even be empty. Make the pre-load file executable and, if not empty, make it exit with 0 (success) (again, not really required, but makes the following explanations simpler).

3. Start calcurse interactively and add an event (or appointment), but don't save to disk. This serves the purpose of triggering a run of post-save by the next periodic save.

4. Wait for the periodic save. When it occurs, the clock in the notify bar will stop running (periodic save is in a  deadlock, and the notify bar is not restarted). The main calcurse thread is still running and you can move between panels. But if you trigger an external program (help for example), calcurse enters the deadlock and must be killed.

#### Solution.

At present, if you use hooks, periodic save should be disabled (`general.periodicsave = 0`).

The complete explanation of the deadlock scenario is complicated, but the upshot is: hooks should not be run like external programs. Parts of the explanation are discussed in #215.

Hooks are not interactive programs and should not write to stdout/stderr, but log any messages to file (like the example hooks in contrib). In exceptional cases failure may be reported through exit values.

Since calcurse v4.4.0 load and save operations do not take possession of the terminal, but run quietly with results being reported internally by function return values. Similarly, hooks should be prevented from writing to stdout/stderr and run quietly "in the background".

I am very interested in opinions, objections, comments.

**Comment by TripleTrable** [comment]
I have the same problem except I have to trigger a redraw to the main thread  to show calendar etc again.

**Comment by lfos** [comment]
Thanks for the summary Lars. What's the proper solution here though? if the answer is "hooks are not interactive programs and should not write to stdout/stderr", shouldn't we at least absorb/suppress any output when the hooks are run?

**Comment by lhca** [comment]
That's what I have worked towards. A PR is on its way, not very comprehensive.
