### ISSUE TITLE
Syntax error in item date

### ISSUE THREAD

**Issue by toasthorse** [lfos/calcurse#324]
**Version information.**  calcurse 4.7.0

**Bug description.** After exporting the current data of the calendar to an .ical file, trying to read it with the -c flag results in the following error: 
`io.c: 543: Documents/calcurse.ical:1: syntax error in the item date`

**Reproduce.**
- launched calcurse, everything works.
- `calcurse --export > Documents/calcurse.ical`
- `calcurse -c Documents/calcurse.ical`
- error: `io.c: 543: Documents/calcurse.ical:1: syntax error in the item date`

**Expected Behavior.** calcurse starts with the data supplied in the file.

I synced the file onto my laptop and mistakenly imported it a few times too many and encountered this error when trying to read the file. However, even after deleting and recreating all the events that I previously had (so that each only appears once), the error still persists.

**Comment by lfos** [comment]
Hi toasthorse; thanks for the bug report! `--export` is used to export an item to the iCal format. `-c` is used to specify a calendar file in calcurse (not iCal) format. To import an iCal file, you can use `--import`. Does that solve your issue?

**Comment by toasthorse** [comment]
Thank you, I didn't know that those are two different formats!

Going through the man page, I saw that there are separate files for appointments, to-do items and notes. As I can only supply the appointments file with the `-c` option, is it correct that there is no way to also supply notes and to-do items as an argument?

My goal was to have a file (or more, whatever works) across both my computers which I can supply to calcurse to work on the most recent version of my calendar. The `--import` flag would not work as it would duplicate the data on every import. I suppose it's being considered already though, given there's a pull request for it.

**Comment by lfos** [comment]
You can supply `-D` to specify a directory to share between the machines (containing both `apts` and `todo`).

**Comment by toasthorse** [comment]
My bad, I'll read more carefully next time. Thank you!
