### ISSUE TITLE
The value of scope must be not None

### ISSUE THREAD

**Issue by diego-rapoport** [lfos/calcurse#327]
**Version information.**
4.7.0

**Bug description.** 
I can't even get the auth code. Already run with `--init keep-remote` and `--init two-way`.
Also tried to comment all of my other configs, but nevertheless still getting the same error. 
```
calcurse-caldav

Connecting to apidata.googleusercontent.com...
Traceback (most recent call last):
  File "/usr/bin/calcurse-caldav", line 728, in <module>
    cred = run_auth(authcode)
  File "/usr/bin/calcurse-caldav", line 210, in run_auth
    credentials = init_auth(client_id, client_secret, scope, redirect_uri, authcode)
  File "/usr/bin/calcurse-caldav", line 158, in init_auth
    oauth2_client = OAuth2WebServerFlow(client_id=client_id,
  File "/home/dinhego/.local/lib/python3.8/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/dinhego/.local/lib/python3.8/site-packages/oauth2client/client.py", line 1878, in __init__
    raise TypeError("The value of scope must not be None")
TypeError: The value of scope must not be None
```

**Config File for CalDav**
```
[General]
Hostname = apidata.googleusercontent.com
Path = /caldav/v2/myemail@gmail.com/events/
AuthMethod = oauth2
SyncFilter = cal,todo

DryRun = No
HTTPS = Yes
InsecureSSL = No
Binary = calcurse
Verbose = Yes

[Oauth2]
ClientID = [code].apps.googleusercontent.com
ClientSecret = [pass]
Scope = https://www.googleapis.com/auth/calendar
RedirectURI = http://127.0.0.1
```

**Comment by lfos** [comment]
The section name should be `OAuth2`, not `Oauth2` (uppercase `A`).

**Comment by diego-rapoport** [comment]
> The section name should be `OAuth2`, not `Oauth2` (uppercase `A`).

I **knew** it was something badly written, but couldn't find it. It worked!
Thanks

**Comment by lfos** [comment]
Glad that it worked for you. I think we should also improve on error reporting for typos; you're not the first one reporting an issue caused my misspelling a section or key name.

**Comment by twllnbrck** [comment]
Have the same issue on FreeBSD 12.2.

`% calcurse --version                                                                            
calcurse 4.5.1 -- text-based organizer`

py-httplib2 and py-oauth2client are installed via ports. Always get the 'The value of scope must not be None' error.

`[General]
Binary = calcurse
Hostname = apidata.googleusercontent.com
Path = /caldav/v2/mymail@gmail.com/events/
AuthMethod = oauth2
SyncFilter = cal,todo
DryRun = No
InsecureSSL = No
Verbose = Yes

[OAuth2]
ClientID = [clientid].apps.googleusercontent.com
ClientSecret =[clientsecret]
Scope = https://www.googleapis.com/auth/calendar
RedirectURI = http://127.0.0.1`
