### ISSUE TITLE
broken link.

### ISSUE THREAD

**Issue by remembertoremind** [lfos/calcurse#33]
Hi! :) I tried to access the readme file from http://calcurse.org/support/ and was directed here http://git.calcurse.org/calcurse.git/tree/contrib/caldav/README with the errormsg "bad gateway" :)

**Comment by remembertoremind** [comment]
I guess this is the right link :) 

https://github.com/lfos/calcurse/blob/master/contrib/caldav/README

**Comment by lfos** [comment]
The link should work again. There was an issue with our cgit setup that should be fixed now. Thanks for reporting!
