### ISSUE TITLE
Help installing package base64

### ISSUE THREAD

**Issue by super-eye** [lfos/calcurse#332]
Hi

I'm trying to sync calcurse to google calendar.
I made a requirements.txt file to download all the packages to a virtual enviroment.
When I do python3 -m pip install -r requirements.txt I get the following message: 
ERROR: Could not find a version that satisfies the requirement base64 (from versions: none)
ERROR: No matching distribution found for base64

This happens too if I try to install it alone.
Could anybody help me to install the base64 package please
?
:)

**Comment by ghaskari** [comment]
Use this instead

pip install pybase64

It's work for me

**Comment by dmit26** [comment]
Thanks! It really works
