### ISSUE TITLE
add .ics URL

### ISSUE THREAD

**Issue by jrejaud** [lfos/calcurse#334]
**Version information.** 
```
calcurse 4.7.0 -- text-based organizer

Copyright (c) 2004-2020 calcurse Development Team.
This is free software; see the source for copying conditions.
```

**Bug description.**
Cannot add a .ics URL (like in Google Calendar). I understand that you can import an ics file, but there is no way (to my knowledge) to point to an .ics resource at a URL and have calcurse periodically read from it and add/ remove changed calendar events

**Expected Behavior.**
A way to specify a URL to an .ics resouce

**Comment by wictory** [comment]
you could use [vdirsyncer](http://vdirsyncer.pimutils.org/en/stable/) to sync your url .ics to a vdir which you can import.

**Comment by jrejaud** [comment]
@wictory 

Unfortunately, it seems calcurse doesn't let you sync with two Google Calendars in the same session so I'll hold off on using it until that functionality is added since it's a must-have for me.

Thanks for the link though, this could be a useful tool.
