### ISSUE TITLE
Notes n N does not open in editor

### ISSUE THREAD

**Issue by cookEbox** [lfos/calcurse#341]
I've looked at the closed versions of similar bug reports so sorry if you feel you've already answered this.

When I press n or N on my notes in the TODO list calcurse window flashes but does not open a text editor.

in .bashrc 

export EDITOR=vim
export VISUAL=vim
export CALCURSE_EDITOR=vim

I reloaded calcurse and even restarted by computer but still no text editor. 

It does, however, work when I open clacurse from the terminal with VISUAL=vim calcurse.

I'm using calcurse 4.7.0 on urxvt v9.22 on an arch distro 

I saw on a previous query you asked to see the result of env, the three variables appear in the list (please let me know if you need more than this):

EDITOR=vim
VISUAL=vim
CALCURSE_EDITOR=vim

I know I could open from terminal with VISUAL=vim prefixed but I would like it to be tied to a hotkey.

Otherwise I really enjoy the program, Thank you!

P.S. I have only been using Linux distros for 7 months and this is my first arch build (so I know there is a good chance this is something I've done wrong not calcurse necessarily)

**Comment by lfos** [comment]
Can you confirm that running
```
export VISUAL=vim
calcurse
```
from the terminal does not work but
```
VISUAL=vim calcurse
```
does?

In case both work, your `export VISUAL=vim` in `.bashrc` likely doesn't get processed or gets overridden.

**Comment by cookEbox** [comment]
both work so this is an issue on my end.

Thanks for the help.
