### ISSUE TITLE
tries to use nano instead of vim

### ISSUE THREAD

**Issue by SwankyBarbecue4** [lfos/calcurse#344]
Hi,

Calcurse tries to open nano instead of nvim when I press `n` to create a new note. The screen flashes briefly, and I can catch a glimpse of `/usr/bin/nano: No such file or directory`. [I posted on reddit about my issue](https://www.reddit.com/r/linuxquestions/comments/kxp4ca/calcurse_uses_nano_instead_of_nvim/), but it was not much help.

How do I configure the environment variables to use nvim insead of nano?

Thanks!

**Comment by lfos** [comment]
Try
```
$ export CALCURSE_EDITOR=nvim
$ calcurse
```
or
```
$ export VISUAL=nvim
$ calcurse
```

If that works, you can move the variables to your `.bashrc` (or another shell config).

**Comment by SwankyBarbecue4** [comment]
Thanks for the reply!

I was able to fix the issue by changing a singe line in `~/.profile`

Thanks for your help! :)
