### ISSUE TITLE
Recurrence Exceptions

### ISSUE THREAD

**Issue by bin** [lfos/calcurse#345]
I would like to add exceptions to a recurring event.  For example, maybe I have a recurring appointment that is not happening due to a holiday.  Being able to delete a single instance of a recurring event would be sufficient.  Are there any plans to implement a feature of this sort?  What are the things that need changing for this to work?

**Comment by lfos** [comment]
Select the occurrence to delete and use the delete key binding.

**Comment by bin** [comment]
That did it, thanks.
