### ISSUE TITLE
How to run pre-load synchronously

### ISSUE THREAD

**Issue by thierrybo** [lfos/calcurse#349]
Hi,

I tried  calcurse/contrib/hooks/pre-load  without modifications to run calcurse-caldav before loading Calcurse. At first I believed it was not working because Calcurse loaded instantaneously and I did not get the new appointments,. 
Then when I quit I understood synchronization occured because Calcurse prompt me to merge changed data. A (R)eload confirm this. I get the new data.

However this is not the behavior I was expecting. I want calcurse loadind AFTER calcurse-caldav ending. How to achieve that? Is there a config parameter to change, or a change to do in pre-load script?

**Comment by lfos** [comment]
The sample pre-load hook runs calcurse-caldav in the background. Remove the `&` at the end of the subshell to make it blocking.

**Comment by thierrybo** [comment]
Thks
