### ISSUE TITLE
calcurse-caldav and radicale: what is path?

### ISSUE THREAD

**Issue by vikasrawal** [lfos/calcurse#354]
I am sorry but I am confused what path to use in the config file. My radicale installation serves the calendars on port 5232. I can access it over the browser. Am I supposed to give the full filesystem path to radicale collections in the calcurse-caldav config?

Why should the filesystem path be required?

**Comment by lfos** [comment]
Path is the URL component following the host name, it (usually) doesn't correspond to the full path in the filesystem of your server.

**Comment by lfos** [comment]
Path is the URL component following the host name, it (usually) doesn't correspond to the full path in the filesystem of your server.
