### ISSUE TITLE
calcurse-caldav deletes its own items

### ISSUE THREAD

**Issue by Andonome** [lfos/calcurse#356]
# Summary

When running calcurse-caldav to synchronize with efoundation's nextcloud, the first run pushes the new appointment up, the second run pulls it down and deletes the local version, and the third run deletes the remote version.

# Dots

My /caldav/config is [here](https://gitlab.com/andonome/dots/-/blob/new/skel/config/calcurse/caldav/config)

All hooks have been disabled for testing.

# Steps to replicate

1. Set up dot files with your nextcloud
2. Push to Nextcloud (maybe this is just efoundation?)
2. Make efoundation calendar entry
3. calcurse-caldav --init=keep-remote
4. Make appointment in calcurse
5. calcurse-caldav
6. Repeat step 5 three times.
7. Notice the appointment has been deleted from everywhere.

The attached file has the output of `calcurse-caldav --debug`.

[calcurse-log.txt](https://github.com/lfos/calcurse/files/6137851/calcurse-log.txt)

**Comment by next-mad-hatter** [comment]
If I'm not mistaken this is another manifestation of https://github.com/lfos/calcurse/issues/337 -- the calendar url in the attached log contains the "@" character, hence this (incorrect) behaviour.

**Comment by lfos** [comment]
Thanks for the report; this is something we should definitely address. I replied in #337.

**Comment by lfos** [comment]
I merged @next-mad-hatter's PR into `pu`.

@Andonome, could you please confirm that the issue no longer occurs when using `calcurse-caldav` from `pu`?

**Comment by Andonome** [comment]
@lfos 
Tested on calcurse 4.7.1 -- text-based organizer.

Everything working on Arch Linux and Arch Linux Arm.

**Comment by lfos** [comment]
Thanks!
