### ISSUE TITLE
Custom colors are reset on window redraw

### ISSUE THREAD

**Issue by cainishraq** [lfos/calcurse#368]
**Version information.** calcurse 4.7.1

**Bug description.** I use wpgtk/pywal to set the colors of my terminal to match my wallpaper. This works perfectly with calcurse initially when launched after running wpg or if wpg is run while calcurse is open. However, editing a note (opening nvim in the same terminal window) then exiting and going back to calcurse resets the colors to default. The same thing happens whenever I resize the window.

**Reproduce.** Making the window redraw everything causes the colors to reset. TABing through the windows and adding items preserves the colors as expected. My conf file is currently empty.

**Expected Behavior.** I would like the colors to be preserved from how they are at first.

**Comment by autoteelar** [comment]
wow ya

**Comment by autoteelar** [comment]
is this git dead or something? im scrolling through the issues and none of them have comments at all, :( i hope this gets resolved i really like calcurse and dont wanna use something else

**Comment by cainishraq** [comment]
I tested with a different terminal, st, and the colors stayed. This may just be an issue with Alacritty.

**Comment by autoteelar** [comment]
i use kitty and get the same problem

**Comment by autoteelar** [comment]
![image](https://user-images.githubusercontent.com/76745649/121518769-dc2f7900-c9be-11eb-841f-dd38342051ff.png)
also just confirmed it happens in xfce4-terminal, thats 3 confirmed terminals

**Comment by autoteelar** [comment]
![image](https://user-images.githubusercontent.com/76745649/121518956-1567e900-c9bf-11eb-91bd-5368dd3f9ba5.png)
also happens in sakura
