### ISSUE TITLE
Auto merge calcurse-caldav changes

### ISSUE THREAD

**Issue by ank0m** [lfos/calcurse#369]
Is there a way to have changes automatically merged as soon as other users of the same CalDAV calender made them?
Currently I only see a note with the ability to merge when I exit calcurse.

Cheers,
ank0m

**Comment by lfos** [comment]
You can run a cronjob (or something similar) that periodically runs the script. If you want new appointments to show up in calcurse without a manual reload, you can send `SIGUSR1` to a running calcurse instance.

**Comment by ank0m** [comment]
Hello lfos,

so by executing the calcurse-caldav.py I see that changes get synchronized, thats fine so far. Regarding sending SIGUSR1 to the running calcurse instance I have no clue how to do this.

#! /bin/bash
cpid=`pidof calcurse`
? -SIGUSR1 $cpid

What command has to be in front -SIGUSR1?

**Comment by ank0m** [comment]
OK, got it to work with this small script:

#!/bin/bash
.config/calcurse/caldav/calcurse-caldav.py && \
kill -USR1 `cat /home/fh/.local/share/calcurse/.calcurse.pid` > /dev/null 2>&1

Thanks Lukas for pointing me in the right direction.
