### ISSUE TITLE
UI Bar Showing Current Time Fails to Be Monochrome

### ISSUE THREAD

**Issue by MorganSeltzer000** [lfos/calcurse#373]
**Version information.** 
Calcurse 4.7.1-3-ga49a-dirty

**Bug description.**
UI bar showing current time fails to be monochrome when a color-enabled terminal selects the monochrome color setting.

**Reproduce.**
Start calcurse in color.
Go to the configuration page, and then the color configuration page.
Press KEY_GENERIC_CANCEL (by default the escape key) to select the monochrome option.
Everything is monochrome except the bottom UI bar showing the current time, which is cyan.

**Expected Behavior.**
The UI bar showing the current time should also be monochrome.

**Comment by MorganSeltzer000** [comment]
I plan to fix this later, I just wanted to write a bug report so the pull request for fixing this bug didn't come out of nowhere.

**Comment by lhca** [comment]
Cannot reproduce _in my environment_. Many specificities may be involved. I run `calcurse` on an old Linux installation in a PuTTY terminal window.

> Everything is monochrome except the bottom UI bar showing the current time, which is cyan.

What exactly is cyan? The whole bar or the current time?

**Comment by MorganSeltzer000** [comment]
After testing in current versions of fedora and debian, this occurs in the terminal (no GUI installed), and not in terminal emulators such as xterm or gnome-terminal. The entire notify bar is cyan, and after further testing I also found recurring events in the calendar are also cyan.
![Cyan_with_notheme](https://user-images.githubusercontent.com/63917142/119520705-23233a80-bd40-11eb-91cc-268f05471e2b.png)

**Comment by MorganSeltzer000** [comment]
This is not a calcurse issue, apparently for most terminals (non-GUI systems) the default for A_UNDERLINE is to apply a color instead of underlining, and A_UNDERLINE does nothing if ncurses specifically sets a color (such as when calcurses has a theme set).
