### ISSUE TITLE
Caldav sync over nextcloud not bringning any event

### ISSUE THREAD

**Issue by damarusama** [lfos/calcurse#38]
Seems like my setups works correctly, yet no event are pulled from the server.  I am not sure if I should have another more specific 'url' for my calendar, which is named personal...

Loading configuration from /home/ponnuki/.calcurse/caldav/config...
Connecting to myserver...
> REPORT /nc/remote.php/caldav/calendars/gef/
> Headers: {'Authorization': 'Basic, 'Content-Type': 'application/xml; charset=utf-8'}
> <?xml version="1.0" encoding="utf-8" ?><C:calendar-query xmlns:D="DAV:"                   xmlns:C="urn:ietf:params:xml:ns:caldav"><D:prop><D:getetag /></D:prop><C:filter><C:comp-filter name="VCALENDAR" /></C:filter></C:calendar-query>

< Headers: [('Date', 'Thu, 03 Aug 2017 09:44:54 GMT'), ('Server', 'Apache/2.2.32 (Unix) mod_python/3.5.0- Python/2.7.13 mod_ssl/2.2.32 OpenSSL/1.0.2k'), ('X-Powered-By', 'PHP/7.1.5'), ('Expires', 'Thu, 19 Nov 1981 08:52:00 GMT'), ('Cache-Control', 'no-store, no-cache, must-revalidate'), ('Pragma', 'no-cache'), ('X-XSS-Protection', '1; mode=block'), ('X-Content-Type-Options', 'nosniff'), ('X-Frame-Options', 'Sameorigin'), ('X-Robots-Tag', 'none'), ('X-Download-Options', 'noopen'), ('X-Permitted-Cross-Domain-Policies', 'none'), ('Content-Security-Policy', "default-src 'none';"), ('Vary', 'Brief,Prefer'), ('Set-Cookie', 'oc_sessionPassphrase=xxx; path=/nc; secure; HttpOnly'), ('Set-Cookie', 'nc_sameSiteCookielax=true; path=/nc; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax'), ('Set-Cookie', 'nc_sameSiteCookiestrict=true; path=/nc; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict'), ('Set-Cookie', 'xxx; path=/nc; secure; HttpOnly'), ('Set-Cookie', 'cookie_test=test; expires=Thu, 03-Aug-2017 10:44:55 GMT; Max-Age=3600'), ('Strict-Transport-Security', 'max-age=31536000'), ('Transfer-Encoding', 'chunked'), ('Content-Type', 'application/xml; charset=utf-8')]
< <?xml version="1.0"?>
< <d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/"/>

Saving synchronization database to /home/ponnuki/.calcurse/caldav/sync.db...
0 items imported, 0 items removed locally.
0 items exported, 0 items removed from the server.

**Comment by lfos** [comment]
It is hard to tell what is wrong without more information. It looks like the URL you are using is not the right one, though... Which software are you using on the server side.

**Comment by damarusama** [comment]
It's a nextcloud server

**Comment by lfos** [comment]
Any progress? Maybe try `/nc/remote.php/caldav/calendars/gef/personal` instead? I assume that `gef` is your remote user name?

**Comment by ellioseven** [comment]
I am getting the same issue, changing the URL from `.../remote.php/dav` to `.../remote.php/caldav/calendars/gef/personal` did not work for me.

**Comment by ellioseven** [comment]
When viewing the logs within next cloud, I can see the following:

```
Sabre\DAV\Exception\BadRequest: HTTP/1.1 400 A calendar-query REPORT on a calendar with a Depth: 0 is undefined. Set Depth to 1

    /var/www/html/3rdparty/sabre/dav/lib/CalDAV/Plugin.php - line 250: Sabre\CalDAV\Plugin->calendarQueryReport(Object(Sabre\CalDAV\Xml\Request\CalendarQueryReport))
    [internal function] Sabre\CalDAV\Plugin->report('{urn ietf param...', Object(Sabre\CalDAV\Xml\Request\CalendarQueryReport), 'calendars/admin...')
    /var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 718: Sabre\Event\EventEmitter->emit('report', Array)
    [internal function] Sabre\DAV\CorePlugin->httpReport(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method REPORT', Array)
    /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/html/apps/dav/lib/Server.php - line 253: Sabre\DAV\Server->exec()
    /var/www/html/apps/dav/appinfo/v2/remote.php - line 33: OCA\DAV\Server->exec()
    /var/www/html/remote.php - line 162: require_once('/var/www/html/a...')
    {main}
```

**Comment by ellioseven** [comment]
If I enter the the following config in `[CustomHeaders]`, I can successfully import from Nextcloud:

```
[CustomHeaders]
Depth: 1
```

Seems to be an issue with the [sabre/dav](https://github.com/fruux/sabre-dav/commit/ca91f5a)

**Comment by lfos** [comment]
Reminds me of a patch I wanted to merge a while ago. Should work with current master and without that custom header entry now. Thanks for reporting!
