### ISSUE TITLE
Events not showed but exported

### ISSUE THREAD

**Issue by mredigonda** [lfos/calcurse#39]
So, I tried to make some events like the following:

**From**: 00:00
**To**: 00:10 
**Description**: 00:10

Yes, with a "00:10" in the description too (it was by accident). Now I'm not able to see this event (so I can't delete it), but everytime I export this (in pcal format, for example), those events are showing.

I'm planning to make something like a "visualizer" for calcurse, but this ghosts events may break the functionality. It's not soooo important, because I can find a workaround for this (simple exporting, deleting those events, and importing, I guess), but it would be nice.

Also, I would like to congratulate you, it's some time now that I use this software, and it's great!

**Comment by lfos** [comment]
What is the output of `calcurse -G --filter-pattern='00:10'`?

**Comment by mredigonda** [comment]
```
calcurse: invalid option -- 'G'
Usage: calcurse [-g|-h|-v] [-an] [-t[num]] [-i<file>] [-x[format]]
                [-d <date>|<num>] [-s[date]] [-r[range]]
                [-c<file>] [-D<dir>] [-S<regex>] [--status]
                [--read-only]
Try 'calcurse -h' for more information.
calcurse: unrecognized option '--filter-pattern=00:10'
Usage: calcurse [-g|-h|-v] [-an] [-t[num]] [-i<file>] [-x[format]]
                [-d <date>|<num>] [-s[date]] [-r[range]]
                [-c<file>] [-D<dir>] [-S<regex>] [--status]
                [--read-only]
Try 'calcurse -h' for more information.
```

**Comment by lfos** [comment]
You seem to be using a quite old version of calcurse. I strongly recommed you to upgrade. Anyways, what is the output of `grep 00:10$ ~/.calcurse/apts`?

**Comment by mredigonda** [comment]
The output now is:
03/12/2018 @ 00:00 -> 03/12/2018 @ 00:00 |00:10

By the way, I tried to update before showing you that message, but from apt-get it doesn't seem to be possible.

**Comment by lfos** [comment]
Ok, seems like there was a bug with punctual appointments at 00:00 (having a description set to `00:10` was not related). Should be fixed in master, thanks for reporting!
