### ISSUE TITLE
ical-003.sh fails on s390x

### ISSUE THREAD

**Issue by nmeum** [lfos/calcurse#397]
**Version information.**

calcurse-4.7.1

**Bug description.** 

While upgrading the [Alpine Linux](https://alpinelinux.org) Edge calcurse package to the latest version (4.7.1) I noticed that the calcurse test suite fails with 4.7.1 on s390x, on all other architectures it passes successfully. Furthermore, it seems to have passed successfully on s390x with 4.6.0 in the past.

**Reproduce.**

s390x is a somewhat obscure architecture. The easiest way to reproduce this is probably setting up a qemu-s390x Alpine Edge chroot with binfmt_misc or using a qemu-system-s390x Alpine VM. In either case, one just needs to run `make && make check` to reproduce this issue.

**Expected Behavior.**

All tests should pass.

**Actual Behavior.**

All tests expect `ical-003.sh` pass:

```
$ cat test/test-suite.log
=========================================
   calcurse 4.7.1: test/test-suite.log
=========================================

# TOTAL: 77
# PASS:  76
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: ical-003.sh
=================

Running ./ical-003.sh... FAIL
FAIL ical-003.sh (exit status: 1)
```

More information:

```
calcurse-4.7.1/test$ ./ical-003.sh actual > /tmp/actual
calcurse-4.7.1/test$ ./ical-003.sh expected > /tmp/expected
calcurse-4.7.1/test$ diff -u /tmp/actual /tmp/expected
--- /tmp/actual
+++ /tmp/expected
@@ -210,12 +210,12 @@
  - ..:.. -> 00:00
 	First weekend in May
 First weekend in May is a two-day event!
-Repeating event, three years.
---
-Import: multi-day event changed to one-day event
-First weekend in May is a two-day event!
 Repeating appointment.
 The first weekend in May is a two-day event.
 Non-repeating event.
+--
+Import: multi-day event changed to one-day event
+First weekend in May is a two-day event!
+Repeating event, three years.
 --
 Import: multi-day event changed to one-day event
```

If you need further information to debug this, let me know. I will try to provide it.

**Comment by lhca** [comment]
Hmm, the star `*` is expanded by the shell. But anyway, according to the diff-output above, the actual and the expected files contain the same lines, but the last 12 lines of the actual file do not appear in the expected order.

The twelve lines are the contents of three note files created earlier by the test script in a temporary directory. The name of each file is the SHA-1 message digest of the file contents and should be the same on all systems.

The three file names in the temporary directory should be

```
80ca0905ba6d331277d5bea0ef7457bb33a33c88
84ccfba5d9a3bf774fe79dac348e8f95bf806714
8fb44c9925743a6f83fc18c72a248adcc0047d03
```

Try replacing

```
cat "$tmpdir/notes"/*
```

with

```
cat "$tmpdir/notes"/*; (cd "$tmpdir/notes"; echo * > /dev/tty)
```

to see the note file names before they are removed.

**Comment by lfos** [comment]
I just pushed 20b23cc to the pu branch as an attempt to fix this. Unfortunately, I do not have access to a big-endian system; I'd appreciate if somebody could build from pu and confirm the bug is fixed and `make check` is passing.

**Comment by nmeum** [comment]
Yep, can confirm that this has been fixed. This issue can be closed.
