### ISSUE TITLE
Double Date for November 7, 2021

### ISSUE THREAD

**Issue by HowiePepper** [lfos/calcurse#398]
I just ran into something I've never seen on calcurse before. When moving to the November 2021 calendar, I noticed November 7th is listed twice, once for Sunday (correct) and again for Monday (incorrect).

I'm running calcurse 4.5.0-2 amd64 on Xubuntu 20.04 LTS

I tried exiting and starting calcurse back up, with no change to this issue

![Calcurse_Screenshot_2021-10-15_11-50-14](https://user-images.githubusercontent.com/24995582/137516609-6c5c9f54-6c6f-4fed-951e-775b653851a7.png)
e.

**Comment by lhca** [comment]
Please see #233. The bug was fixed in _calcurse v4.5.1_.
