### ISSUE TITLE
"calcurse -t --filter-completed" does not show completed tasks from todo list

### ISSUE THREAD

**Issue by nowittynamesleft** [lfos/calcurse#407]
Using version 4.7.1, on both Arch Linux and MacOS.

After marking a todo item as completed in interactive mode using "!", the output of

calcurse -t --filter-completed 

is empty.

To reproduce, run calcurse in interactive mode, add a todo item to the todo list with any priority, highlight it, and press ! . It will hide the item. Exit calcurse, and then run "calcurse -t --filter-completed".

The expected behavior should have the completed todo item, that was highlighted and marked as such using ! , to be listed as output of the "calcurse -t --filter-completed" command.

This is under my assumption "!" marks a todo as completed. It doesn't say in the man page explicitly how to mark a todo item as done, but in the interactive mode, :help ! shows that it should flag the item as completed. However, that help text says that filtering by 0 priority should output completed tasks. Unfortunately, when running "calcurse -t --filter-priority 0", the program says "args.c: 784: invalid priority: 0". 

But even if that command was working, --filter-completed is still recognized as a valid flag but is failing to do the intended function, without errors.

**Comment by nowittynamesleft** [comment]
Also, although the ":help !" dialog says that the priority is replaced by X when you mark something as completed, the actual todo file (saved in the directory calcurse looks for tasks/notes/appointment data) has the priority changed to negative whatever the priority was. So, a priority 4 task "some task" would be listed as the following in the todo file:
[-4] some task

**Comment by lhca** [comment]
> Using version 4.7.1, on both Arch Linux and MacOS.
> 
> After marking a todo item as completed in interactive mode using "!", the output of
> 
> calcurse -t --filter-completed
> 
> is empty.

And that's not an error. Read the first two paragraphs of __Section 5. Filter Options__ in the man page very carefully. The commands

```
calcurse -t0
```
or
```
calcurse --todo=0
```
or
```
calcurse -Q --filter-type todo --filter-completed
```
accomplish what you want.

The _-t_ option is a query short-form and should not be combined with filter options. It is used to list open (=uncompleted) todos. The use of priority 0 is confusing: _-t3_ will list open todos with priority 3, and _-t0_ will list closed todos irrespective of priority. But priority 0 has nothing to do with the open/closed state of a todo. With _-t_ there is no way to list todos with priority 0 or closed todos with a particular priority.

> However, that help text says that filtering by 0 priority should output completed tasks. Unfortunately, when running "calcurse -t --filter-priority 0", the program says "args.c: 784: invalid priority: 0".

Indeed, priority 0 should be allowed. At present there is no way of only listing todos with priority 0.

**Comment by lhca** [comment]
Please note that the _calcurse_ documentation is in a sorry state. Only the man-page has been maintained, but could do with an update for the _-t_ option.

Neither the manual nor the built-in help texts are reliable, and in some respects they may be misleading.

By the way, once you have flagged a todo as closed (completed), there is no way of getting it back from the interactive interface.
