### ISSUE TITLE
Gmail setup

### ISSUE THREAD

**Issue by remembertoremind** [lfos/calcurse#41]
Hi :)

I found calcurse a few months ago and it's awesome. However, I would like to sync with my calendar at gmail. I followed the guide but surely I'm missing something obvious in the config since all my attempts have ended with this:

```
warning: Dry run; nothing is imported/exported. Add "DryRun = No" to the
warning: [General] section in the configuration file to enable synchronization.
Connecting to calendar.google.com...
error: The server at calendar.google.com replied with HTTP status code 302
error: (Moved Temporarily) while trying to access /calendar/
```

Could anybody direct me to a more expansive guide or just a sample to make it work with gmail?

Thanks.

**Comment by lfos** [comment]
You are probably using the wrong URL, [1] might be helpful.

[1] https://developers.google.com/google-apps/calendar/caldav/v2/guide

**Comment by remembertoremind** [comment]
Hi :) Thanks for the reply. However, I can't seem to figure this out. I'll keep messing around with it.

**Comment by lfos** [comment]
Maybe the script and the information given in #28 helps?

**Comment by lfos** [comment]
There now is a full guide here [1]. Note that it currently only works with the `pu` branch.

[1] https://github.com/lfos/calcurse/tree/pu/contrib/caldav#synchronization-with-google-calendar

**Comment by remembertoremind** [comment]
Great thanks! 👍 I'll look try it out :) Thank you for all your hard work.

**Comment by lfos** [comment]
Closing this for now. Please reopen if there are any remaining issues/concerns.
