### ISSUE TITLE
Failed to import object (VEVENT [22]: line break in summary)

### ISSUE THREAD

**Issue by mb720** [lfos/calcurse#414]
Hi and thanks a lot for calcurse!

I'm running calcurse 4.7.1 on Arch Linux and this is what I did so far:

1. Ran `calcurse-caldav --init=keep-remote` which completed without errors or warnings.
2. Then ran `calcurse-caldav --debug -v`. This produced some errors:

    ```
    Some items could not be imported.
    See /tmp/calcurse_log.MlcEjB for details.
    Failed to import object: 8a67c00c4010520b94574c05f56371cbd9c5fa86ba928c16ce2484a5e0c2f0d2 (/me/personal/78a86d2c-4104-40fa-8923-572a3da95b74.ics)
    ```

The file `/tmp/calcurse_log.MlcEjB` says:

>VEVENT [22]: line break in summary.

The corresponding file `78a86d2c-4104-40fa-8923-572a3da95b74.ics` (downloaded with vdirsyncer) looks like this:

    BEGIN:VCALENDAR
    VERSION:2.0
    PRODID:DAVx5/3.3.3-gplay ical4j/3.0.19 (com.samsung.android.calendar)
    BEGIN:VEVENT
    DTSTAMP:20201025T160611Z
    UID:78a86d2c-4104-40fa-8923-572a3da95b74
    SEQUENCE:1
    SUMMARY:\nT: Doctor's Appointment
    DTSTART;TZID=Europe/Vienna:20201102T134500
    DTEND;TZID=Europe/Vienna:20201102T144500
    BEGIN:VALARM
    TRIGGER:-PT1H
    ACTION:DISPLAY
    DESCRIPTION:\nT: Doctor's Appointment
    END:VALARM
    END:VEVENT
    BEGIN:VTIMEZONE
    TZID:Europe/Vienna
    X-LIC-LOCATION:Europe/Vienna
    BEGIN:DAYLIGHT
    TZOFFSETFROM:+0100
    TZOFFSETTO:+0200
    TZNAME:CEST
    DTSTART:19810329T020000
    RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
    END:DAYLIGHT
    BEGIN:STANDARD
    TZOFFSETFROM:+0200
    TZOFFSETTO:+0100
    TZNAME:CET
    DTSTART:19961027T030000
    RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
    END:STANDARD
    END:VTIMEZONE
    END:VCALENDAR

Is there a way to import the calendar with this entry as is?

**Comment by lhca** [comment]
Short answer: no.

The SUMMARY property of a VEVENT is used by calcurse as the one-line description of the appointment displayed in the appointments panel. This agrees well with the iCalendar standard RFC 5545 which says in section 3.8.1.12 (https://datatracker.ietf.org/doc/html/rfc5545#section-3.8.1.12):
```
Description:  This property is used in the "VEVENT", "VTODO", and
      "VJOURNAL" calendar components to capture a short, one-line
      summary about the activity or journal entry.
```
The value type (data type) of SUMMARY is TEXT, which allows multiple lines by encoding a newline as "\n". So in this respect the SUMMARY is OK. I wonder what Android calendar (?) puts in SUMMARY. It shouldn't allow newlines (in my opinion). In your example the same text is also used as DESCRIPTION, which may have several lines.

Do you control the contents of SUMMARY and DESCRIPTION in your calendar?

**Comment by mb720** [comment]
Thanks for pointing to the specification.

>Do you control the contents of SUMMARY and DESCRIPTION in your calendar?

I share this calendar with another person and could probably fix entries containing a newline from the Android calendar app. But that's not ideal, as you might imagine.

**Comment by lhca** [comment]
Thank you for the explanation of Android calendar behaviour. Indeed, it's the old story of adhering to standards or Big Tech's implementations. To be fair, the iCalendar specification is unclear on this point. I cited only part of the Description which in full is
```
Description:  This property is used in the "VEVENT", "VTODO", and
        "VJOURNAL" calendar components to capture a short, one-line
        summary about the activity or journal entry.

        This property is used in the "VALARM" calendar component to
        capture the subject of an EMAIL category of alarm.
```
The description is not normative (I believe) unlike the "Format Definition", which follows and which has no mention of restrictions on TEXT.

Compare this with the property STATUS (https://datatracker.ietf.org/doc/html/rfc5545#section-3.8.1.11) which also has value type TEXT, but curtailed by the following Format Definition.

So there is an argument for allowing newlines in SUMMARY. Or for pointing out the inconsistency and have the iCalendar standard modified. I have tried the latter in other cases, but iCalendar has been around for much too long for that to succeed and have in impact.

I am inclined to do as you suggest and have calcurse remove any newline in SUMMARY.

**Comment by lhca** [comment]
I just mailed a patch to @lfos that replaces any newline in SUMMARY with a blank.

**Comment by lfos** [comment]
@lhca I did not receive an email from you. Could you please retry (or file a PR here)?

**Comment by lhca** [comment]
On Sun, Mar 13, 2022 at 08:25:39AM -0700, Lukas Fleischer wrote:
>    ***@***.*** I did not receive an email from you. Could you please retry
>    (or file a PR here)?

Sorry about that. I had prepared the patch email, but forgot to send it. I have
sent it now to ***@***.***

Lars

**Comment by lfos** [comment]
Fix merged, closing. Please reopen if issue persists. Thanks for reporting, Matthias, and thanks for investigating and fixing, Lars!
