### ISSUE TITLE
Custom colors

### ISSUE THREAD

**Issue by UgoTurner** [lfos/calcurse#42]
Hi, 

I use Calcurse and everything seems to work well for me, you did a great job !
I just wonder if custom color themes are supported in the current version ? If not, is it planned to be implemented (or just add extra colors in the configuration panel) ?

Thanks !

**Comment by lfos** [comment]
Depends on what you mean. In the configuration menu, you can set custom foreground and background colors. Is that what you are looking for? Or are you talking about adding more fine-grained color settings?

**Comment by lfos** [comment]
No reply... Please reopen and provide more details if the issue is not fixed.

**Comment by mb720** [comment]
I assume OP was interested (as I am) in using more colors than those available in the color settings, by using a hex value like `#5B1F23` in `.config/calcurse/conf`.

Judging from [the code](https://github.com/lfos/calcurse/blob/master/src/config.c#L183), this seems not currently possible (but there's a another color available which is not among the choices in the color settings: white).

**Comment by lfos** [comment]
That's correct. Patches to make the color config more flexible are very welcome, though!

**Comment by pk0dev** [comment]
Hey all, can we customize the colors with the current version?

colors for each elements like date, appointment, todo, notify, etc..
