### ISSUE TITLE
Feature Request: Open notes with mdless

### ISSUE THREAD

**Issue by atlaskerr** [lfos/calcurse#43]
Being able to view the note of an item's TODO list with mdless would really take the notes features up a notch.
Maybe it could open up in a subscreen like when you expand the name of a TODO item?
Thoughts?

**Comment by lfos** [comment]
What happens if you run `PAGER=mdless calcurse` and then use `>` to view a note? Is that what you want?

**Comment by atlaskerr** [comment]
I get a "No Input" error

**Comment by lfos** [comment]
I do not use mdless, so this is just a guess: It looks like mdless invokes `$PAGER` which might fail if the default pager is mdless itself. Sounds like something that should be addressed in mdless, I guess... However, as a workaround, I added support for a calcurse-specific pager variable to the `pu`  branch. So you could checkout `pu`, build and install calcurse from there and try `CALCURSE_PAGER=$(which mdless) calcurse` instead.

**Comment by lfos** [comment]
Status? The `CALCURSE_PAGER` feature has been merged into `master`.

**Comment by lfos** [comment]
Closing this for now. Please reopen if you cannot make it work with `CALCURSE_PAGER`.
