### ISSUE TITLE
Weekly view displaying boxes instead of lines.

### ISSUE THREAD

**Issue by aisneto** [lfos/calcurse#441]
The slices are presented as empty boxes in the weekly view. I'm not sure if this is intended, as slices within the weekly view are presented as lines in the official manual (https://calcurse.org/files/manual.html), not boxes. Screenshots from other users also seems to suggest that this is a bug in my system.

![Screenshot_20220915_122601](https://user-images.githubusercontent.com/105523584/190444908-00b9b7a4-840b-4a50-b4a2-640a029f7eb0.png)
My currently weekly view.

![Screenshot_20220915_122638](https://user-images.githubusercontent.com/105523584/190444965-303064ea-a003-4102-8c51-4905feb5d712.png)
Suggested format by the official manual.

![Screenshot_20220915_122835](https://user-images.githubusercontent.com/105523584/190445040-108edc6c-1602-4517-84a9-a090cdc94a29.png)
Another user's weekly view, per the official manual (this screenshot refers to an older version).

I'm running calcurse 4.8.0 built from source, in Debian 11.

**Comment by lfos** [comment]
Fixed, thank you!
