### ISSUE TITLE
Change editor type

### ISSUE THREAD

**Issue by 1stdevfriend** [lfos/calcurse#442]
It's not a bug report but i just want to know if I can change edit note editor from
**vi** to **nvim**

**Comment by public-rant** [comment]
Does it work if you `export PAGER=nvim`?

**Comment by lfos** [comment]
You can set the editor via `EDITOR` or `VISUAL` environment variables or, alternatively, `CALCURSE_EDITOR` if you'd like to configure a different editor for just calcurse.
