### ISSUE TITLE
[Feature request] Recurring birthdays

### ISSUE THREAD

**Issue by shoddysheep** [lfos/calcurse#444]
Hello there :)

I've recently jumped to Calcurse and was wondering if it would be possible to implement a feature of sorts where you only have to input a person's birthday once, and then it will apply it automatically next year, so you don't have to sit and do it over and over again.

Cheers.

**Comment by BurnyBoi** [comment]
Just create a yearly recurring event like any other event. Already in calcurse and I do this for birthdays

**Comment by lfos** [comment]
Marking as resolved; let me know if you have any feature request that isn't already covered with yearly recurring events.
