### ISSUE TITLE
All day events are exported as zero duration events

### ISSUE THREAD

**Issue by hiqua** [lfos/calcurse#46]
I export my calcurse calendar to the ical format using `calcurse -x`. I then import it into the Android calendar. The problem is that what are called "all-day event"s in calcurse are just events occurring at 00:00 in Android, so I don't see them anymore after 00:01.

When looking at the ical file exported by calcurse, it appears that there is no DTEND field for these events. This is the correct behaviour for events that do not take time according to RFC 2445 ([cf Recommended pratices, 2](https://tools.ietf.org/html/rfc2445#page-140)).
For events that actually take the whole day, DTEND should be specified as DTSTART+1 day (or +n days depending on how many days it lasts), since DTEND specificies the non-inclusive ending time.

calcurse already supports events with only a starting date (just fill the starting date and leave the ending date empty). I think it would be better if an all-day event really had a duration of 24h.

Overall I'm not sure whether calcurse's behaviour is wrong per se, but always writing a DTEND for all day events would remove the ambiguity.

Related: it would be nice to be able to create all-day events spanning several days; for now, it's only possible to specify a duration if a precise time has been chosen.

**Comment by lfos** [comment]
See PR #60 for a related issue -- iCloud does not seem to like events without `DTEND` at all. So we should try to improve the way `DTEND` is exported for all-day events and for punctual appointments (maybe add a configurable workaround specifically for iCloud if we agree that not specifying `DTEND` for punctual appointments is the right thing to do)...

**Comment by hiqua** [comment]
I just realized that even though the lack of DTEND field makes calcurse differ from what Android expects, the real reason why all day events are not considered as such in Android is the difference in the DTSTART field. calcurse exports these fields as:
`DTSTART:20171001`
while it actually works when I change this field to this format (which is the one used when exporting from Android):
`DTSTART;VALUE=DATE:20171001`

So this is actually a bug in the app I use to import the calcurse calendars (ICSDroid), even though it would work correctly, were calcurse to export using the explicit format with the VALUE field.

**Comment by lfos** [comment]
Should be fixed by now. Please reopen if the issue persists.
