### ISSUE TITLE
[Feature Request] Calcurse-caldav external password support

### ISSUE THREAD

**Issue by refacto** [lfos/calcurse#48]
I really like the functionality of calcurse-caldav, the only problem I have is that I don't like storing my password in a plain text file.
What I'm requesting for is that it should be possible to get the password for calcurse-caldav via external command, so that it'd be possible to issue something like 'pass ls calendar'. That way, passwords aren't stored in an unencrypted fashion.

**Comment by lfos** [comment]
You can now set the password using the `CALCURSE_CALDAV_PASSWORD` environment variable; see 9be2c10 (calcurse-caldav: Read password from env variable, 2017-11-10) for details.
