### ISSUE TITLE
Question: Is there a way to use other calendars?

### ISSUE THREAD

**Issue by xemadp** [lfos/calcurse#486]
Is there a way to use other calendars ( apart from changing the start day of the week ), where month names and day names are set accordingly? e.g : Persian(Jalali) Calendar.

**Comment by nimaaskarian** [comment]
Hey. I know I'm a bit late to the party here.
but I made some [patches that uses changes calcurse so it'd use Jalali calendar](https://github.com/nimaaskarian/calcurse-jalali). I would be happy if someone else used them too!

**Comment by xemadp** [comment]
Hey there. That's a nice patch! I'll Tried it out and It works! thanks.

**Comment by nimaaskarian** [comment]
Hey @xemadp. I just added two other patches that makes each calendar views (monthly and weekly) jalali.
