### ISSUE TITLE
[Bug] Atempting to edit the color causes crash

### ISSUE THREAD

**Issue by retiform** [lfos/calcurse#52]
when the space key is pressed the program crashes resulting in the bug: Segmentation fault (core dumped)

System: Manjaro i3; installed from manjaro packages using pacman

**Comment by retiform** [comment]
This is probably the same as this bug: https://bugs.archlinux.org/task/56079?project=5&cat%5B0%5D=33&string=calcurse

**Comment by retiform** [comment]
any way to manually edit this?

**Comment by NathanRVance** [comment]
Can confirm on Arch, though this doesn't seem to be a calcurse problem - compiling from scratch fixes the issue.

**Comment by watersalesman** [comment]
I can also confirm that this happens on Arch but not on Fedora.

**Comment by lfos** [comment]
Dupe of issue #31 and #51.

This has fixed by commit 5722d2e a while ago (Fix segmentation fault when changing colors, 2017-07-28).
