### ISSUE TITLE
?  calcurse/scripts/Makefile.am  

### ISSUE THREAD

**Issue by glsmaxx2015** [lfos/calcurse#53]
Says it has 20 lines but are only 15.  Almost 1/2 of those are spaces? Just Wondering..

I also noticed that the script   calcurse/scripts/calcurse-upgrade.sh.in  has the suffix .in after it. I was wondering what that was for. I probably just have never seen it therefore haven\t the knowledge to understand.

Thanks A Bunch
glsmaxx2015

**Comment by lfos** [comment]
5/20 is 1/4, not 1/2. And yes, there are blank lines for optical separation.

`calcurse-upgrade` is generated from `calcurse-upgrade.sh.in` (replacement of a placeholder), thus the suffix.

Not sure what this bug report is about... :)
