### ISSUE TITLE
sync.db doesn't get created

### ISSUE THREAD

**Issue by pasau** [lfos/calcurse#54]
`calcurse-caldav --init=two-way`
Connecting to xxx.xxx.xxx.xxx:5232...
Saving synchronization database to /home/sauriol/.calcurse/caldav/sync.db...
0 items imported, 0 items removed locally.
0 items exported, 0 items removed from the server.

`Connecting to xxx.xxx.xxx.xxx:5232...`
Loading synchronization database from /home/sauriol/.calcurse/caldav/sync.db...
error: Sync database not found or empty. Please initialize the database first.
error: Supported initialization modes are:
error:   --init=keep-remote Remove all local calcurse items
error:   --init=keep-local  Remove all remote objects
error:   --init=two-way     Copy local items to the server and vice versa

`cat /home/sauriol/.calcurse/caldav/config`
[General]
Binary = calcurse
Hostname = xxx.xxx.xxx.xxx:5232
Path = user1/759b6094-d263-b2d5-ca2f-f45623adda3e/
InsecureSSL = Yes
DryRun = No
Verbose = Yes

[Auth]
Username = user1
Password = qwer

--------
im running a radicale caldav server

**Comment by watersalesman** [comment]
If there are no events to sync, the database will not initialize. Try adding an event locally and running it again.

**Comment by pasau** [comment]
i think i tried that, but didn't work either. Then i ran calcurse-upgrade, tried again and it worked
