### ISSUE TITLE
How do I setup CalDAV synchronization?

### ISSUE THREAD

**Issue by hubitor** [lfos/calcurse#58]
I want to setup CalDAV for synchronization with my phone but the README file with the instructions seems to be empty:
[http://git.calcurse.org/calcurse.git/tree/contrib/caldav/README](url)
I see only:
"Path not found"

**Comment by lfos** [comment]
The document moved [1]. Where did you find that link?

[1] http://git.calcurse.org/calcurse.git/tree/contrib/caldav/README.md

**Comment by watersalesman** [comment]
There are two links to the old README at http://calcurse.org/support/

**Comment by lfos** [comment]
Fixed those links. Thanks!
