### ISSUE TITLE
Feature request (?): Multiple CalDAV calendars

### ISSUE THREAD

**Issue by mrossinek** [lfos/calcurse#59]
Hi!

I successfully managed to synchronize my calcurse installation with my private nextcloud server.
Now I am wondering, if it is possible to sync more than one calendar with the same calcurse profile.. So far, I can only sync the one calendar specified within the Path of my calcurse-caldav config file.

I'd be happy to hear any tipps or a possible implementation of this feature.

Cheers!

**Comment by lfos** [comment]
You can use different configuration files and pass them to `calcurse-caldav` using the `--config` command line option, see issue #14 for more information... Does that solve your issue?

**Comment by mrossinek** [comment]
It solves it partially I guess.
I am able to also specify separate sync database files using the `--syncdb` command line option.
However, whenever initializing the sync of one or the other calendar all items get deleted locally..
A possible solution would be to add another option to initialize each synchronisation. I.e. keep both

However I guess this only becomes feasible once calcurse may support several calendars because as of now this would sync all items into each of the calendars.

**Comment by lfos** [comment]
You can use `--init=keep-local` if you want to do a one-way import from the server. Syncing with two different calendars (different data directories and different sync DBs) should work perfectly fine right now. You only cannot access them at the same time (i.e. using the same running instance) with `calcurse`.

**Comment by mrossinek** [comment]
Okay thanks for clarifying!
I will close this issue then.
