### ISSUE TITLE
Google caldav issue

### ISSUE THREAD

**Issue by shaggytwodope** [lfos/calcurse#62]
Hello, I've noticed a new feature to sync google calendar with a recent update. However I'm running into an error and unsure if I've configured anything incorrectly at this point.

I've created a config file in `~/.calcurse/caldav` as mentioned on the [readme](https://github.com/lfos/calcurse/blob/master/contrib/caldav/README.md). As well as setup (to best of my knowledge) the clientid/clientsecret  for the OAuth2 stuff.

My config:
```
[General]
Hostname = apidata.googleusercontent.com
Path = /caldav/v2/twodopeshaggy@gmail.com/events/
AuthMethod = oauth2

InsecureSSL = No
DryRun = No
Verbose = Yes


[OAuth2]
ClientID = xxxxxxx
ClientSecret =  xxxxxx
Scope = https://www.googleapis.com/auth/calendar
RedirectURI = http://127.0.0.1

```

I then run the command `calcurse-caldav --init keep-remote`

It produces this error:

```
calcurse-caldav --init keep-remote                                                     1 ＃
Connecting to apidata.googleusercontent.com...
Traceback (most recent call last):
  File "/bin/calcurse-caldav", line 604, in <module>
    cred = run_auth(authcode)
  File "/bin/calcurse-caldav", line 157, in run_auth
    credentials = init_auth(client_id, client_secret, scope, redirect_uri, authcode)
  File "/bin/calcurse-caldav", line 105, in init_auth
    oauth2_client = OAuth2WebServerFlow(client_id=client_id,
NameError: name 'OAuth2WebServerFlow' is not defined

``` 

Any help would be greatly appreciated.

**Comment by watersalesman** [comment]
Did you install oauth2client? If not, this can done by running `pip3 install --user oauth2client`

**Comment by shaggytwodope** [comment]
@watersalesman that was exactly my issue thank you so much.

For future reference any arch users should install `python-oauth2client`. I'll open a report to add to optional depends list.
