### ISSUE TITLE
Making Doc Files Fails on Some Distros

### ISSUE THREAD

**Issue by watersalesman** [lfos/calcurse#65]
Compiling from source works fine on Arch Linux, but when I try on Fedora 26, Fedora 27, or OpenSUSE Tumbleweed, I run the following: 
```
./autogen.sh
./configure
make
```
and receive the following error when making docs:
```
...
make[2]: Leaving directory '/home/iismu/build/calcurse/contrib/caldav'
Making all in doc
make[2]: Entering directory '/home/iismu/build/calcurse/doc'
make[2]: *** No rule to make target 'calcurse.1', needed by 'all-am'.  Stop.
make[2]: Leaving directory '/home/iismu/build/calcurse/doc'
make[1]: *** [Makefile:387: all-recursive] Error 1
make[1]: Leaving directory '/home/iismu/build/calcurse'
make: *** [Makefile:328: all] Error 2
```

I can provide more information/output if you need it.

**Comment by lfos** [comment]
Definitely need more information (full `configure` and `make` output would be a good start)...

**Comment by watersalesman** [comment]
Here is the full output for ./autogen.sh, ./configure, and make.
https://gist.github.com/watersalesman/6eb9b7287d4df4b18947b17af05cc5c0

**Comment by lfos** [comment]
It seems like you don't have AsciiDoc installed, which is required to build the documentation and man page.

**Comment by watersalesman** [comment]
Yup, that was it! It might be worth adding some of these build dependencies to the README.

**Comment by lfos** [comment]
Sounds like a good idea to me -- patches welcome! :)

**Comment by watersalesman** [comment]
I can work on that. Should I only include the generalized dependencies, or installation instructions for specific distros? and if the latter, which ones? I figure that Arch, Ubuntu, and Fedora should be included at least if we go that route.

**Comment by lfos** [comment]
I think including build dependencies only is fine.

**Comment by lfos** [comment]
Build dependencies are now documented; see commit cf90f5f (Document build dependencies, 2017-11-10) for details. Closing...
