### ISSUE TITLE
"please report the following bug"

### ISSUE THREAD

**Issue by pasau** [lfos/calcurse#69]
I got the message, and then this bug:

config.c: 589: configuration variable unknown: "appearance.headingpos"

when running calcurse. version 4.2.2

**Comment by lfos** [comment]
Did you run 4.3.0 and then downgrade to 4.2.2 somehow?

**Comment by lfos** [comment]
Assuming that the answer to my question is "yes", I will close this for now...

**Comment by pasau** [comment]
yes
