### ISSUE TITLE
[EXPIRED] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [lfos/calcurse#71]
Dear Mr. Fleischer,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by lfos** [comment]
I do not have access to a Windows system, so no, I unfortunately can't. I think your only option as of now is to setup a Cygwin environment with a compiler and compile it yourself, until somebody steps up and starts providing binaries...
