### ISSUE TITLE
Prompt in calcurse-caldav sync.db

### ISSUE THREAD

**Issue by andreasbaumann** [lfos/calcurse#73]
When synchronizing with calcurse-caldav I get an almost correct database, just one line
is weird:

```
Some items could not be imported, see log file? [y/n]
```

I tested with Verbose and Debug flags, it doesn't seem to make a difference.

**Comment by andreasbaumann** [comment]
aha. Now when I call calcurse-caldav the second time, I get: 

```
Loading synchronization database from /home/abaumann/.calcurse/caldav/sync.db...
Traceback (most recent call last):
  File "/bin/calcurse-caldav", line 645, in <module>
    syncdb = get_syncdb(syncdbfn)
  File "/bin/calcurse-caldav", line 282, in get_syncdb
    href, etag, objhash = line.rstrip().split(' ')
ValueError: not enough values to unpack (expected 3, got 2)
```

checking then sync.db I see:

```
personal/0a377a45-d694-440b-ac24-5b7e02af88d1.1500807026587.ics 4738fac5e17df79fb8763c095711ba1e e367ca8a694f0e31274731673b65cc72f9d13d53
personal/0c7d4475-3323-4a90-9db1-7c7eecc671ed.1470391123949.ics 7e46e29b18c334d6f0f7626e8fcd280e 
personal/11fb3770-3f94-43ff-9ace-cb163920dc77.1461575613586.ics 323939705193632676816d0e560f5e69 7f649a97a0e1ea8dd3908bcb1a46b2ca7fe589f9
```

So instead of setting the second hash it prompted the message above.

Sadly I don't know (yet) which caldav item causes the effect.

**Comment by andreasbaumann** [comment]
Mailing list: http://lists.calcurse.org/bugs/msg00162.html

**Comment by andreasbaumann** [comment]
So I see this is a message in calcurse itself:

```
io.c:               _("Some items could not be imported, see log file?");
```
when some items could not be imported.

**Comment by andreasbaumann** [comment]
So the message is a follow up error of the sync.db not having this last hash?
The question would be, what is causing that..

**Comment by andreasbaumann** [comment]
```
curl -u 'user:xx' -k -v 'https://somwhere.com/remote.php/caldav/calendars/user/personal/0c7d4475-3323-4a90-9db1-7c7eecc671ed.1470391123949.ics'
```

returns:

```
< HTTP/1.1 200 OK
< Date: Thu, 16 Nov 2017 11:29:14 GMT
< Server: Apache/2.4.29 (Unix) OpenSSL/1.1.0g PHP/7.1.11
< X-Powered-By: PHP/7.1.11
< Set-Cookie: xxxx path=/; HttpOnly
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate
< Pragma: no-cache
< Set-Cookie: oc_sessionPassphrase=xxx; path=/; secure; HttpOnly
< Content-Security-Policy: default-src 'none';
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: Sameorigin
< X-Robots-Tag: none
< X-Download-Options: noopen
< X-Permitted-Cross-Domain-Policies: none
< Set-Cookie: xxx; path=/; secure; HttpOnly
< Set-Cookie: cookie_test=test; expires=Thu, 16-Nov-2017 12:29:18 GMT; Max-Age=3600
< X-Sabre-Version: 3.0.9
< Last-Modified: Fri, 05 Aug 2016 09:58:45 GMT
< ETag: "7e46e29b18c334d6f0f7626e8fcd280e"
< Content-Length: 508
< Content-Type: text/calendar; charset=utf-8; component=vevent
< 
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//dmfs.org//mimedir.icalendar//EN
BEGIN:VEVENT
DTSTART;VALUE=DATE:20160615
TRANSP:OPAQUE
STATUS:CONFIRMED
DTEND;VALUE=DATE:20160616
LAST-MODIFIED:20160805T095843Z
DTSTAMP:20160805T095843Z
CREATED:20160805T095843Z
UID:0c7d4475-3323-4a90-9db1-7c7eecc671ed.1470391123949
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT10M
ACTION:DISPLAY
DESCRIPTION:Default Event Notification
X-WR-ALARMUID:d0aec9c9-785c-4544-a82f-bd8bd2b82ea3
END:VALARM
END:VEVENT
END:VCALENDAR
```

and a debug log of the initial database sync:

[debug.log](https://github.com/lfos/calcurse/files/1478347/debug.log)

**Comment by lfos** [comment]
It is the other way round: The iCal file does not contain any `SUMMARY` field which calcurse uses as a description for the imported item, thus the import fails. As a result of the failed import, the synchronization database is broken.

Two things we should definitely improve:

1. Not show this prompt on import errors. Continue with the next item instead and make calcurse-caldav display a warning (saying that not all items were imported).
2. Do not break the sync DB if any import does wrong. Skip the item instead.

**Comment by lfos** [comment]
The debug log you pasted above contains your full authentication details (including the Base64-encoded password). I removed the link but I strongly recommend you to change your password if you do not want anybody to access your calendars.

**Comment by andreasbaumann** [comment]
Thanks, I thought I had removed them all.. o well. Not a very important password. :-)
On the othe rhand, debug logs should never contain credentials or personal data (the
script/program should make sure).

**Comment by lfos** [comment]
Well, the debug log actually contains personal data only (calendar data and server communication); making sure it doesn't means we would not be able to print anything at all... :)

**Comment by andreasbaumann** [comment]
Good point :-)
Ok, it boils down to "Think first, then publish to Github." ;-)

**Comment by lfos** [comment]
Pushed two commits to ignore import failures. Closing this... :)

**Comment by peterski007** [comment]
I resolved the issue by creating a NEW Google Calendar. Upon running calcurse-caldav all
my existing apts from calcurse were synchronized/pushed up to the new calendar and after
that, subsequent calcurse-caldav invocations just work!

As a relevant side note: crontab requires initialization of the users environment (.bash_profile) so that the Python3 bin folder is in the path
otherwise defaults to Python 2.6 which does not have the required ‘httplib2’ module installed using ‘pip3 install httplib2’ required by oauth2 authentication.

**Comment by peterski007** [comment]
I resolved the issue by creating a NEW Google Calendar. Upon running calcurse-caldav all my existing apts from calcurse were synchronized/pushed up to the new calendar and after that, subsequent calcurse-caldav invocations just work!

As a relevant side note: crontab requires initialization of the users environment (.bash_profile) so that the Python3 bin folder is in the path otherwise defaults to Python 2.6 which does not have the required ‘httplib2’ module installed using ‘pip3 install httplib2’ required by oauth2 authentication.
