### ISSUE TITLE
Notification daemon

### ISSUE THREAD

**Issue by ralpheeee88** [lfos/calcurse#75]
What's the best way to have notifications show up on pc with dunst or any other notification daemon...

**Comment by lfos** [comment]
I am not sure I understand your question. Just enable the notification daemon and configure the notification command?

**Comment by ralpheeee88** [comment]
@lfos with a Google search I found

```
notification.command=calcurse --next | xargs -0 notify-send "Appointment"
```

Am wondering if there is a more elegant way,  and or  to have the actual appointment title displayed...

**Comment by lfos** [comment]
Unfortunately, there currently isn't a "more elegant" way. The command you used should actually display the appointment title, though?

**Comment by deepaknegilachu** [comment]
> @lfos with a Google search I found
> 
> ```
> notification.command=calcurse --next | xargs -0 notify-send "Appointment"
> ```
> 
> Am wondering if there is a more elegant way, and or to have the actual appointment title displayed...

I have this.
notification.command=notify-send "calcurse" "$(calcurse -n)" && aplay ~/.local/share/sounds/pomo.wav >/dev/null 2>&1
