### ISSUE TITLE
how to debug?

### ISSUE THREAD

**Issue by craftyguy** [lfos/calcurse#76]
I am getting random hangs (e.g. when hitting R to reload) and seg faults, and I would like to know how I can help debug these things. Since it's an ncurses app, runnning it in gdb is very messy and hard to use since it prints all over gdb's output. Do you have any suggestions?

**Comment by lfos** [comment]
Are you using the most recent version (i.e. 4.3.0 or even a development snapshot)? Usually, when calcurse crashes, it should be no problem to obtain a backtrace via gdb. If you want to do interactive debugging, the tips in [1] might be helpful, especially the `Separating the Input/Output` section.

[1] http://dirac.org/linux/gdb/07-Debugging_Ncurses_Programs.php

**Comment by craftyguy** [comment]
Thanks for the help. I've been able to reproduce the issue but there's nothing useful in gdb. I'll continue to try to get something useful before filing an issue.
