### ISSUE TITLE
[Feature Request] Projection of appointments.

### ISSUE THREAD

**Issue by aThorp96** [lfos/calcurse#77]
I would love it if calcurse showed me a projection upcoming appointments. I like to prepare for them a few days in advance and if I don't have anything that day I think it would be nice if I didni't have to go a few days forward to see what I have going on.  This is a great program, and I use it every day, this feature would make it a more friendly I think

**Comment by holalluis** [comment]
but you can write:
`calcurse -r10`

to see the appointments for the next 10 days

**Comment by fmv1992** [comment]
that is correct, you can

but to be honest I would also like to enable this feature in the interactive mode

**Comment by aThorp96** [comment]
One way this could be displayed could be a large calandar view with the first few words of the first few appointments that day. This could be instead of or with a queue of appointments inside your TODO list.

**Comment by Ierezell** [comment]
Maybe have a look here : #152 
It's a good improvement to see in advance what you will have in the n next days

**Comment by lfos** [comment]
See issue #152.
