### ISSUE TITLE
Changing the notes text editor

### ISSUE THREAD

**Issue by Hipomenes** [lfos/calcurse#83]
I love Calcurse! However, the documentation is not clear about how extactly to modify the visual variable... Calcurse keeps opening an old version of Vim rather than the one I generally use, so that my .vimrc doesn't work.

Thanks!
David

**Comment by lfos** [comment]
There are different options. Setting the `EDITOR` or `VISUAL` environment variables should work!

**Comment by lfos** [comment]
There also is `CALCURSE_EDITOR` now.
