### ISSUE TITLE
config.c: 589: configuration variable unknown: "appearance.headingpos"

### ISSUE THREAD

**Issue by adjunkth** [lfos/calcurse#86]
I use calcurse on my phone and on my computer and use Dropbox to sync the files:

Computer - Debian 9
calcurse version 4.2.1

Android 6.0
Termux
Calcurse version 4.3.0

The problem occurs when I have changed the files on my phone and tries to use the same files on my computer. However if I open up my conf file and erase the following two lines (Which seems to have been added by calcurse version 4.3.0):

appearance.headingpos=right-justified
format.dayheading=%B %-d, %Y

Then everything works fine. 

If I don't erase the files I get the following error message:
config.c: 589: configuration variable unknown: "appearance.headingpos"

and can not open the program

**Comment by hiqua** [comment]
In summary, either unknown configuration variables should be ignored instead of calcurse exiting, or the configuration format should not change between minor versions.

**Comment by lfos** [comment]
... or you should not synchronize configuration files accross different releases (sharing data files is okay).

**Comment by hiqua** [comment]
I never thought about using calcurse in termux, but I think I'll end up doing it as well, when it becomes possible.

Is there a way to specify the path of the configuration file without changing the path of the data files? (so `-D` does not work)

I have tried to use `-c` to specify the apts file, but the notes are still in the data directory, so it's not a good solution either.

I think being able to specify some configuration folder (which would also contain keys) different from the data folder would be a suitable workaround, and the changes should be rather minimal. It would then be easier to just sync the whole data folder, and use device-specific configuration files.

This assumes that the data (not configuration) format does not change, at least not too often.

@lfos if you're open to this I can look into it.

**Comment by adjunkth** [comment]
Yes of course

I like calcurse and would like to see it work. Calcurse works well in termux 
and that sounds like a good solution



onsdag 9 maj 2018 kl. 04:13:19 CEST skrev  Quentin Hibon:
> I never thought about using calcurse in termux, but I think I'll end up
> doing it as well, when it becomes possible.
> 
> Is there a way to specify the path of the configuration file without
> changing the path of the data files? (so `-D` does not work)
> 
> I have tried to use `-c` to specify the apts file, but the notes are still
> in the data directory, so it's not a good solution either.
> 
> I think being able to specify some configuration folder (which would also
> contain keys) different from the data folder would be a suitable
> workaround, and the changes should be rather minimal. It would then be
> easier to just sync the whole data folder, and use device-specific
> configuration files.
> 
> This assumes that the data (not configuration) format does not change, at
> least not too often.
> 
> @lfos if you're open to this I can look into it.

**Comment by lfos** [comment]
You can now use `-C` to specify an alternative configuration file.
