### ISSUE TITLE
403 forbidden while trying to access google calendar

### ISSUE THREAD

**Issue by holalluis** [lfos/calcurse#87]
this is the result I get from doing the command:

calcurse-caldav --init=keep-local

Connecting to apidata.googleusercontent.com...
Removing all objects from the CalDAV server...
Pushing new object d46bb7237b778f7252574c13e217e011e5595 to the server.
Pushing new object 021d043f8bc3b9a33e17ca8539f82d5f6e9bc to the server.
error: The server at apidata.googleusercontent.com replied with HTTP status code
error: 403 (Forbidden) while trying to access https://apidata.googleusercontent.
error: com/caldav/v2/{myemail}@gmail.com/events/021d043fbc3b9ea3317caf53982
error: d5febc.ics.

how to fix it?

**Comment by watersalesman** [comment]
Could you post your config file to better diagnose the issue? With sensitive information removed, of course.

**Comment by holalluis** [comment]
I think I was using an old version, I downloaded the last one from this repo and the problem disappeared, now it works great
