### ISSUE TITLE
Can't edit start time of appointments that don't have an end date

### ISSUE THREAD

**Issue by 991jo** [lfos/calcurse#89]
I am running on calcurse v4.3.0 from the arch linux repos.

When I want to edit an appointment which only has a start time and want to change the start time to a later time than the start time I receive the error message "Invalid time: start time must be before end time!".
Changing the start time to something earlier results in an appointment that lasts from the new time to the old time.

How to repeat:
1. add a new appointment without an end date
2. edit the start date of the appointment
3. change the start date to something that is after the current start date

**Comment by lhca** [comment]
The behaviour is somewhat counterintuitive and should probably be changed. The explanation is that an appointment always has an end time, but it may be the same as the start time in which case it's not displayed (internally it has a start time and a duration which is zero in this case). If the start time is increased, it comes after the end time and is disallowed; if it is decreased (as you did), the end time is displayed.
You can achieve what you want by moving the appointment.

**Comment by 991jo** [comment]
thanks for opening my eyes, I have never seen the move option.

**Comment by lfos** [comment]
I pushed a patch to `pu` that essentially makes editing the start time a move operation on punctual appointments.
