### ISSUE TITLE
add support for ISO date formats

### ISSUE THREAD

**Issue by fmv1992** [lfos/calcurse#92]
After reading the manual I cannot find a way to change dates displayed to a format different than the standard/American one:

    $ calcurse -r7 --format-apt='- %S -> %E\n\t%m\n%N'
    03/31/18:
    - x
        xxx
        xxx

    04/01/18:
    * y

    04/03/18:
    * z

I would like the dates to be displayed like 2018-03-04.

Is that possible?

**Comment by lhca** [comment]
The output date format is configured interactively and not from the command line.

Start calcurse and type "C" to enter the configuration menu. Then type "g" to enter the general options. Scroll down to format.outputdate and type "e" to edit the entry. It probably has the default value "%D", which is the american form. Change that to "%F" to get the ISO format you want.

**Comment by fmv1992** [comment]
Gret; thanks for pointing out. I was using an outdated version of calcurse which did not presented such option.
