### ISSUE TITLE
Calcurse eats most CPU power when run as root.

### ISSUE THREAD

**Issue by retiform** [lfos/calcurse#93]
I accidentally ran calcurse as root, and it put both of my CPUs at 100%

Not a major problem, but I do wonder why.

**Comment by retiform** [comment]
@lfos no speical settings.  I was running Debian Stable with xfce.

**Comment by lfos** [comment]
Can you consistently reproduce this issue, even with a fresh setup (no data)?

**Comment by hiqua** [comment]
Can't reproduce.

Debian Stretch (stable), calcurse 4.2.1-1.1.

Tried with `sudo calcurse`, as well as `sudo su` then `calcurse`.

**Comment by lfos** [comment]
Cannot reproduce. Please reopen with more details if you can.
