### ISSUE TITLE
pre-load hook doesn't work as expected in 4.3.0

### ISSUE THREAD

**Issue by vaygr** [lfos/calcurse#98]
I suspect 57dd3d6 broke it.

The use case is the following: I use scm to sync calendar data between nodes, so my `pre-load` hook essentially pulls data from a remote host, and then calcurse reloads data files on ^R or automatically.

The problem with that commit is that it now reloads only if the data's been changed, but it's never going to happen, because the hook is executed after modification check, not before as it should.

Is there a way to fix this? Thoughts?

**Comment by lfos** [comment]
I am not sure. The `pre-load` hook is supposed to be executed immediately before data is loaded. The reload function is supposed to load data if anything has changed. Assuming that these are semantics we want, everything works as expected.

I see that what you describe might be a valid use case, though. There are two options to get your desired behavior: 

1. Move the `pre-load` hook before the check such that it is executed even if nothing has changed.
2. Add another hook.

**Comment by lfos** [comment]
If we go with the first option, it might be a good idea to document this behavior at the same time.

**Comment by vaygr** [comment]
Right, because I think this hook is supposed to be used for modifying data quite often.

**Comment by vaygr** [comment]
Thanks @lfos, I'll keep it running for several days and report back about the status.

**Comment by vaygr** [comment]
Works as expected, so I think it's safe to close this one.
